### ISSUE TITLE
What sould be the "twitch_username"?

### ISSUE THREAD

**Issue by afucher** [TwitchLib/TwitchLib#1033]
Sorry, but the only way that I found to generate access_token is using the creation of an app in the twitch dev console.
There I have the 'client_id' and the application name, but both did not work on TwitchCliente Credentials.

I try to found some documentation related to this, but didn't have success.

Can someone help me with this?

**Comment by Syzuna** [comment]
In which context?
Are you talking about the TwitchClient property? thats just the user login of the account you connect to chat and the access token is associated with, so the client knows who it is for parsing purposes.

**Comment by afucher** [comment]
Hi @Syzuna , yes is the `TwitchClient.Initialize `

So the user should be mine? not from my application that I have registered on twitch?
And do you know where can I generate this access_token for my user? I didn't found any place to do that.

**Comment by afucher** [comment]
Just found it: https://twitchapps.com/tmi/

:)

**Comment by Syzuna** [comment]
If you want the bot to use your name and you dont register a new account on Twitch just for the bot with a different name then yes it would be your username
