### ISSUE TITLE
TwitchLib.Client still uses Microsoft.Extensions.Logging.Abstractions 2.1.1 while the API uses Microsoft.Extensions.Logging.Abstractions 3.1.5

### ISSUE THREAD

**Issue by patrick-dmxc** [TwitchLib/TwitchLib#1036]
TwitchLib.Client still uses Microsoft.Extensions.Logging.Abstractions 2.1.1 while the API uses Microsoft.Extensions.Logging.Abstractions 3.1.5.
This bring me to the Problem, i cant use both NugetPakeges in the same Project.

**Comment by swiftyspiffy** [comment]
This should be updated now and no longer a problem. Please reopen if it still is.
