### ISSUE TITLE
FollowerService too slow

### ISSUE THREAD

**Issue by MaZyGer** [TwitchLib/TwitchLib#1037]
Hello I want to achieve alerts in unity game engine and I needed new follower event. However, FollowerService seems to be slow. The alerts from streamelements triggers one or two seconds after pressing follow button while FollowerService triggers after maybe 30-60 seconds even I have there the minimum value of 1.

**Comment by Syzuna** [comment]
The Follows Helix API is cached by Twitch and therefore ofc slower. nothing we can do against Twitchside caching.
I would guess Streamelements uses sth like Webhooks or Eventsub to get realtime updates.

**Comment by MaZyGer** [comment]
Is EventSub planned? Or is there already something which provides in this lib already to try myself? If I read about it I think the hardest part is https and port 443.

**Comment by swiftyspiffy** [comment]
Syzuna has worked on TwitchLib's eventsub implementation here: https://github.com/TwitchLib/TwitchLib.EventSub.Webhooks but ya, I think eventsub/pubsub is probably what they're using.
