### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by arcueid-dev** [TwitchLib/TwitchLib#1038]
Hi. Do refresh token are needed or your lib are reconnecting on connection-token expires? Could you please give any description of this? I'm making a bot that should all time be connected to the Twitch channel because it's monitoring gift subs.

**Comment by swiftyspiffy** [comment]
Refreshing tokens is done via the Api component of Twitchlib. That being said, if your client will remain connected to chat and pubsub as long as the token was valid when first connecting.

For refreshing, you'd use this function: https://github.com/TwitchLib/TwitchLib.Api/blob/816b6d46af4edb89f9f1f54d3344cd752a8f043f/TwitchLib.Api/Auth/Auth.cs#L25
