### ISSUE TITLE
TwitchLib.Client.Modles won't load from other folder.

### ISSUE THREAD

**Issue by Haqz** [TwitchLib/TwitchLib#1040]
Hello so I'm trying to move all dll's from root folder to another using [probing](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/probing-element?redirectedfrom=MSDN) and for some reason this one dll won't load.
While not using probing everything works fine. Is there other way to do so?
Thanks in advance

**Comment by swiftyspiffy** [comment]
Not sure why this would be the case. If you have references to `Modles` in your code, it should be `Models`. Other than that, not sure. Feel free to reopen if you think this is an issue specific to twitchlib.
