### ISSUE TITLE
CustomReward Model MaxPerUserPerStreamSetting wrong json tag

### ISSUE THREAD

**Issue by H3adcode** [TwitchLib/TwitchLib#1042]
The data model of the custom reward response from Twitch has different field names for the MaxPerUserPerStreamSetting and MaxPerStreamSetting. 

Max per stream uses "max_per_stream" and max per user per stream uses "max_per_user_per_stream". The TwitchLib Model usese for both "max_per_stream", which leads to wrong values.

namespace TwitchLib.Api.Helix.Models.ChannelPoints
class CustomReward

        [JsonProperty(PropertyName = "max_per_user_per_stream_setting")]
        public MaxPerStreamSetting MaxPerUserPerStreamSetting { get; protected set; }
        [JsonProperty(PropertyName = "max_per_stream_setting")]
        public MaxPerStreamSetting MaxPerStreamSetting { get; protected set; }

class MaxPerStreamSetting is used for both

        [JsonProperty(PropertyName = "is_enabled")]
        public bool IsEnabled { get; protected set; }
        [JsonProperty(PropertyName = "max_per_stream")] <---
        public int MaxPerStream { get; protected set; }

It should be as follows for the max per user per stream setting

        [JsonProperty(PropertyName = "max_per_user_per_stream")] <---
        public int MaxPerUserPerStream { get; protected set; }

**Comment by Mahsaap** [comment]
Actually seems the json Tag is wrong  
![image](https://user-images.githubusercontent.com/13688718/120324123-a6064100-c2bc-11eb-94d4-3abede296a7a.png)
I'll update that.

**Comment by H3adcode** [comment]
Agree. Naming it "wrong property name" was misleading by me, sorry. The wrong json tag is actually the core issue as pointed out in the excerpt. Thank you!

**Comment by Mahsaap** [comment]
Thx for the heads up, I put a PR in.

**Comment by Mahsaap** [comment]
I was corrected, I was looking at eventsub. Let me look further

**Comment by Mahsaap** [comment]
At the moment the code represents the Helix docs example. However, they could be wrong and someone will need to see what the payload returned is to confirm.

**Comment by swiftyspiffy** [comment]
This seems to be correct now, no? Closing, feel free if it's not.

**Comment by H3adcode** [comment]
Unfortunately, it was only partially fixed. The JSON Tag was corrected but CustomReward.cs uses the wrong type for the setting.

TwitchLib.Api.Helix.Models.ChannelPoints.CustomReward
```
[JsonProperty(PropertyName = "max_per_stream_setting")]
public MaxPerStreamSetting MaxPerStreamSetting { get; protected set; }
[JsonProperty(PropertyName = "max_per_user_per_stream_setting")]
public MaxPerStreamSetting MaxPerUserPerStreamSetting { get; protected set; } <--- wrong type here
```

MaxPerUserPerStreamSetting.cs actually exists and is correct as far as I can tell, but it is not used in the CustomReward.

**Comment by swiftyspiffy** [comment]
Looking

**Comment by swiftyspiffy** [comment]
Should be fixed now :)

**Comment by H3adcode** [comment]
Thank you!
