### ISSUE TITLE
Command Uptime and Gameofstream 

### ISSUE THREAD

**Issue by AndreZila01** [TwitchLib/TwitchLib#1043]
Hey everyone,

i try devolpment my bot, when user use command "!uptime" and give all information about stream (HH:mm:SS).
But i try consult all codes about uptime and all codes is not worked, because have many differences in Package and have many variabels not declareted.

If you can help my to consult time of stream and the game of streammer play.

		
		ConnectionCredentials creds = new ConnectionCredentials("Andrezila1", "");
		
		TwitchClient client;

		String channel = "streammer";
		string BotNickname = "Andrezila1";

		internal void Connect(bool isLogging)
		{
			client = new TwitchClient();
			client.Initialize(creds, channel);
			client.OnConnected += Client_OnConnected;

			Console.WriteLine("[Bot]: Connecting...");

			if (isLogging)
				client.OnLog += Client_OnLog;

			client.OnError += Client_OnError;
			client.OnMessageReceived += Client_OnMessageReceived;
			client.OnChatCommandReceived += Client_OnChatCommandReceived;
			client.AddChatCommandIdentifier('$');

			client.Connect();
		}

		private async void Client_OnChatCommandReceived(object sender, OnChatCommandReceivedArgs e)
		{
			switch (e.Command.CommandText.ToLower())
			{
				
				case "uptime":
					//
					break;
			}

		}

		private void Client_OnLog(object sender, OnLogArgs e)
		{
			Console.WriteLine(e.Data);
		}

		private void Client_OnError(object sender, OnErrorEventArgs e)
		{
			throw new NotImplementedException();
		}

		private void Client_OnConnected(object sender, OnConnectedArgs e)
		{
			Console.WriteLine("[Bot]: Connected");
		}

		internal void Disconnect()
		{
			Console.WriteLine("[Bot]: Disonnecting and closing application");

			client.Disconnect();
		}

Thanks

**Comment by Mahsaap** [comment]
https://github.com/TwitchLib/TwitchLib.Api/blob/07beee545dcc51a2003304358a85d879a76b69f1/TwitchLib.Api.Helix/Streams.cs#L24

Call this using userlogins or userid and use the started on time in the stream object to calculate.

**Comment by AndreZila01** [comment]
@Mahsaap but one question. I think, i need call function right (GetStreamsAsync)?!??
But all value is null, ... communityids, gameids, languages, userlds and userLogin. How i can remove "null" and put values!??! I need go first in one class?!?

Thanks

**Comment by Mahsaap** [comment]
Userlogins:

**Comment by Mahsaap** [comment]
Getstreamsasync(userlogins: new list.......)

**Comment by AndreZila01** [comment]
Dude i dont understand your code... My objective is like this https://github.com/TwitchLib/TwitchLib/issues/425 code.

But not collect uptime, ... you can help my?!??

![image](https://user-images.githubusercontent.com/56931353/123711167-e929e480-d867-11eb-9fad-50e4779ad8f3.png)

**Comment by AndreZila01** [comment]
I find the solution. Thanks
