### ISSUE TITLE
How i can receive notification about raid, host and autohost?!?

### ISSUE THREAD

**Issue by AndreZila01** [TwitchLib/TwitchLib#1044]
Hey everyone,

i try devolpment my bot, but i see all sources and not found one code its working!!!

Can help me thanks.

**Comment by AndreZila01** [comment]
About host i use this code


		client.OnBeingHosted += OnBeingHosted;

		private static void OnBeingHosted(object sender, OnBeingHostedArgs e)
		{
			var channel = e.BeingHostedNotification.Channel;
			var host = e.BeingHostedNotification.HostedByChannel;
			var viewers = e.BeingHostedNotification.Viewers;

			Debug.Print($"Hey @{channel}, we just got hosted by {host} with {viewers} viewers Kappa");
		}

But not worked, cannot in the code!! Why?!?
About raids i dont have code at the moment

**Comment by AndreZila01** [comment]
String[] canal;
	string channel="x";
	canal = e.Command.ArgumentsAsString.Split(' ');

	var api = new TwitchAPI();
	api.Settings.ClientId = "";
	api.Settings.AccessToken = "";
	if (canal[0] == "")
		canal[0]=canal[1];
	var foundChannelResponse = await api.V5.Users.GetUserByNameAsync(canal[0]);
	var foundChannel = foundChannelResponse.Matches.FirstOrDefault();
	var stream = await api.V5.Streams.GetStreamByUserAsync(foundChannel.Id);
	string msg = $"{e.Command.ArgumentsAsString} has been streaming forand they've been playing {stream.Stream.Game}.";

	msg = $"Vão a correr ver o canal {canal[0]}, este pela última vez em {stream.Stream.Game}. Sigam o canal!!! https://twitch.tv/{canal[0]}";
	client.SendMessage(channel, msg);

	stream is null!!! Why?!?

![image](https://user-images.githubusercontent.com/56931353/124808511-f07f7b00-df56-11eb-896c-99306af7a889.png)

**Comment by swiftyspiffy** [comment]
To use OnBeingHosted, you have to be using the broadcaster user, not a bot user.

Stream objects are only populated when a stream is active/broadcaster is streaming. Trying to pull stream data for a broadcaster that isn't stream will return null.
