### ISSUE TITLE
List of Viewers

### ISSUE THREAD

**Issue by AndreZila01** [TwitchLib/TwitchLib#1050]
Hello everyone, ... 
How i can see list of all viewers?!? And detect if this people is mod, vip, viewers ou streammer??!

Thanks

**Comment by Syzuna** [comment]
https://github.com/TwitchLib/TwitchLib.Api/blob/master/TwitchLib.Api.Core/Undocumented/Undocumented.cs#L131

`var chatters = await api.Undocumented.GetChattersAsync(channelName);`

**Comment by AndreZila01** [comment]
Ok thanks for helping me. But in this solution of code, dont return broadcaster. But is not important thanks.
