### ISSUE TITLE
How to build and/or include TwitchLib locally via Visual Studio?

### ISSUE THREAD

**Issue by Snickbrack** [TwitchLib/TwitchLib#1051]
Hi guys I am currently struggling with Issue of the FollowerService of TwitchLib for which I wanted to include TwitchLib and its Components in my VS-Project to be able to debug it on my own.

But its really hacky to include TwitchLib into my Project as for example all of the Parts (API, Client, ...) are separated and I am getting weird Errors for missing Project Information.

Can you help me with this?

**Comment by swiftyspiffy** [comment]
You can either clone all of the relevant packages and reference them (as you stated), or you can use the nuget packages. Nuget is the easiest way to get all of them, and the fastest. https://www.nuget.org/packages/TwitchLib/
