### ISSUE TITLE
Check if streamer is online!?

### ISSUE THREAD

**Issue by AndreZila01** [TwitchLib/TwitchLib#1052]
I everyone, ... i need check if streammer is online or not!?! 

Thanks

**Comment by swiftyspiffy** [comment]
var resp = await api.Helix.Streams.GetStreams(userLogin: "my-streamer");
if(resp.Data.Length > 0) {
    // streamer is online
} else {
    // streamer is offline
}

**Comment by AndreZila01** [comment]
![image](https://user-images.githubusercontent.com/56931353/130520044-7ac22dac-843a-4a56-9c74-b0eb840a8f1a.png)
I cannot found, GetStreams

**Comment by swiftyspiffy** [comment]
It is indeed GetStreamsAsync.

**Comment by AndreZila01** [comment]
@swiftyspiffy sorry report this problem at the moment, but i dont found method Data.
Error:
Error	CS1061	 Task<GetStreamsResponse>' does not contain a definition for 'Data' and no accessible extension method 'Data' accepting a first argument of type 'Task<GetStreamsResponse>' could be found (are you missing a using directive or an assembly reference?)

![image](https://user-images.githubusercontent.com/56931353/133129104-687f82ee-3166-41ac-9786-e7c9437263a4.png)

Thanks

**Comment by AndreZila01** [comment]
Sorry to send this report @swiftyspiffy but i cann't found one solution. Can u help me?!?!

![image](https://user-images.githubusercontent.com/56931353/133131223-34ea801e-ac62-4e18-80fc-5dfa99405e81.png)

Thanks

**Comment by Mahsaap** [comment]
resp.Streams

**Comment by AndreZila01** [comment]
Sorry to delete mensage @Mahsaap, ... i try reset the token but is not token.

But i cannot run code?!? Why?!

![image](https://user-images.githubusercontent.com/56931353/133132504-232f021f-5f56-4f07-83f8-399f7f3f9519.png)


Thanks

**Comment by swiftyspiffy** [comment]
check your client id and access token are valid

**Comment by Mahsaap** [comment]
> check your client id and access token are valid

```
            TwitchAPI api = new TwitchAPI();
            api.Settings.ClientId = "client_id";
            api.Settings.AccessToken = "access_token"; // App Secret is not an Accesstoken
```

To add to that.

**Comment by AndreZila01** [comment]
@swiftyspiffy client id is new and valid, i create one now.
@Mahsaap i have like this:

![image](https://user-images.githubusercontent.com/56931353/133133371-e08302b7-0d3b-4743-afbf-cac98b532be9.png)

**Comment by AndreZila01** [comment]
I dont understand, ... i can use command Users.GetUserByNameAsync but i can't GetUserByIDAsync?!? Why?!?! @swiftyspiffy 

![image](https://user-images.githubusercontent.com/56931353/133519177-46bfc564-5fef-420e-b2d5-f039f282e2ce.png)
![image](https://user-images.githubusercontent.com/56931353/133519262-51e286f3-141a-4357-bb12-dcaaad666b05.png)

**Comment by swiftyspiffy** [comment]
because `andrezila1` and `souajuba` are not userids, they're usernames. Their associated userids are `102586568` (`souajuba`) and `155285178` (`andrezila1`)

**Comment by AndreZila01** [comment]
ok, ... i understand. But please change mensagem error. And thanks

**Comment by swiftyspiffy** [comment]
Is `3.` not the correct problem here? `3. You requested a username when the server was expecting a userid`?
