### ISSUE TITLE
Getting Followers through FollowerService takes very long/hangs

### ISSUE THREAD

**Issue by Snickbrack** [TwitchLib/TwitchLib#1053]
Hi,

I have seen it in some Issues before that the FollowerService-Performance heavily depends on Twitch API.

But could there be some more things that could affect the functionality of the FollowerService?

**Comment by swiftyspiffy** [comment]
You can update the interval for the follower service, but at the end of the day, all it's doing is polling the Twitch API for updates, and comparing a local cache against the results, and firing an event for any discrepancies. Whatever Twitch gives us is what we have to work with.

**Comment by swiftyspiffy** [comment]
Closing this, feel free to reopen if needed.
