### ISSUE TITLE
Emote API

### ISSUE THREAD

**Issue by delasource** [TwitchLib/TwitchLib#1054]
How do i access the Emote API?

Is this not implemented yet?

https://dev.twitch.tv/docs/irc/emotes#getting-channel-emotes

**Comment by swiftyspiffy** [comment]
Something like:
```
var api = new TwitchLib.Api.TwitchApi();
api.Settings.ClientId = "my-client-id";
api.Settings.AccessToken = "my-access-token";
var result = await api.Helix.Chat.GetEmoteSetsAsync("emote-set-id");
```

**Comment by genyx** [comment]
ok but where do i get this "emote-set-id" given that i only have the channel name/id ?

**Comment by swiftyspiffy** [comment]
Closing, feel free to reopen if needed.
