### ISSUE TITLE
OnUserJoined Event causes my bot to lock up until all joined users have been processed

### ISSUE THREAD

**Issue by bilago** [TwitchLib/TwitchLib#1055]
In normal usage, my bot works without delay, however every time I get raided by large raids (50-300) so far, my bot stops replying to any chat commands until all the users have been checked. 

I subscribe to the event 

`client.OnUserJoined += Client_OnUserJoined`

My method is
````
private async void Client_OnUserJoined(object sender, OnUserJoinedArgs e)
      {
           _ = UserJoined(e).ConfigureAwait(false);
      } 
````
which should run my UserJoined Task asynchronously without waiting, which I thought would avoid the bot response issues.

UserJoined is as follows:
````
private async Task UserJoined(OnUserJoinedArgs e)
        {
           //This checks an already populated hashset<string> for bots, since I don't want to waste processing on them
            if (bots?.Any(e.Username.ToUpper().Equals) ?? false)
            {
                await Logging.Write($"A bot has joined: {e.Username}", Logging.Severity.Trace);
                return;
            }
            await Logging.Write($"User Joined: {e.Username}", Logging.Severity.Trace);

           //this checks a pre Existing list of trolls who make multiple accounts to instantly ban them when they join
            if (_Kryptonite != null && await _Kryptonite?.KryptoniteCheck(new UserMessage(e.Channel, e.Username, false)))
                return;
         //this is another async task that I don't wait for, that just does an API call to see if they are following me or not
            _ = IsUserFollowing(e.Username).ConfigureAwait(false);
        }
````

And IsUserFollowing calls GetUserByName to get the Joined user's ID from their username:
````
     private async Task<User> GetUserByName(params string[] usernames)
        {
            var result = await API.Helix.Users.GetUsersAsync(logins: usernames.ToList());
            return result.Users.FirstOrDefault();
        }
````

which then the userid is used to get if they are a follower or not:

````
var isFollower = await API.Helix.Users.GetUsersFollowsAsync(fromId: userID, toId: ChannelID);
````

I hope this is enough information. According to my logs the bulk amount of users who joined were at 06:16:17pm and the bot wasn't responsive until 6:16:30 pm (13 seconds) once every single user that joined in on the raid finished being checked if they are a follower or not.

Am I implementing this correctly?

**Comment by Syzuna** [comment]
Try to dont use ConfigureAwait(false) in application level code, this might cause some issues.
I am not sure if its the root of your issues but its sth I saw in a quick look at 7:40 am

**Comment by Mahsaap** [comment]
Additionally I would try this without any extras. So use console.writeline for example so it's only the lib being tested etc... Something we know is fast. This way you can troubleshoot what the cause is. It could very well be the lib but, some solid test to solidify it would be great.

**Comment by bilago** [comment]
> Try to dont use ConfigureAwait(false) in application level code, this might cause some issues.
> I am not sure if its the root of your issues but its sth I saw in a quick look at 7:40 am

Sorry I wasn't clear in my original message, but the ConfigureAwait(false) was something I added to try and fix the issue, but I was raided after adding that and there wasn't any difference in speed.

Do you have any idea how I can test this without having to wait for a large raid? Again normal usage with users trickling in, the performance is fine.

**Comment by Syzuna** [comment]
The library might not do that.
But we also never had anyone coming in with such an issue and we know about some bigger projects using TwitchLib.
Can look into it tho.

But a quick fix I could think of to do on your site would be

` cs
           Task.Run(async () =>
            {
                await UserJoined(e);
            });
`

**Comment by bilago** [comment]
> The library might not do that.
> But we also never had anyone coming in with such an issue and we know about some bigger projects using TwitchLib, so it surprises me we never had issues reported like that before.
> Can look into it tho.
> 
> But a quick fix I could think of to do on your site would be
> 
> ` private async void Client_OnUserJoined(object sender, OnUserJoinedArgs e) { Task.Run(async () => { await UserJoined(e); }); } `

Thanks for your suggestion. I really appreciate it After I made my last reply here I modified my event handlers to this, which is similar to what you're suggesting:

````
                client.OnMessageReceived += async (s, e) => await Client_OnMessageReceived(s,e).ConfigureAwait(false);
                client.OnUserJoined += async (s,e) => await Client_OnUserJoined(s,e).ConfigureAwait(false);
                client.OnChatCommandReceived += async (s, e) => await ProcessCommand(e);
````
And while I didn't get any large raids today, I did get hit with 1800 follow bots (sadface) and they didn't slow the bot down at all so this might be the winning change - I'll update if it doesn't.

**Comment by swiftyspiffy** [comment]
Sounds like that solution may be workiing. Feel free to reopen if needed.
