### ISSUE TITLE
All games streamer play on stream

### ISSUE THREAD

**Issue by AndreZila01** [TwitchLib/TwitchLib#1056]
How i can see all games, streamer play in live?!?

![image](https://user-images.githubusercontent.com/56931353/133896071-feba071a-a367-4615-8774-1cae2fb5ef7c.png)

![image](https://user-images.githubusercontent.com/56931353/133896067-af584b53-250e-49da-b478-18673a4498ec.png)

Thanks!!

**Comment by swiftyspiffy** [comment]
chapters are not available when indexing vods via the API

**Comment by AndreZila01** [comment]
Thanks!!
