### ISSUE TITLE
Login authentication failed

### ISSUE THREAD

**Issue by 454406** [TwitchLib/TwitchLib#1057]
Hi,
My bot worked perfectly fine until yesterday (8 October 2021).
![image](https://user-images.githubusercontent.com/62300856/136665923-ecfe7e81-7d2b-4841-b2f9-be13a05e4fa2.png)
"Login authentication failed"
I checked and resetted the stream key, which normally worked and replaced it with an oauth token and resetted that (variable: Token).
I added, checked and removed the channel id (variable: ClientId).
I toggled api.Settings.SkipAutoServerTokenGeneration.
And I added, checked and removed the secret (variable: Secret).
All resulted in the same error.
I tried the good old 'restart' too, but it didn't magically fix itself.

**Comment by Mahsaap** [comment]
Twitch just did a reset with the leak. Regenerate token through authentication flow should fix it.
