### ISSUE TITLE
Api Bad Resource Exception

### ISSUE THREAD

**Issue by 454406** [TwitchLib/TwitchLib#1058]
I'm getting an error when using the TwitchAPI methods.
![image](https://user-images.githubusercontent.com/62300856/136711112-44ec0e2f-4865-45dc-97ca-6ffb88567c80.png)
This exception gets raised no matter what method or parameters I use.
The weird thing is that I use that same instance to login to the stream, and that works...
(I tried setting SkipDynamicScopeValidation to true, no effect)

**Comment by 454406** [comment]
I wanted to use
`string game = (await api.V5.Channels.GetChannelByIDAsync("xxx")).Game;`
But I tried this as well
`api.V5.Users.GetUserByNameAsync("username")`

**Comment by Syzuna** [comment]
V5 is deprecated by Twitch and will be decommisioned end of February next year.
If you didnt make calls to V5 before July 15 2021 with that clientId, you arent able to access v5 anymore and that woul also explain your exception.

Try to use Helix instead

**Comment by 454406** [comment]
What AuthScope would I need to use? Cause now I'm getting a different error:
TwitchLib.Api.Core.Exceptions.BadScopeException: 'Your request was blocked due to bad credentials (Do you have the right scope for your access token?).'

**Comment by 454406** [comment]
> What is the id of the channel your trying to get?
> 
> also keep in mind things are a bit dynamic due to the recent security incident, so it’s possible you’re getting one-off failures.

The id is a nine digit number.
But yes, keeping the security breach in mind, thanks!

**Comment by 454406** [comment]
![image](https://user-images.githubusercontent.com/62300856/136712507-7d8eddb6-deb0-432c-ab28-635ae1016a27.png)

**Comment by Syzuna** [comment]
can you screenshot the actual code that you wrote?
cant see much in decompiled framework code ^^

**Comment by 454406** [comment]
I fixed it by getting a token somewhere else (more scopes)
