### ISSUE TITLE
Error in topic

### ISSUE THREAD

**Issue by UrClockwerkband** [TwitchLib/TwitchLib#1059]
for listen that reward is redeemed twitchlib using a `community-points-channel-v1` but twitch endpoint is `channel-points-channel-v1`
is this correct?

**Comment by Syzuna** [comment]
we used an older undocumented topic there yes.
that topic was deprecated in TwitchLib and replaced by channel-points-channel-v1.
that change now also should be in the latest all-in one package TwitchLib (just updated to the latest versions of the individual packages)

**Comment by UrClockwerkband** [comment]
There is some workaround now? I need to get channel point redeemed event now, but don't want to create an event listener for that with one more web socket
