### ISSUE TITLE
Proxy supports missing in nuget package

### ISSUE THREAD

**Issue by Esgok** [TwitchLib/TwitchLib#1060]
Hello, i just saw the commits about proxy support. But there is no proxy support in nuget package. I could not use the one on the commit. There are a lot of errors and changes between that and lastest version.

**Comment by Mahsaap** [comment]
I though Client proxy support was removed years ago. What commits are you refering to?

**Comment by Esgok** [comment]
https://github.com/TwitchLib/TwitchLib/search?q=proxy&type=commits

**Comment by Mahsaap** [comment]
Ya those are 2017 I'm pretty sure they were removed because they were getting abused.
