### ISSUE TITLE
Prediction status

### ISSUE THREAD

**Issue by RNGIllSkillz** [TwitchLib/TwitchLib#1061]
Where can i get prediction status?
API.Helix.Predictions.GetPredictions doesnt seem to return it.

**Comment by swiftyspiffy** [comment]
Can you share your code

**Comment by RNGIllSkillz** [comment]
`public void GetCurrentPred()
        {
            var Predictions = API.Helix.Predictions.GetPredictions(BrodcasterID).Result;
            PredID = Predictions.Data.First().Id;
            winID = Predictions.Data.First().Outcomes.First().Id;
            loostID = Predictions.Data.First().Outcomes.Last().Id;
        }`
I assume that prediction STATUS should be here Predictions.Data.First().STATUS

**Comment by Mahsaap** [comment]
Looks like these are missing, i will PR them tonight.  `      "prediction_window": 600,
      "status": "",
      "created_at": "",
      "ended_at": ,
      "locked_at": `

**Comment by RNGIllSkillz** [comment]
Thanks!

**Comment by RNGIllSkillz** [comment]
?Any luck with
`[JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("created_at")]
        public DateTimeOffset CreatedAt { get; set; }

        [JsonProperty("ended_at")]
        public object EndedAt { get; set; }

        [JsonProperty("locked_at")]
        public object LockedAt { get; set; }`

**Comment by RNGIllSkillz** [comment]
So I added missing responses to Predictions. Its returns a value now, but its returning it as a string. How to convert it to PredictionStatusEnum ?

**Comment by swiftyspiffy** [comment]
Mahsaap added the missing fields here: https://github.com/TwitchLib/TwitchLib.Api/commit/a4d3566398b25883e9e5ed127cee09e5c9403f73
