### ISSUE TITLE
bot stops responding after a few hours

### ISSUE THREAD

**Issue by antedebaas** [TwitchLib/TwitchLib#1064]
I'm creating a bot using TwitchLib.
However i noticed that after a few hours it just stops responding to commands. It reieves them but does not seem to trigger Client_OnMessageReceived
It does trigger Client_OnMessageReceived when the bot is started for a few hours but after a while it just stops responding.
the program is still running and connected to twitch (e.g. did not hang or crash).

it runs on a (Rocky) Linux server in screen.
The code is basicly a copy from the README.md code but extended.
```
2021-11-25 21:04:33.708 +00:00 [INF] 11/25/2021 9:04:33 PM: <botname> - Received: @badge-info=subscriber/2;badges=moderator/1,subscriber/2;clie
nt-nonce=26d7f1c3510c67f77365b21b2766ecb8;color=#7CB222;display-name=<my username>;emotes=;first-msg=0;flags=0-4:;id=7e4b4527-22d2-4c7b-9a8e-ba14
dac3376b;mod=1;room-id=29034865;subscriber=1;tmi-sent-ts=1637874273536;turbo=0;user-id=462563499;user-type=mod :<my username>!<my username>@<my username>.tmi.twitch.tv PRIVMSG #<channel> :!beep
```

**Comment by Syzuna** [comment]
Hey a few questions to be able to assess this better.

What version are you using?
What is the last message that your bot logs?
Are there any errors/exceptions?
Are there any Errors coming through in the OnLog?

**Comment by swiftyspiffy** [comment]
+1 The last couple logs in OnLog would be super helpful here.

**Comment by antedebaas** [comment]
I did an test with 2 versions running, one with just the code from the Twitchlib.Client - CSharp example and one with my added code.
The plain Twitchlib.Client - CSharp version is still responding however the one with my added code is not.
They both run on the same server in seperate screen sessions so the enviroment is exactly the same.

The problem must be in my added code not TwitchLib so i'm closing the issue.
