### ISSUE TITLE
Unaccounted for

### ISSUE THREAD

**Issue by Pychro** [TwitchLib/TwitchLib#1066]
I ran my capstone project today and got this new error below. Previously I've been able to run it just fine and connect to channels with no problem and I haven't touched the code relating to this. I have an onJoin event that never runs and the events for detecting new subscribers also does not trigger anymore.

12/2/2021 8:57:04 PM: pychbot - Should be connected!
12/2/2021 8:57:04 PM: pychbot - Received: :tmi.twitch.tv 001 pychbot :Welcome, GLHF!
12/2/2021 8:57:04 PM: pychbot - Received: :tmi.twitch.tv 002 pychbot :Your host is tmi.twitch.tv
12/2/2021 8:57:04 PM: pychbot - Received: :tmi.twitch.tv 003 pychbot :This server is rather new
12/2/2021 8:57:04 PM: pychbot - Received: :tmi.twitch.tv 004 pychbot :-
12/2/2021 8:57:04 PM: pychbot - Received: :tmi.twitch.tv 375 pychbot :-
12/2/2021 8:57:04 PM: pychbot - Received: :tmi.twitch.tv 372 pychbot :You are in a maze of twisty passages, all alike.
12/2/2021 8:57:04 PM: pychbot - Received: :tmi.twitch.tv 376 pychbot :>
12/2/2021 8:57:04 PM: pychbot - Received: :tmi.twitch.tv CAP * ACK :twitch.tv/membership
12/2/2021 8:57:04 PM: pychbot - Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/membership (please create a TwitchLib GitHub issue :P)
12/2/2021 8:57:05 PM: pychbot - Received: :tmi.twitch.tv CAP * ACK :twitch.tv/commands
12/2/2021 8:57:05 PM: pychbot - Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/commands (please create a TwitchLib GitHub issue :P)
12/2/2021 8:57:05 PM: pychbot - Received: :tmi.twitch.tv CAP * ACK :twitch.tv/tags
12/2/2021 8:57:05 PM: pychbot - Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/tags (please create a TwitchLib GitHub issue :P)

```cs
 ConnectionCredentials credentials = new ConnectionCredentials("Pychbot", "[removed]");
            var clientOptions = new ClientOptions
            {
                MessagesAllowedInPeriod = 750,
                ThrottlingPeriod = TimeSpan.FromSeconds(30)
            };
            WebSocketClient customClient = new WebSocketClient(clientOptions);
            client = new TwitchClient(customClient);
            client.Initialize(credentials, streamerUser); //Inserted after user selected

            client.OnLog += Client_OnLog;
            client.OnJoinedChannel += Client_OnJoinedChannel;
            client.OnNewSubscriber += Client_OnNewSubscriber;
            client.OnReSubscriber += Client_OnReSubscriber;
            client.OnGiftedSubscription += Client_OnGiftedSubscription;


            client.Connect(); ```

**Comment by Mahsaap** [comment]
Unaccounted for is just that, unaccounted for and not going to affect your code.
Make sure your library is up to date, and you may also have an expired token and just need to generate a new one.

**Comment by Pychro** [comment]
I updated and the same problem is occurring and I tried to update the token (did so incorrectly and got an error about logging in and then did it correctly) and still got the same problem. I know its not working because the output should be creating a new line every time a chat message is sent but it is not.

**Comment by swiftyspiffy** [comment]
So the `:tmi.twitch.tv CAP *` unaccounted fors are more or less expected (and if you're using the latest code from dev branch/prerelease in nuget, they should no longer show in the logs). If you're still having problems with connecting, lmk.

Also I would expect your log to be a little larger than that? Is that really the end? Can you print out `streamerUser` at the time of the OnConnected event? Just to confirm the field is populated correctly at the time of joining a channel (which happens at OnConnected internally).

**Comment by Pychro** [comment]
> 

I am currently updated to 3.3.0 and I am still having issues with connecting. I've copied the entire log this time.

'SubathonWPF.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\Scoob\source\repos\SubathonWPF\bin\Debug\SubathonWPF.exe'. Symbols loaded.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.Desktop.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Step into: Stepping over non-user code 'SubathonWPF.App..ctor'
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Step into: Stepping over non-user code 'SubathonWPF.App.InitializeComponent'
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\Users\Scoob\source\repos\SubathonWPF\bin\Debug\XamlRadialProgressBar.DotNet.dll'. 
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\Users\Scoob\source\repos\SubathonWPF\bin\Debug\Xceed.Wpf.Toolkit.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\xamldiagnostics\Framework\x86\Microsoft.VisualStudio.DesignTools.WpfTap.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\SMDiagnostics\v4.0_4.0.0.0__b77a5c561934e089\SMDiagnostics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Internals\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Internals.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll'. 
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\SysNative\WinMetadata\Windows.UI.winmd'. Module was built without symbols.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\SysNative\WinMetadata\Windows.Foundation.winmd'. Module was built without symbols.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.WindowsRuntime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.WindowsRuntime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.WindowsRuntime\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.WindowsRuntime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x29f0 has exited with code 0 (0x0).
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\Users\Scoob\source\repos\SubathonWPF\bin\Debug\TwitchLib.Client.Models.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\Users\Scoob\source\repos\SubathonWPF\bin\Debug\TwitchLib.Communication.dll'. 
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\Users\Scoob\source\repos\SubathonWPF\bin\Debug\TwitchLib.Client.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\Users\Scoob\source\repos\SubathonWPF\bin\Debug\TwitchLib.Client.Enums.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SubathonWPF.exe' (CLR v4.0.30319: SubathonWPF.exe): Loaded 'C:\Users\Scoob\source\repos\SubathonWPF\bin\Debug\Microsoft.Extensions.Logging.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
12/4/2021 5:35:45 AM: pychbot - Connecting to: wss://irc-ws.chat.twitch.tv:443
12/4/2021 5:35:45 AM: pychbot - Should be connected!
12/4/2021 5:35:46 AM: pychbot - Received: :tmi.twitch.tv 001 pychbot :Welcome, GLHF!
12/4/2021 5:35:46 AM: pychbot - Received: :tmi.twitch.tv 002 pychbot :Your host is tmi.twitch.tv
12/4/2021 5:35:46 AM: pychbot - Received: :tmi.twitch.tv 003 pychbot :This server is rather new
12/4/2021 5:35:46 AM: pychbot - Received: :tmi.twitch.tv 004 pychbot :-
12/4/2021 5:35:46 AM: pychbot - Received: :tmi.twitch.tv 375 pychbot :-
12/4/2021 5:35:46 AM: pychbot - Received: :tmi.twitch.tv 372 pychbot :You are in a maze of twisty passages, all alike.
12/4/2021 5:35:46 AM: pychbot - Received: :tmi.twitch.tv 376 pychbot :>
12/4/2021 5:35:46 AM: pychbot - Received: :tmi.twitch.tv CAP * ACK :twitch.tv/membership
12/4/2021 5:35:46 AM: pychbot - Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/membership (please create a TwitchLib GitHub issue :P)
12/4/2021 5:35:46 AM: pychbot - Received: :tmi.twitch.tv CAP * ACK :twitch.tv/commands
12/4/2021 5:35:46 AM: pychbot - Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/commands (please create a TwitchLib GitHub issue :P)
12/4/2021 5:35:46 AM: pychbot - Received: :tmi.twitch.tv CAP * ACK :twitch.tv/tags
12/4/2021 5:35:46 AM: pychbot - Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/tags (please create a TwitchLib GitHub issue :P)
The thread 0x6340 has exited with code 0 (0x0).
The thread 0x3a6c has exited with code 0 (0x0).
The thread 0x4374 has exited with code 0 (0x0).
The thread 0x64e8 has exited with code 0 (0x0).

This is after adding the following to the onJoin event:

```cs
private void Client_OnJoinedChannel(object sender, OnJoinedChannelArgs e)
        {
            Console.WriteLine(streamerUser);
            client.SendMessage(e.Channel, "Pychbot has connected");
        }
```

**Comment by swiftyspiffy** [comment]
I assume you're consuming from NuGet? `3.3.0` is the latest TwitchLib version, which has dependencies on `TwitchLib.Client`, `TwitchLib.PubSub`, and `TwitchLib.Api`. For the `TwitchLib.Client` dependency, can you make sure `Show pre-release packages` is checked in your NuGet browser, and consume the latest pre-release one? It should look something like `3.2.5-preview-ebowadaoksndoasndoasndoasdioasn`.

**Comment by Pychro** [comment]
I am using NuGet and Visual Studios. I was running 3.2.4 for the TwitchLib.Client and have now updated to the latest 3.2.5. So now it does take away the unaccounted for but its still not joining the channel.

12/4/2021 6:51:51 AM: pychbot - Connecting to: wss://irc-ws.chat.twitch.tv:443
12/4/2021 6:51:51 AM: pychbot - Should be connected!
12/4/2021 6:51:52 AM: pychbot - Received: :tmi.twitch.tv 001 pychbot :Welcome, GLHF!
12/4/2021 6:51:52 AM: pychbot - Received: :tmi.twitch.tv 002 pychbot :Your host is tmi.twitch.tv
12/4/2021 6:51:52 AM: pychbot - Received: :tmi.twitch.tv 003 pychbot :This server is rather new
12/4/2021 6:51:52 AM: pychbot - Received: :tmi.twitch.tv 004 pychbot :-
12/4/2021 6:51:52 AM: pychbot - Received: :tmi.twitch.tv 375 pychbot :-
12/4/2021 6:51:52 AM: pychbot - Received: :tmi.twitch.tv 372 pychbot :You are in a maze of twisty passages, all alike.
12/4/2021 6:51:52 AM: pychbot - Received: :tmi.twitch.tv 376 pychbot :>
12/4/2021 6:51:52 AM: pychbot - Received: :tmi.twitch.tv CAP * ACK :twitch.tv/membership
12/4/2021 6:51:52 AM: pychbot - Received: :tmi.twitch.tv CAP * ACK :twitch.tv/commands
12/4/2021 6:51:52 AM: pychbot - Received: :tmi.twitch.tv CAP * ACK :twitch.tv/tags
The thread 0x3978 has exited with code 0 (0x0).

and I get nothing else after.

Edit:
So I still wasn't getting anything but now I've manually coded in the streamerUser and it connected fine.... So it must be messed up somewhere else. Thanks for the help!
