### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by BotJames312** [TwitchLib/TwitchLib#1069]
Hey everyone,

My token account is expired, and i need a new token. I try refresh my token but dont work ...  give me "TwitchLib.Api.Core.Exceptions.InvalidCredentialException: 'A Client-Id or OAuth token is required to use the Twitch API. If you previously set them in InitializeAsync, please be sure to await the method.'"

![Code](https://user-images.githubusercontent.com/93090977/147388805-8cb6e368-a3cc-4d27-a81d-00befc13bdd8.png)

But i have the same strings in call of Api and work.
And one other question ... how i can "expand" the time to expired token?? I do request like in website and token is valid to 4 hours.
I use like this https://id.twitch.tv/oauth2/token?grant_type=refresh_token&refresh_token=<refresh_token>&client_id=<client_id>&client_secret=<client_secret>.

Thanks and merry christmas

**Comment by Mahsaap** [comment]
I believe the API call cant get a refresh if the token if it is expired, you have to use the code prior to expiry (the expiry time is given when generated) 

@Syzuna can you verify that.

**Comment by BotJames312** [comment]
But it work when I call the api

**Comment by BotJames312** [comment]
I try one second time, ... and return this 
![image](https://user-images.githubusercontent.com/93090977/147822401-d9a83267-73db-4e90-870e-21ab7ba686a2.png)

**Comment by JulanDeAlb** [comment]
I've got this Error too on refreshing AccessToken using RefreshAuthTokenAsync() : Ausnahme ausgelöst: "TwitchLib.Api.Core.Exceptions.InvalidCredentialException" in mscorlib.dll
Pasting the same ClientID, ClientSecret and Refresh Token in my Twurple Bot, it refreshes my accessToken and connect to twitch chat

**Comment by Syzuna** [comment]
> I believe the API call cant get a refresh if the token is expired, you have to use the code prior to expiry (the expiry time is given when generated)
> 
> @Syzuna can you verify that.

actually that doesnt matter.

Will investigate later/tomorrow depending on timezones

**Comment by JulanDeAlb** [comment]
i fixed it by doing: `
var api = new TwitchAPI();
api.Settings.ClientId = Properties.Chatbot.Default.clientID;` instead of inserting the ClientID directly in RefreshAuthTokenAsync()

**Comment by swiftyspiffy** [comment]
I'm thinking we need to pass the client id here as well? https://github.com/TwitchLib/TwitchLib.Api/blob/816b6d46af4edb89f9f1f54d3344cd752a8f043f/TwitchLib.Api/Auth/Auth.cs#L46 will need to investigate further, but that's my guesserino.

**Comment by Syzuna** [comment]
its passed as a getParam here https://github.com/TwitchLib/TwitchLib.Api/blob/816b6d46af4edb89f9f1f54d3344cd752a8f043f/TwitchLib.Api/Auth/Auth.cs#L38-L44 so that should be fine

**Comment by Syzuna** [comment]
actually no you are right bcs the Client-ID header is set as well later on soe yeah it needs to be passed down or we need to disable automatic header injection for ApiVersion.Void

**Comment by swiftyspiffy** [comment]
> actually no you are right bcs the Client-ID header is set as well later on soe yeah it needs to be passed down or we need to disable automatic header injection for ApiVersion.Void

This sounds like the right thing to do (disable header injection for ApiVersion.Void), since I believe it is used in third party calls.

**Comment by JulanDeAlb** [comment]
Sry for the new message, first one was a mess.
`api.Settings.ClientId = clientID;`
`await api.Auth.RefreshAuthTokenAsync(refreshToken, clientSecret);` 
Works and 
`await api.Auth.RefreshAuthTokenAsync(refreshToken, clientSecret, clientID);` Doesnt

**Comment by Syzuna** [comment]
yeah that makes sense actually.
we currently inject the client id header on every request even if its not needed here for obvious reasons.
but the injected header does not use the overwritten clientId you passed into the method bcs we didnt pass it down properly.

but the best course of action would be to not inject headers anyway as they are not requested by Twitch

**Comment by Syzuna** [comment]
@JulanDeAlb if your fancy and have some time to spare might I bother you to test with the fixes currently in https://github.com/TwitchLib/TwitchLib.Api/tree/fixes/authrefresh ?

**Comment by JulanDeAlb** [comment]
> @JulanDeAlb if your fancy and have some time to spare might I bother you to test with the fixes currently in https://github.com/TwitchLib/TwitchLib.Api/tree/fixes/authrefresh ?

Yeah sure, give me a few minutes, i will try

**Comment by JulanDeAlb** [comment]
Im sorry, i cant get it to work with the new files, dont know how to import/upgrade them. First 20h using C#

**Comment by Syzuna** [comment]
dont worry.
the current structure makes it hard bcs there are many different projects to seperate stuff.
didnt know it was your first day in the .NET ecosystem sorry ^^

**Comment by JulanDeAlb** [comment]
All good, not bad ^^ Fortunately I learn it quickly as long as I know how it is done. ^^

**Comment by BotJames312** [comment]
Hey @swiftyspiffy, ... you can explain how i can refresh my token?!? Thanks

**Comment by JulanDeAlb** [comment]
> Hey @swiftyspiffy, ... you can explain how i can refresh my token?!? Thanks

Try using 
`api.Settings.ClientId = clientID;`
`await api.Auth.RefreshAuthTokenAsync(refreshToken, clientSecret);` 

Instead of 
`await api.Auth.RefreshAuthTokenAsync(refreshToken, clientSecret, clientID);`

**Comment by BotJames312** [comment]
@JulanDeAlb I'm waiting 3 minutes and nothing...
why!?!? Client secret is authToken???

![Time waiting](https://user-images.githubusercontent.com/93090977/150699767-3cf2e629-0225-4dd2-99f9-cf6ef7a85a78.png)
![Code](https://user-images.githubusercontent.com/93090977/150699842-81dd6cb6-8e78-4f18-94fe-329e839dbb3c.png)

**Comment by JulanDeAlb** [comment]
@BotJames312 
Im using SQLite to save the ClientID, ClientSecret, RefreshToken and AccessToken
This it what it looks for me
I set the ClientID using `api.Settings.ClientId = "yourClientID"`
awaiting the RefreshAuthTokenAsync without the ClientID since this doesnt work for now and the new AccessToken should be saved for you under dssss.AccessToken which you can use or save
![image](https://user-images.githubusercontent.com/67780894/150701834-c87989ec-95d6-4547-a21a-d9a819ec10b4.png)

**Comment by BotJames312** [comment]
@JulanDeAlb this token is valid to 60 days or 4h!?!?

**Comment by Mahsaap** [comment]
When your refresh you get a duration.

**Comment by BotJames312** [comment]
@JulanDeAlb ... ehn. I'm waiting and waiting and nothing!! Why?!? Client Secret i collect here [twitch dev](https://dev.twitch.tv/console/apps/) right??

![code](https://user-images.githubusercontent.com/93090977/150874130-ce02c236-7a54-42e7-bfb8-aa5efe33097d.png)
![time](https://user-images.githubusercontent.com/93090977/150874142-5f788056-f333-4641-8ff8-614ddc00c304.png)

@Mahsaap yes ... but your [token is valid for x hours/days](https://discuss.dev.twitch.tv/t/pubsub-oauth-token-help/28801/4)

**Comment by swiftyspiffy** [comment]
![724Mt0582](https://user-images.githubusercontent.com/9569194/150875899-bc58d35d-8e94-4684-832b-a8c1a3461eb2.png)

**Comment by BotJames312** [comment]
Ok ... now working. The problem is how i can insert clientId. Thanks!!!

**Comment by swiftyspiffy** [comment]
Sounds like this is resolved.
