### ISSUE TITLE
I am not able to Install TwitchLib to my C# Net Form Application Project

### ISSUE THREAD

**Issue by tuncileri** [TwitchLib/TwitchLib#1070]
I am having issues with adding TwitchLib nuget package from the latest package manager UI&console. I ma using Visual Studio 2019.

Problem as seen below:

![fa2il](https://user-images.githubusercontent.com/22811535/148185116-db57a09d-a718-4945-8f47-038a782293ec.jpg)
![fail](https://user-images.githubusercontent.com/22811535/148185127-e7dea352-8179-4447-895e-e093b51cd264.jpg)

I double check the source list in Nuget Package Manager Settings, cleaned up Temp Nuget Files, but no luck.

**Comment by Syzuna** [comment]
Fixed.
See #1080 for more info
