### ISSUE TITLE
can't connect > 20 channels

### ISSUE THREAD

**Issue by Cocss** [TwitchLib/TwitchLib#1072]
when connecting to more than 20 twitch channels, a connection error appears, connects 20, skips the rest, just gives an error and that's it. Is this an api limit? or a twitchlib error I can't figure out

**Comment by AbbyTheRat** [comment]
Not sure, but that sounds like the rate limit of the API.

Regular Twitch Accounts can only attempt 20 join (joining channel) per 10 seconds, if you're using a queue it may be hitting the rate limit. Verified Bot can reach 200 per 10 second, so it may be worth getting verified at this point or adding in a rate limit of 10 per 5 seconds.

**Comment by AbbyTheRat** [comment]
I don't know enough to help there, I suspect there's already a function to enqueue channels and that it already rate limit the join.

**Comment by swiftyspiffy** [comment]
I'm not sure about this. I'm able to connect to like 400 on my connection being disconnected (due to queue backup). Something doesn't seem right here.
