### ISSUE TITLE
GetAllFollowersAsync  on Helix

### ISSUE THREAD

**Issue by AndreZila01** [TwitchLib/TwitchLib#1073]
Hey everyone,  I have one question, i try execute command with `apiss.V5.Channels.GetAllFollowersAsync`, but give my a error. I read one document about v5. The staffers tell, v5 is "shutdown". But my question is -.. how i can collect all followers??

I try use this code ... but i think, this code dont return what i need...

`await apiss.Helix.Users.GetUsersFollowsAsync("01/01/1999");`

Thanks

**Comment by swiftyspiffy** [comment]
What is the first argument of `api.Helix.GetUsersFollowsAsync()`? Your editor should tell you, but also you can search the code on github to see what it is. I think your first arg is wrong.

**Comment by Mahsaap** [comment]
> What is the first argument of `api.Helix.GetUsersFollowsAsync()`? Your editor should tell you, but also you can search the code on github to see what it is. I think your first arg is wrong.

This is the confusing one with after and before first params

**Comment by WrithemTwine** [comment]
I wrote an extended version of the TwitchLib "Followers" service to perform the "GetAllFollowers" method: 

https://github.com/WrithemTwine/TwineChatBot/blob/main/StreamerBotLib/BotClients/Twitch/TwitchLib/ExtFollowerService.cs#L29

Some calls are to my own library, e.g. LogWriter (to record exceptions). The "before" and "after" refer to the pagination cursor within the 'followers' listing Twitch maintains so we don't retrieve the same "100" followers every API call.
