### ISSUE TITLE
Pls change Get Users Follows

### ISSUE THREAD

**Issue by Cocss** [TwitchLib/TwitchLib#1075]
![image](https://user-images.githubusercontent.com/28766832/154251059-0b229c23-a4a2-4452-8c55-3bd0aa3c1e0a.png)
a very important from_login value has been lost. Pls add 😅 
The api currently has only from_name, but the name may consist of hieroglyphs, after which it will be impossible to identify the user through other APIs.

**Comment by swiftyspiffy** [comment]
looking

**Comment by swiftyspiffy** [comment]
PR submitted: https://github.com/TwitchLib/TwitchLib.Api/pull/257

**Comment by Cocss** [comment]
Thanks a lot <3
