### ISSUE TITLE
Unable to resolve dependency 'TwitchLib.Api'. Source(s) used: 'nuget.org', 'Microsoft Visual Studio Offline Packages'.

### ISSUE THREAD

**Issue by Gadzzaa** [TwitchLib/TwitchLib#1076]
Whenever i try and install the package i get this error. I actually don t have any idea how to fix it. Tried to manually install the package and it did not work, tried to reset cache, didn't work.			
![image](https://user-images.githubusercontent.com/60661008/154851972-0e84f6f3-1f1b-47b0-ad78-c0968a622000.png)

**Comment by Fruschel** [comment]
Also got this issue.
Can't install the package neither with the NuGet GUI or command prompt - always getting this error with: TwitchLib.Api.Core

**Comment by Syzuna** [comment]
Hey. Please try if the steps in the video fix your issue:

https://cdn.syzuna-programs.de/images/ysHh8GA8Wb.mp4

**Comment by Fruschel** [comment]
@Syzuna I just downloaded the source files and implemented them into my code... A bit squishy but works after a few Stop-n-Gos. :)

I should try your way in the video in a new project - but in the moment I have something to work with! :) 

Thank you for helping!

**Comment by Syzuna** [comment]
Fixed.
See #1080 for more info
