### ISSUE TITLE
TwitchLib.Client.Exceptions.BadStateException: 'Must be connected to at least one channel.'

### ISSUE THREAD

**Issue by BotJames312** [TwitchLib/TwitchLib#1082]
I have one error when i try connect my bot in my channel.

	TwitchClient clientAux = new TwitchClient();

	ConnectionCredentials credsAux = new ConnectionCredentials((comboBox1.SelectedItem as ComboboxItem).Text.ToString(), (comboBox1.SelectedItem as ComboboxItem).Value.ToString());

	clientAux.Initialize(credsAux, ChannelStart);

	clientAux.Connect();

	client.SendMessage(ChannelStart, "testar");

	clientAux.SendMessage(ChannelStart, "testar");

	clientAux.SendMessage(ChannelStart, ((TextBox)sender).Text.ToLower().Replace("-bot ", ""));
	clientAux.Disconnect();

I dont know why i cann't send one mensage in my secondary account. If i try send a mesage in variable client worked, but i send on other account (clientAux) and i dont see them on chat.
[I try to check if token is valid and yes is valid](
https://user-images.githubusercontent.com/93090977/163652264-6aa87a5e-f8de-48a6-b2e1-ff859a5bdf04.png).

![mesage of error](https://user-images.githubusercontent.com/93090977/163651740-1ac51e83-87ad-439b-a50e-b1474f4ae618.png)

Can you help me thanks.

**Comment by Cocss** [comment]
I think your client does not have time to connect to the channel, and you immediately try to send a message. that's why he writes 'Must be connected to at least one channel.'

**Comment by BotJames312** [comment]
Ok ... its work. I needed add "Thread.Sleep(500);" and appears the message. Thanks @Cocss
