### ISSUE TITLE
OnWhisperReceived work one time.

### ISSUE THREAD

**Issue by BotJames312** [TwitchLib/TwitchLib#1083]
Hello everyone, 

I have one problem in my project. I tried create a simple function, when someone redeem a whisper, create a simple picturebox in form. But when redeem a second time, dont redeem (dont return nothing)!

My code at the moment:
> 
	private void ClientBot_OnWhisperReceived(object sender, OnWhisperReceivedArgs e)
	{
		Debug.Print(""+ e.WhisperMessage.Message);
		redeem(e.WhisperMessage.Message.Split(' ').ToArray()[0].ToUpper(), e.WhisperMessage.Username);
	}

> 
	public void redeem(string nameredeem, string username)
	{
		Panel pnlRedeem = new Panel();
		PictureBox pctAceitar = new PictureBox();
		pctAceitar.Location = new System.Drawing.Point(175, 8);
		pctAceitar.Name = "pctAccept";
		pctAceitar.Size = new System.Drawing.Size(37, 36);
		pctAceitar.TabIndex = 3;
		pctAceitar.TabStop = false;
		pctAceitar.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
		pctAceitar.Image = Properties.Resources.correct;
		pnlRedeem.Controls.Add(pctAceitar);
		flwRedeems.Invoke((MethodInvoker)(() => flwRedeems.Controls.Add(pnlRedeem)));
	}
	
Can you help me? Thanks

**Comment by swiftyspiffy** [comment]
Looking into this. Also reported in #1084

**Comment by swiftyspiffy** [comment]
![image](https://user-images.githubusercontent.com/9569194/174153572-87c3e97c-945e-47ad-baa9-e9e80a658859.png)

Appears to be working. Please comment out the line:
```
redeem(e.WhisperMessage.Message.Split(' ').ToArray()[0].ToUpper(), e.WhisperMessage.Username);
```
And let me know if the debug print line prints for multiple whispers.

**Comment by swiftyspiffy** [comment]
Closing this since no follow up.
