### ISSUE TITLE
PubSub OnWhisper is not working.

### ISSUE THREAD

**Issue by SirBitesalot** [TwitchLib/TwitchLib#1084]
OnWhisper Event is never firing.
The Message only appears in OnLog

**Comment by swiftyspiffy** [comment]
Looking into this. Also reported in #1083

**Comment by swiftyspiffy** [comment]
https://github.com/TwitchLib/TwitchLib.PubSub/pull/103

**Comment by swiftyspiffy** [comment]
This has been fixed and is being deployed to prerelease now. Will be published to non-prerelease in the future.
