### ISSUE TITLE
Twitch client reconnect

### ISSUE THREAD

**Issue by Cocss** [TwitchLib/TwitchLib#1085]
Does anyone have a working code sample to reconnect the twitch client? I tried to do through Connect() inside onDisconnected and Reconnect() none of these works, only initialization works, but it sometimes runs the bot three times

**Comment by JulanDeAlb** [comment]
Which Client Protocol do you use ? WebSocket or Tcp ?

**Comment by WrithemTwine** [comment]
I couldn't get reconnect working nor adding a new channel doesn't seem to provide channel connection. I ended up on a disconnect to instantiate a new object and connect again. I'm using the websocket protocol.

![CurrentTwitchLibversions](https://user-images.githubusercontent.com/20450441/167892139-6e9b1f1c-ffc8-4240-ae5d-4a8ed59f67b1.png)

**Comment by Cocss** [comment]
I'm using WebSocket, Nuget 3.2.4

**Comment by Cocss** [comment]
oh, I saw another open issue, and saw a mention of the pre-release 3.2.6 Twitch.Client, it works, lol
