### ISSUE TITLE
Read chat only / Anonymous mode?

### ISSUE THREAD

**Issue by AvabAlexander** [TwitchLib/TwitchLib#1086]
Is it possible to connect to a chat anonymously? For my tasks I don't need to post anything back to chat, just read !commands and do stuff within the program.

**Comment by Syzuna** [comment]
you can connect as justinfanXXXXX replace X with a random number like justinfan12345 or justinfan1337 and pass in an empty token.

sth like the following should work:

```csharp
var creds = new ConnectionCredentials("justinfan12345", string.Empty)
var client = new TwitchClient();
client.Initialize(creds);
client.Connect();
```

**Comment by OakTr1be** [comment]
Thanks you, it connect now!
I also noticed `JoinChannel("name")` does not appear to work?

This works, OnMessageReceived is raised and messages are printed to the console.
```
	var creds = new ConnectionCredentials("justinfan1234567", "");
	var client = new TwitchClient();
	client.Initialize(creds, "name");

	client.OnLog += Client_OnLog;
	client.OnJoinedChannel += Client_OnJoinedChannel;
	client.OnMessageReceived += Client_OnMessageReceived;
	client.OnConnected += Client_OnConnected;

	client.Connect();
```

This does not work. OnMessageReceived is never raised
```
	var creds = new ConnectionCredentials("justinfan1234567", "");
	var client = new TwitchClient();
	client.Initialize(creds);

	client.OnLog += Client_OnLog;
	client.OnJoinedChannel += Client_OnJoinedChannel;
	client.OnMessageReceived += Client_OnMessageReceived;
	client.OnConnected += Client_OnConnected;

	client.Connect();
	client.JoinChannel("name");
```

**Comment by Syzuna** [comment]
Subscribe to the OnConnected event and do the JoinChannel call in the
event  handler of the OnConnected event

OakTr1be ***@***.***> schrieb am So., 15. Mai 2022, 16:21:

**Comment by OakTr1be** [comment]
Ahh, that's the order you do it in. 

Thanks for your help! Have a great evening 😊
