### ISSUE TITLE
EventSub

### ISSUE THREAD

**Issue by Cocss** [TwitchLib/TwitchLib#1089]
Somehow it is possible now to use EventSub in a regular console application without ASP.NET ?

**Comment by Syzuna** [comment]
I mean you could just use HttpListeners if you want to but I wouldnt know why you would torture yourself like that :D
Other than that there currently is no way to use EventSub witthout a webserver handling HTTP POST requests to your callback as Webhook is the only public transport for EventSub right now.
Websockets are in closed beta but who knows they go GA

**Comment by Cocss** [comment]
I'm just slowly switching from a console application to ASP.net , I don't really understand how to organize the work of microservices yet T.T
