### ISSUE TITLE
tmi.twitch.tv NOTICE * :Login authentification failed (please create a TwitchLib GitHub issue :P)

### ISSUE THREAD

**Issue by setolyx** [TwitchLib/TwitchLib#1090]
Not quite sure what I did or how I did it, but in between my tests today I think i somehow got the client either stuck on a hanging connection, or somehow changed something in my back-end on the twitch application dashboard and lost my authentification. I updated my secret key and verified I had the correct application ID before posting here.

I also signed into my chatbot's account just to check if there were any extra things I needed to configure, so I don't know if I just need to wait for a session to fall off or what. Basically posting here just in case y'all have a setup where sometimes connections are flagged until later approved through an issue ticket. 

If there are any files I need to upload or additional outputs that would be helpful, please let me know and I'll be happy to share them. my bot's name is SetolyxBot and i'm very sad that he isn't working :(

**Comment by setolyx** [comment]
Oh, probably would help to include i'm using C# dotnet framework executing in a command prompt via the test build feature (since i can't actually figure out how to build it without ruining things)

**Comment by swiftyspiffy** [comment]
Hi! Is this really the error you got (including the typo): `tmi.twitch.tv NOTICE * :Login authentification failed`

**Comment by setolyx** [comment]
![image](https://user-images.githubusercontent.com/8112005/174005161-68734fdd-a1ec-4866-a404-3e0eed54fa03.png)
my bad about the typo but yes that's the error i got

**Comment by swiftyspiffy** [comment]
And what version of twitchlib.chat are you using?

**Comment by setolyx** [comment]
I'm not 100% sure how to check that right off the bat, these are the packages I'm using at least:
![image](https://user-images.githubusercontent.com/8112005/174005544-0f3804eb-3faa-4c7b-a38c-f951926b6120.png)

**Comment by swiftyspiffy** [comment]
I see the issue: https://github.com/TwitchLib/TwitchLib.Client/blob/dev/TwitchLib.Client/TwitchClient.cs#L1105
There's no return after firing the `OnIncorrectLogin` login.

So for you to fix it, you need to refresh your credentials and make sure you have a correctly scoped oauth token with chat login enabled.

For library fix, we need to add a return to prevent "please create a TwitchLib Github issue" log statement.

**Comment by setolyx** [comment]
Thank you so much for getting back to me so quickly! I posted this and was planning to head off for the night, figuring I wouldn't hear back from someone till morning. Thank you very much for taking the time to help me out with this.

I'll be sure to go through the steps you've given and do some reading into making sure I have the correct oath token and hopefully won't have to bug anybody here to do so! :)

**Comment by setolyx** [comment]
Thank you!!
