### ISSUE TITLE
SendMessage and SendReply trigger "Unaccounted for [UserState]: id" log

### ISSUE THREAD

**Issue by Chris-Is-Awesome** [TwitchLib/TwitchLib#1095]
Doesn't seem to be an error as everything is still functional, but it just repeats this line in the log every time the bot sends a message, gets kinda spammy.

Not a major deal but thought I'd report it anyways and maybe it's a sign that things aren't working as expected for me.

Let me know if I should post code/log.

**Comment by Mahsaap** [comment]
https://github.com/TwitchLib/TwitchLib.Client/pull/195

Already aded in pre-release / dev branch
