### ISSUE TITLE
Twitch capabilities land in "UnaccountedFor" event

### ISSUE THREAD

**Issue by ronan-thibaudau** [TwitchLib/TwitchLib#1097]
I have an account setup to request additional capabilities as documented on : https://dev.twitch.tv/docs/irc/capabilities

When using twitchlib the ack from those lands in the events "UnaccountedFor" of TwitchClient : 

:tmi.twitch.tv CAP * ACK :twitch.tv/membership
:tmi.twitch.tv CAP * ACK :twitch.tv/commands
:tmi.twitch.tv CAP * ACK :twitch.tv/tags

I don't know if this has an actual side effect from users but the OnLog event asked to report them hence this Issue (results from the OnLog event) : 

Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/membership (please create a TwitchLib GitHub issue :P)
Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/commands (please create a TwitchLib GitHub issue :P)
Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/tags (please create a TwitchLib GitHub issue :P)

**Comment by ronan-thibaudau** [comment]
3.3.0 which was latest stable when i started this project, upgrading to 3.4.1 (latest stable on nugget) down and double checking

**Comment by ronan-thibaudau** [comment]
My bad it is fixed in the latest version, sorry for not checking before i didn't realise the lib moved so fast:)

**Comment by Syzuna** [comment]
Full releases are kinda rare. I think that fix was in dev branch since at least start of the year 😅
