### ISSUE TITLE
TimeOut event does not provide Twitch User Id while the ban event does and the irc data provides it

### ISSUE THREAD

**Issue by ronan-thibaudau** [TwitchLib/TwitchLib#1098]
Most events (messages, subscribe etc) provide the twitch user Id but timeout only provides the username which is not ideal as the twitch id is the only unchanging reference to a user / link it to things that happen in other events. 

Sample of the OnLog received showing timeout provides the TwitchId (timing out streamlabs for 1 second), removed channel info : 

Received: @ban-duration=1;room-id=REMOVED;target-user-id=105166207;tmi-sent-ts=1661279376550 :tmi.twitch.tv CLEARCHAT #REMOVED :streamlabs

But the event only exposes the username and not the user id, this is also inconsistend with the Ban event that provides the user Id.

**Comment by Mahsaap** [comment]
The twitch documentation really doesn't show anything about IRC events. Thank you for bringing this up and I'll look at adding it later to dev branch.

**Comment by ronan-thibaudau** [comment]
There sure is a lack of info on the irc events side:(, as i'm trying to log most things, if i find more areas missing unconsistent (like here, timeout vs ban) data should i make a separate issue for each or would it be easier to have a single issue created for all of them?

Is there a scope definition for what twitchlib tries to capture or should i consider any data provided by Irc that i find / could use myself as a candidate for an issue even if it's not something expected like this one?

**Comment by swiftyspiffy** [comment]
This issue resolved with https://github.com/TwitchLib/TwitchLib.Client/pull/198
