### ISSUE TITLE
How to get live stream?

### ISSUE THREAD

**Issue by Smilexs** [TwitchLib/TwitchLib#1100]
Hi! Does TwitchLib have an API or other way to get the live stream and provide it to Unity for playback?

**Comment by LuckyNoS7evin** [comment]
The simple answer is "you can't", there is no supported way of grabbing a stream. 

The only official way is to use the embedded player which is html/js based so will be a pain/almost impossible to get working in a unity environment

**Comment by swiftyspiffy** [comment]
Closing this since question answered.
