### ISSUE TITLE
Documentation Website down

### ISSUE THREAD

**Issue by Wonkerz** [TwitchLib/TwitchLib#1103]
Hey could you update your Documentation Website?
I'm getting a 404 Error at swiftyspiffy.com/TwitchLib

Thank you.

**Comment by Mahsaap** [comment]
I don't think it's been up for a while now. But I am will tag Swifty for an official response. @swiftyspiffy 

But if you need help feel free to ask on discord or here.

**Comment by swiftyspiffy** [comment]
Up to date docs published here: https://twitchlib.github.io/

**Comment by delasource** [comment]
please fix the link in README and in Project description!!

**Comment by Mahsaap** [comment]
https://github.com/TwitchLib/TwitchLib/commit/243a5a2181a735273cc7abc7b9b2a11b9b3cdc18

**Comment by swiftyspiffy** [comment]
I just updated project description link
