### ISSUE TITLE
TwitchAPI.Auth.GetAuthorizationCodeUrl, ForceVerify won't work

### ISSUE THREAD

**Issue by PtitJao** [TwitchLib/TwitchLib#1108]
I'm using the TwitchAPI.Auth.GetAuthorizationCodeUrl function to generate my URL for OAuth.

However, when using this function with **ForceVerify = true**, the forced verification with the generated URL won't get triggered:
`https://id.twitch.tv/oauth2/authorize?client_id=<id>&redirect_uri<redirect>&response_type=code&scope=chat:read+chat:edit&state=&force_verify=True`

I found out that simply making the `&force_verify=true` to lower case in the URL would fix it.

**Comment by Mahsaap** [comment]
that's interesting, I tested it and it sure does capitalize it for some odd reason. It's literally just added with `$"force_verify={forceVerify}";`

not sure why that is happening but will do so looking.

**Comment by Mahsaap** [comment]
And that was fast. Seems its C# changing the bool to string and capitalizing it. Thus we need to add a ToLower. ill do a PR for that. Thanks for reporting it.

**Comment by Mahsaap** [comment]
https://github.com/TwitchLib/TwitchLib.Api/pull/337

**Comment by PtitJao** [comment]
Thanks, I'm closing this ticket
