### ISSUE TITLE
Create clip not working (api.Helix.Clips.CreateClipAsync(broadcasterId))

### ISSUE THREAD

**Issue by fishheadcode** [TwitchLib/TwitchLib#1110]
Hi,

i now tried different ways in different streams, but i cant get api.Helix.Clips.CreateClipAsync(broadcasterId) running. 
Meanwhile i receive a response, but a clip never gets created. 
I am always live when i am testing.

The call is the following

```
static void createClip() {
    Task<CreatedClipResponse> clipResponse = api.Helix.Clips.CreateClipAsync(broadcasterId);
}
```

Can you please take a look at it? Thanks :)

**Comment by swiftyspiffy** [comment]
Closing as issue is with not handling async method. Reopen if the issue exists with the function itself.
