### ISSUE TITLE
Missing Commands

### ISSUE THREAD

**Issue by A5ho9999** [TwitchLib/TwitchLib#1113]
Some commands appear to be missing, the /announce command was working fine last week but seems to no longer be recognized. The /shoutout command would also be nice, but understandable if not accessible.

Using latest release: 3.9.0-preview-f7f2908

```
[Received] @msg-id=unrecognized_cmd :tmi.twitch.tv NOTICE :Unrecognized command: /announce
Unaccounted for: @msg-id=unrecognized_cmd :tmi.twitch.tv NOTICE :Unrecognized command: /announce (please create a TwitchLib GitHub issue :P)
```

**Comment by xDeveluxe** [comment]
Also happens to me.

**Comment by Hampo** [comment]
This isn't a bug with TwitchLib, this is a change by Twitch that just went live. You can read the announcement here: https://discuss.dev.twitch.tv/t/deprecation-of-chat-commands-through-irc/40486

**Comment by A5ho9999** [comment]
Mm I see... thanks.
