### ISSUE TITLE
Whisper doesnt work (Unrecognized Command /w)

### ISSUE THREAD

**Issue by Locxion** [TwitchLib/TwitchLib#1115]
If ill try to send a Whisper to a User i get the Error
`Unaccounted for: @msg-id=unrecognized_cmd :tmi.twitch.tv NOTICE #jtv :Unrecognized command: /w (please create a TwitchLib GitHub issue :P)`

I tried it with my Main Account and my registered Bot Account ... both times same Error

This is my Code
```
		/// <summary>
		/// Sends Message to User
		/// </summary>
		/// <param name="userName"></param>
		/// <param name="message"></param>
		public void SendWhisper(string userName, string message)
		{
			if (!_client.IsConnected)
				return;
			_client.SendWhisper(userName, message);
			_logger.Info($"-> to {userName} - {message}");
		}
```

Nuget Package TwitchLib.Client Version 3.3.1.0

**Comment by Hampo** [comment]
Same as #1113

**Comment by Revyn112** [comment]
> Same as #1113
> 
> Specifically you need to use the [Send Whisper](https://dev.twitch.tv/docs/api/reference/#send-whisper) endpoint now.

Whats the point of using a libary then when its recommend to using endpoints instead?

**Comment by Hampo** [comment]
Did you read the #1113 ? There was a change by Twitch that removed chat commands from the IRC Client, so you can no longer use `TwitchLib.Client.TwitchClient` to send whispers. I would assume a future update will add `SendWhisper` to `TwitchLib.Api.TwitchAPI`, if it isn't already in dev.

**Comment by Syzuna** [comment]
> > Same as #1113
> > Specifically you need to use the [Send Whisper](https://dev.twitch.tv/docs/api/reference/#send-whisper) endpoint now.
> 
> Whats the point of using a libary then when its recommend to using endpoints instead?

That change wasn't made by use but it was a recent change by Twitch.
We didn't get to remove those from the Client yet. As you know this is an Open Source project and we do what we can to keep it up to date in our free time.
This time is limited lately tho. I am sorry for that.

**Comment by Locxion** [comment]
> > > Same as #1113
> > > Specifically you need to use the [Send Whisper](https://dev.twitch.tv/docs/api/reference/#send-whisper) endpoint now.
> > 
> > 
> > Whats the point of using a libary then when its recommend to using endpoints instead?
> 
> That change wasn't made by use but it was a recent change by Twitch. We didn't get to remove those from the Client yet. As you know this is an Open Source project and we do what we can to keep it up to date in our free time. This time is limited lately tho. I am sorry for that.

You dont have to be sorry ... i know how big this Project is ... but i cant understand the reply from @Hampo at all in this case 🤷 

Anyway ... i will open a issue in my repo to rewrite my code if Twitchlib is updated again ... thanks <3

**Comment by Syzuna** [comment]
Well that is what Twitch did. you have to call the API now for most of the stuff you did via IRC before.

**Comment by Revyn112** [comment]
> Same as #1113
> 
> Specifically you need to use the [Send Whisper](https://dev.twitch.tv/docs/api/reference/#send-whisper) endpoint now.

Your answer suggest that there will be no support anymore and it has to be done with the endpoint from now.


> Did you read the https://github.com/TwitchLib/TwitchLib/issues/1113 ? There was a change by Twitch that removed chat 
> commands from the IRC Client, so you can no longer use TwitchLib.Client.TwitchClient to send whispers. I would assume a future 
> update will add SendWhisper to TwitchLib.Api.TwitchAPI, if it isn't already in dev.

> I just checked, it's already [in master](https://github.com/TwitchLib/TwitchLib.Api
> /blob/4f70cfa4ed526447e5cdf0e4ea6997d92dbd7994/TwitchLib.Api.Helix/Whispers.cs#L31), just not the latest NuGet release

That would be initial the better answer and clear things up ;)

**Comment by Hampo** [comment]
@Locxion I just did testing on the latest NuGet [preview version](https://www.nuget.org/packages/TwitchLib.Api/3.9.0-preview-f7f2908) of TwitchLib.Api, and `SendWhisperAsync` works.

Example code:
```cs
TwitchLib.Api.TwitchAPI API = new TwitchLib.Api.TwitchAPI();
API.Settings.AccessToken = "TOKEN HERE"; // Token with `user:manage:whispers` scope
await API.Helix.Whispers.SendWhisperAsync(MyUserID, TargetUserID, true, "Message here");
```

**Comment by Hampo** [comment]
> Your answer suggest that there will be no support anymore and it has to be done with the endpoint from now.

To be fair, there will no longer be support for `SendWhisper` in `TwitchClient`, and you do have to use the endpoint from now on, through `TwitchLib.Api.TwitchAPI`

**Comment by Mahsaap** [comment]
Dev Branch of API until it's been pushed to master.

**Comment by Locxion** [comment]
close to clear up issue
using api to send whispers now
