### ISSUE TITLE
Channel Point Reward IsMaxPerStreamEnabled Doesn't Toggle Cooldown & Limits

### ISSUE THREAD

**Issue by Chris-Is-Awesome** [TwitchLib/TwitchLib#1116]
I noticed that when creating a new `CreateCustomRewardsRequest` object and assigning `MaxPerStream`, it does set the value, but `IsMaxPerStreamEnabled` doesn't control the "Cooldown & Limits" toggle, so this is essentially useless.

Given that both `IsGlobalCooldownEnabled` and `IsMaxPerUserPerStreamEnabled` update that toggle, a workaround is to turn on global cooldown and set seconds to 1 (since greater than 0 is required for request to go through)

Here's an example of this issue:
```csharp
CreateCustomRewardsRequest newRewardRequest = new()
{
	// The issue
	IsGlobalCooldownEnabled = true, // Toggles "Cooldown & Limits"
	IsMaxPerStreamEnabled = true, // Doesn't toggle "Cooldown & Limits"
	IsMaxPerUserPerStreamEnabled = true, // Toggles "Cooldown & Limits"
	
	// Workaround
	IsGlobalCooldownEnabled = true,
	GlobalCooldownSeconds = 1, // Arbitrary 1 second cooldown so setting global cooldown works
	MaxPerStream = 10,
};

**Comment by Hampo** [comment]
I took a quick look, and it appears to be a simple typo here: https://github.com/TwitchLib/TwitchLib.Api/blob/dev/TwitchLib.Api.Helix.Models/ChannelPoints/CreateCustomReward/CreateCustomRewardsRequest.cs#L19

I'm on mobile at the moment, but I can do a PR tomorrow if no one does it before then.

For reference, the JSON property name currently ends `-Enabled` and should end `_enabled`.

**Comment by Mahsaap** [comment]
Typo is fixed on the dev branch (pre release) of the API.

**Comment by Hampo** [comment]
> Typo is fixed on the dev branch (pre release) of the API.

Awesome, saves me having to remember tomorrow

**Comment by Chris-Is-Awesome** [comment]
> Typo is fixed on the dev branch (pre release) of the API.

Nice, was about to fix it as well
