### ISSUE TITLE
Client to API Help - Bad Credentials 

### ISSUE THREAD

**Issue by A5ho9999** [TwitchLib/TwitchLib#1117]
So I've been trying to switch to using the Announcements API but no matter what I try it keeps giving the same error. I've checked repeatedly that the `moderator:manage:announcements` was in the token, and have create multiple now and still get the error. I have tried with both a token generated from the Bot Account as well as token generated from the streamer account, both have resulted in the same error. Has anyone else ran into this or am I missing something?

```
TwitchLib.Api.Core.Exceptions.BadScopeException: Your request was blocked due to bad credentials (Do you have the right scope for your access token?).

at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.HandleWebException(HttpResponseMessage errorResp)
at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.GeneralRequestAsync(String url, String method, String payload, ApiVersion api, String clientId, String accessToken)
at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass22_0.<<TwitchPostAsync>b__0>d.MoveNext()
```

```
await API.Helix.Chat.SendChatAnnouncementAsync(TwitchConfig.StreamerName, TwitchConfig.BotName, Message, AnnouncementColors.Purple, TwitchConfig.BotAccessToken);
```

```
await API.Helix.Chat.SendChatAnnouncementAsync(TwitchConfig.StreamerName, TwitchConfig.StreamerName, Message, AnnouncementColors.Purple, TwitchConfig.StreamerAccessToken);
```

**Comment by Mahsaap** [comment]
I see steamer name and bot name, these need to be the user Id.

**Comment by A5ho9999** [comment]
> I see steamer name and bot name, these need to be the user Id.

I have tried with both the names and ids, same result.

**Comment by Syzuna** [comment]
Could you try the newest preview of the API package (https://www.nuget.org/packages/TwitchLib.Api/3.9.0-preview-d6adaf0) and put a try catch around the API call like this:

```
            try
            {
                await Api.Helix.Chat.SendChatAnnouncementAsync(BroadcasterId, ModeratorId, Message, AnnouncementColors.Purple);
            }
            catch (HttpResponseException e)
            {
                Console.WriteLine(await e.HttpResponse.Content.ReadAsStringAsync());
                throw;
            }
 ```
 
 so we can see what the real response from Twitch is and the actual error the API returns? (This is new in 3.9.0)

**Comment by A5ho9999** [comment]
The response is `{"error":"Unauthorized","status":401,"message":"incorrect user authorization"}`

I believe I know the issue is now, but I can't quite remember how to generate an actual authorization again since I've recently switch the Bot's account to a different one.

**Comment by A5ho9999** [comment]
So finally after a sleep I managed to work out my issue. Thanks for the help
