### ISSUE TITLE
Does client.TimeoutUser() not work anymore?

### ISSUE THREAD

**Issue by nikhunter** [TwitchLib/TwitchLib#1119]
I've had this line for about 1-2 years working perfectly fine but now it doesn't seem to work anymore?
`client.TimeoutUser(channel, user, TimeSpan.FromSeconds(timeValue), "(AUTO) Timeout redemption");`

**Comment by iProdigy** [comment]
You'll have to switch to https://github.com/TwitchLib/TwitchLib.Api/blob/2ea61c70225c0c15d7def7a5808837191e33d778/TwitchLib.Api.Helix/Moderation.cs#L236 due to https://discuss.dev.twitch.tv/t/deprecation-of-chat-commands-through-irc

**Comment by swiftyspiffy** [comment]
Prodigy is correct. Closing this.

**Comment by ghost132** [comment]
How do I find the broadcaster id, moderator id and user id?

**Comment by Mahsaap** [comment]
Getuser API endpoint will return the Id.

In the end if it's one user your looking up broadcaster moderator and user id are all the same given it is the owner of the channel. If say I'm a mod and you look up my Id then that will work as a moderator Id. Broadcaster is the owner. 

Hope this helps
