### ISSUE TITLE
Submit channel score

### ISSUE THREAD

**Issue by abdullahAkduman** [TwitchLib/TwitchLib#1124]
Hello friends. I want to send channel score to any live user. Is there anyone who can help with this?

**Comment by GimliCZ** [comment]
I dont know what are you talking about, try to be more specific. Check https://dev.twitch.tv/docs/api/reference/

**Comment by swiftyspiffy** [comment]
As @GimliCZ mentioned, this issue is far too vague. Feel free to reopen with something more specific.
