### ISSUE TITLE
Garbage character from 'OnMessageReceived' when message sent with numpad enter

### ISSUE THREAD

**Issue by Renari** [TwitchLib/TwitchLib#1127]
I noticed that if a message is sent in chat via using numpad enter a garbage control character is at the end of the string, specifically `0xE0000`. I'm not sure if Twitch is using this in some way or where the character is coming from but this may not be intended.

**Comment by iProdigy** [comment]
That character is used by some third-party chat clients to be able to effectively send duplicate chat messages without Twitch blocking it.

**Comment by Renari** [comment]
That makes sense, and if that's the case I'll just have to parse it out.
