### ISSUE TITLE
Unrecognized command: /clear

### ISSUE THREAD

**Issue by HenryMigo** [TwitchLib/TwitchLib#1128]
I have a simple command that clears the chat upon request. I have since been getting the error in the title when requesting to clear the chat.

![image](https://github.com/TwitchLib/TwitchLib/assets/10053087/0a3771c9-3844-4b16-80d3-e784757ef652)

**Comment by HenryMigo** [comment]
Even when you send the message as ".clear" you get the same error but not when you type ".clear" directly into the Twitch Chat

**Comment by Hampo** [comment]
Twitch removed IRC commands a while back now, you'll have to use the [Delete Chat Message](https://dev.twitch.tv/docs/api/reference/#delete-chat-messages) endpoint with no `message_id`. You can find that in the [TwitchLib.Api](https://github.com/TwitchLib/TwitchLib.Api) under `TwitchLib.Api.Helix.Moderation.DeleteChatMessagesAsync`

**Comment by Hampo** [comment]
Twitch did post a [Migration Guide](https://dev.twitch.tv/docs/irc/chat-commands/#migration-guide) to help know which endpoints you need to use for the relevant commands

**Comment by HenryMigo** [comment]
Ah fair enough, is it worth someone marking the method as 'Deprecated' with a link to the blog post?

**Comment by Hampo** [comment]
In the `dev` branch they've already been removed (or marked Obsolete, I can't remember) - Not sure what's holding up pushing to `master` just yet, but it's there.

My advise would be to use the pre-release branch on NuGet - only available if you install the individual components and not the AIO package

**Comment by HenryMigo** [comment]
Sweet thank you I shall do that! Marking this as closed.
