### ISSUE TITLE
Noob Help: Channel Points Redemptions

### ISSUE THREAD

**Issue by Stage4000** [TwitchLib/TwitchLib#1129]
I am a serious noob when it comes to C# so I apologize in advance. 
I have got twitchlib.client working, I can handle command and all that just fine. But subscribing to channel points redemptions with PubSub is twisting my brain, could someone help me out with an example?

Thank you in advance.

**Comment by Mahsaap** [comment]
With pubsub, listen to the topic you need. Then dont forget to SendTopics after it connects.
If it is something more then this, please feel free to add. :) 
(I personally don't have pubsub setup, so I'm going off top of my head atm)

**Comment by Stage4000** [comment]
I tried making a pubsub module but it just kept connecting. I had a catch for connection then listened to the channels I wanted and sent topics but pubsub just kept giving me "pubsub connected" like ever 30 seconds and wasn't giving me any events back. I tried messing with it for a few hours but didn't seem to make any progress between myself and GPT.

**Comment by Stage4000** [comment]
I scrapped all the code and was hoping for a basic example before trying again. Maybe I will just make it its own project so its less confusing trying to make it work around the bot code I already have set up.

**Comment by Stage4000** [comment]
I threw together a project from the example on the readme but its still not working out.

`using System;
using TwitchLib.PubSub;
using TwitchLib.PubSub.Events;

namespace TwitchLibPubSubExample
{
    class Program
    {
        private TwitchPubSub client;

        static void Main(string[] args)
        {
            new Program().Run();
        }

        private void Run()
        {
            client = new TwitchPubSub();

            client.OnPubSubServiceConnected += onPubSubServiceConnected;
            client.OnListenResponse += onListenResponse;
            client.OnChannelPointsRewardRedeemed += onRewardRedeemed;

            client.ListenToChannelPoints("45897889"); //this says it wants an ID but Ive tried with both a name and ID.

            client.Connect();

            Console.ReadLine(); // Quick fix to keep program from closing right away. ReadKey could also be used.
        }


        private void onPubSubServiceConnected(object sender, EventArgs e)
        {
            // SendTopics accepts an oauth optionally, which is necessary for some topics
            client.SendTopics(); //tried giving it an o-auth token and nothing changed?
            Console.WriteLine("topics sent?");
        }

        private void onListenResponse(object sender, OnListenResponseArgs e)
        {
            if (!e.Successful)
                throw new Exception($"Failed to listen! Response: {e.Response}");
        }

        private void onRewardRedeemed(object sender, OnChannelPointsRewardRedeemedArgs e)
        {
            Console.WriteLine(e.RewardRedeemed.ToString());
            Console.WriteLine(e.RewardRedeemed.Redemption.User.DisplayName);
        }
    }
}`

**Comment by Mahsaap** [comment]
Do you have the required scopes on that token ? https://dev.twitch.tv/docs/pubsub/#topics

**Comment by Mahsaap** [comment]
Pubsub only responds to the custom redemptions as well. Not sure if it needs to be created by the same account token or not. I know API does.

**Comment by Stage4000** [comment]
> Do you have the required scopes on that token ? https://dev.twitch.tv/docs/pubsub/#topics

It definitely did not. TY <3

**Comment by Stage4000** [comment]
OK I am a little confused here: I just used another great tool by @swiftyspiffy, twitchtokengenerator, to get a token but what do I send with SendTopics? Do I send like the client secret of my app? the token of the person who's channel it is I want to listen to? or do I send the same oauth token that I use for the bot?

**Comment by Stage4000** [comment]
all sorted, thank you again for your patience. <3
