### ISSUE TITLE
Cannot create/modify/request Custom Rewards

### ISSUE THREAD

**Issue by Aida-Enna** [TwitchLib/TwitchLib#1135]
I really hate the way twitch tokens work.

I have this code
```var Response = await api.Helix.ChannelPoints.GetCustomRewardAsync("123456789");```

I created my bot's access scope token via [twitch token generator](https://twitchtokengenerator.com), selected all the scopes, and verified all the scopes show up on the user auth page. However, every time I try to run the above code, I get a
 ```TwitchLib.Api.Core.Exceptions.BadScopeException: 'Your request was blocked due to bad credentials (Do you have the right scope for your access token?).'```

I've tried regenerating the tokens 3 times, and my bot can still ban and do many other things on the channel that require access tokens, just not mess with custom rewards. Is there something I'm missing?

**Comment by Mahsaap** [comment]
Did you insert your own client ID and secret into the generator? Only use the generator for testing though. You should setup up proper authentication flow.

Also the reward has to be created by the same account to access. So create the reward with the bot.

**Comment by Aida-Enna** [comment]
Yes, I used my own Client ID and Client Secret from the Twitch Developer dashboard. And yeah, I'll do that after I get this working.

I can't get rewards, create (I tried this first), or delete them.

**Comment by Syzuna** [comment]
if you use 3.9.0 or above try warpping the API call like below to get the usually more detailed error response that Helix returns

```cs
            try
            {
               // API call
            }
            catch (HttpResponseException e)
            {
                Console.WriteLine(await e.HttpResponse.Content.ReadAsStringAsync()); // or what ever you use for logging
            }
```

**Comment by Aida-Enna** [comment]
```{"error":"Unauthorized","status":401,"message":"The ID in broadcaster_id must match the user ID found in the request's OAuth token."}```

This sounds like I need to be the broadcaster in order to modify channel points. My understanding is that Editors/Mods can't modify channel points (for reasons no one understands), but that you can do it via the API with mod/editor. Is that incorrect?

**Comment by Syzuna** [comment]
you need a token from the broadcaster with the appropriate scopes yes. mods/editor won't work here.
the channel points endpoints predate the moderator scoping functionality in Helix and they were never revisited or well not yet maybe at some point who knows

**Comment by Aida-Enna** [comment]
Will an access token from the broadcaster work or do I need to do use actual OAuthToken like they say? My issue is that if I use the broadcaster's OAuthToken, won't my bot then sign in and do everything as the broadcaster instead of my bot user?

**Comment by Syzuna** [comment]
Basically rule of thumb if you see sth like `The ID of the broadcaster to add the custom reward to. This ID must match the user ID found in the OAuth token.` in the docs it needs a broadcaster token

**Comment by Aida-Enna** [comment]
> Basically rule of thumb if you see sth like `broadcasterId: This ID must match the user ID found in the OAuth token.` in the docs it needs a broadcaster token

Yeah, I completely skipped over that in the docs. Looks like the user who can't read today is me! Thank you for the help, I'll go ahead and close this.

**Comment by Syzuna** [comment]
You can use different tokens for different things yes.
also TwitchClient is completely isolated from the TwitchApi object anyway

**Comment by Aida-Enna** [comment]
> You can use different tokens for different things yes. also TwitchClient is completely isolated from the TwitchApi object anyway

At the risk of continuing my stupidness, I would use the ClientID and AccessToken generated from the broadcaster to do this via the TwitchApi object, right? I ask because the TwitchApi object doesn't seem to use OAuthTokens so I'm not sure how this would work.

**Comment by Syzuna** [comment]
The TwitchAPI object uses OAuth Tokens. they are just called AccessTokens/accessTokens acros the board

**Comment by Syzuna** [comment]
> > You can use different tokens for different things yes. also TwitchClient is completely isolated from the TwitchApi object anyway
> 
> At the risk of continuing my stupidness, I would use the ClientID and AccessToken generated from the broadcaster to do this via the TwitchApi object, right? I ask because the TwitchApi object doesn't seem to use OAuthTokens so I'm not sure how this would work.

You use your own client id, you just have the broadcaster auth with that client id.

**Comment by Syzuna** [comment]
This forum post of a friend might help you understand the whole authentication thing better:
https://discuss.dev.twitch.com/t/authenticating-with-the-twitch-api/29237

**Comment by Aida-Enna** [comment]
> This forum post of a friend might help you understand the whole authentication thing better: https://discuss.dev.twitch.com/t/authenticating-with-the-twitch-api/29237

This helps a lot, thank you very much! I'll experiment and exhaust all resources I can (by reading them!) before posting again if I need to.
