### ISSUE TITLE
GetChanneliCalendarAsync doesnt return any value.

### ISSUE THREAD

**Issue by PartemImperium** [TwitchLib/TwitchLib#1136]
The GetChanneliCalendarAsync method in the Schedule API does not return any value. It has Task as its return type instead of Task<string> and as such you cant (easily) get the result of the call.

**Comment by Mahsaap** [comment]
#390 

Thanks for the heads up. I made it a returnable string. I haven't worked with icalendar, so if there is a better way someone can add it later.

**Comment by swiftyspiffy** [comment]
Closing this as it seems fixed.
