### ISSUE TITLE
OAuth Token workflow not working with TwitchClient

### ISSUE THREAD

**Issue by tdorey00** [TwitchLib/TwitchLib#1138]
Hello,

I'm working with the TwitchClient and attempting to use the TwitchLib.Api.Auth functionality to semi-automatically request the Token.

 I'm using ```GetAuthorizationCodeUrl``` and then reading the code out of that using HttpListener similar to: https://github.com/swiftyspiffy/Twitch-Auth-Example then passing that code into ```GetAccessTokenFromCodeAsync``` to receive my token which I then pass into ```ConnectionCredentials``` and then finally the ```Initialize``` function of the TwitchClient. I'm able to see via step debugging that through each part of the process I get the auth code successfully and then the token successfully however, when the client is initialized it never seems to fire off the OnConnected event I have registered and seemingly never connects to twitch.

I have some links to the relevant code here if you would like to take a look: 

Here is where I initialize the TwitchClient - 
https://github.com/tdorey00/AI-VTube.NET/blob/3fdfe2f5c47e36684c2791b42e536c971d82a3b5/AI-Vtube-dotNET/AI-Vtube-dotNET/Livestream/Twitch/TwitchManager.cs#L53

Here is where I get the Auth Code and then the token using TwitchLib.Api.Auth -
https://github.com/tdorey00/AI-VTube.NET/blob/3fdfe2f5c47e36684c2791b42e536c971d82a3b5/AI-Vtube-dotNET/AI-Vtube-dotNET/Livestream/Twitch/TwitchAuth.cs#L3

The code is heavily WIP so it is definitely not ideal but I'm just trying to get something working.

Any help/insight is greatly appreciated.

**Comment by swiftyspiffy** [comment]
Can you try listening to the OnLog event and see if anything shows up? If nothing, I'd try creating a new project with only the client and a known working oauth token and see if you can get it to work in that project then port it to your main project.

**Comment by tdorey00** [comment]
@swiftyspiffy Hey sorry for the long wait on the reply hectic week at work. I did hook it up to OnLog and here's a dump of what we got

```
    2024-07-12 22:52:01.6902| INFO
    Location = AI_Vtube_dotNET.Livestream.Impl.TwitchManager.Client_OnLog
    Message = Connecting to: wss://irc-ws.chat.twitch.tv:443

    2024-07-12 22:52:02.2324| INFO
    Location = AI_Vtube_dotNET.Livestream.Impl.TwitchManager.Client_OnLog
    Message = Should be connected!

    2024-07-12 22:52:02.3998| INFO
    Location = AI_Vtube_dotNET.Livestream.Impl.TwitchManager.Client_OnLog
    Message = Joining channel: [Twitch Channel Name Censored by me]

    2024-07-12 22:52:02.6002| INFO
    Location = AI_Vtube_dotNET.Livestream.Impl.TwitchManager.Client_OnLog
    Message = Received: :tmi.twitch.tv NOTICE * :Login unsuccessful

    2024-07-12 22:52:02.6056| INFO
    Location = AI_Vtube_dotNET.Livestream.Impl.TwitchManager.Client_OnLog
    Message = Unaccounted for: :tmi.twitch.tv NOTICE * :Login unsuccessful (please create a TwitchLib GitHub issue :P)

    2024-07-12 22:52:02.6056| INFO
    Location = AI_Vtube_dotNET.Livestream.Impl.TwitchManager.Client_OnLog
    Message = Unaccounted for: :tmi.twitch.tv NOTICE * :Login unsuccessful (please create a TwitchLib GitHub issue :P)
    ```
    
    Didn't really help me understand what was going on, but hopefully this helps somehow.  Let me know if there's anything else I should try outside of stripping the code down in a separate project or if you need any more information on it. Would also be willing to link to the repo if you want to take a look at the code itself.

**Comment by swiftyspiffy** [comment]
`NOTICE * :Login unsuccessful`

This is Twitch telling you that the auth token you're using is not permitted to read/write chat. Make sure the token you're using has the scopes `chat:read` / `chat:edit`

**Comment by tdorey00** [comment]
Thank you so much for the help, I figured it was something we overlooked like that. Everything worked as soon as we put that in. I'll close this as completed, thanks again!
