### ISSUE TITLE
Support new Twitch API

### ISSUE THREAD

**Issue by Felk** [TwitchLib/TwitchLib#259]
Twitch has announced a new API. It's supposedly a fresh start including simplified/unified data models, revamped pubsub, more reliability, and webhooks. I couldn't find an official name, so let's call it "v6" for now.

The announcement: https://dev.twitch.tv/api
Their roadmap: https://trello.com/b/xdoVhmKj/twitch-developer-platform-roadmap

Once more information about the new API gets released, this issue shall get updated.

**Comment by Syzuna** [comment]
Webhooks will be a problem for local development and local bots.. I was hyped but then I read about the webhook stuff

**Comment by swiftyspiffy** [comment]
Having used various web hooks from different services, I don't think webhooks are designed for bot usage, unless they have a web server attached or something

**Comment by Felk** [comment]
Programmatic administration of webhooks is very much desirable. Keep in mind that webhooks will most likely just be an optional addition to improve what was previously done with polling

**Comment by swiftyspiffy** [comment]
Are you saying there might be an API that is used to provision new webhooks or what have you? I didn't think about that.

**Comment by Felk** [comment]
That's what I assumed, yes. Similar to github.

**Comment by Syzuna** [comment]
Do you see a posibility to get the lib more "DI" friendly with the rework you/we have to do anyway? would be great if possible

**Comment by Felk** [comment]
DI?

**Comment by LuckyNoS7evin** [comment]
@Felk Dependency Injection

**Comment by Syzuna** [comment]
The released docs arent that big of a reason to be hyped lol

It looks more like a v5.5 to me with a changed name :D

**Comment by swiftyspiffy** [comment]
GetUsers and GetUsersFollows are supported (though untested). Will be adding the rest tonight or tomorrow, hopefully.

**Comment by swiftyspiffy** [comment]
New package going out with very "beta" support for the new API. Lightly tested. Will get it tested more later.

**Comment by Scrxtchy** [comment]
Is `helix.GetStreams` broke?
Always returning `null`

**Comment by swiftyspiffy** [comment]
Will look into helix.GetStreams

**Comment by swiftyspiffy** [comment]
@Scrxtchy should be fixed with 345478767ae

**Comment by Scrxtchy** [comment]
Thanks, Praise Helix

**Comment by swiftyspiffy** [comment]
This has been completed up to the supported Helix api.
