### ISSUE TITLE
TwitchPubSub Read me outdated and issues with it

### ISSUE THREAD

**Issue by As2piK** [TwitchLib/TwitchLib#271]
Hello,

First of all I don't have many expertise on using external libraries, nor using english.

It seems that TwitchPubSub informations in readme is outdated, ListenToWhispers doesn't use oauth anymore but channel ID, and other little changes. 

About that last change, I don't get if channelTwitchId is simply the channel name, or another private information found somewhere. In the Class Reference, it mentions that this Id "can be fetched from TwitchApi" but no other informations about it in TwitchPubSub, nor in TwitchApi References.

Hope you understand my issue.

Thanks !

**Comment by Syzuna** [comment]
Channel Id isnt simply the channel name. the channel id is a unique sequence of numbers to idetifiy a user/channel. you can query it with the Twitch Api. (UserId is the same as the ChannelId for that particular user)

**Comment by swiftyspiffy** [comment]
You're right, the README docs are significantly out of date. I'll see if I can get them updated. Will leave this issue open until done so.

**Comment by swiftyspiffy** [comment]
Sorry about the really long delay. I just added an example to the README. You can find it here: 
https://github.com/TwitchLib/TwitchLib.PubSub/blob/master/README.md

Feel free to reopen as necessary.
