### ISSUE TITLE
EmoteSet.Emotes + Emoji = ??

### ISSUE THREAD

**Issue by BuHerPeT** [TwitchLib/TwitchLib#311]
So, send this to a chat `SMOrc 😡😡 Kappa` (sometimes somebody send emoji to a chat) and handle
```
foreach (var item in e.ChatMessage.EmoteSet.Emotes)
{
    Console.WriteLine(item.Name);
}
```

There must be this
```
SMOrc
Kappa
```

...but get this
```
SMOrc
? Kap
```

Am I doing something wrong? 🤔

**Comment by swiftyspiffy** [comment]
Nope, you're doing things correctly, but I'm not surprised it has issues with emojis. I don't really have a good solution for them off the top of my head.

**Comment by Scrxtchy** [comment]
Is this in your debugger or your `Console`?

Using .netcore here
![image](https://user-images.githubusercontent.com/12771982/33072101-37b7f06e-cf12-11e7-974d-717e9735e2ad.png)

Windows terminal is not a very good modern terminal, but it does the job it's made to do well

**Comment by BuHerPeT** [comment]
@Scrxtchy, ummm... Problem is not in `Message`

![2017-11-21_18-10-20-774_devenv](https://user-images.githubusercontent.com/4807012/33074241-483fb58c-cee7-11e7-9771-cceddee81019.png)

Msg is: `🤔🤔 Kappa`

**Comment by Scrxtchy** [comment]
I know what's going on here, I was completely wrong in my assumption that it was a display error

The way twitch handle's emotes, they give the start and the end reference in the string.
However they might not be account that emojis are actually two characters in some cases (a lot of the time actually)
This is usually why you see double marks `??` when they are displayed

**Comment by Scrxtchy** [comment]
This is also why you cannot use an emoji as a `char`, only within a string, because they have to allocate what I assume is around 4bytes (talked over this with someone else but we couldn't get anything firm), however emoji are more than that.

There's a good blog post I found on hacker news regarding this
http://blog.jonnew.com/posts/poo-dot-length-equals-two

**Comment by swiftyspiffy** [comment]
I'm going to go ahead and close this. If someone finds a good solution for this (or Twitch makes it easier), then we can re-investigate.
