### ISSUE TITLE
Trying to follow users.

### ISSUE THREAD

**Issue by TehKingPenguin** [TwitchLib/TwitchLib#358]
I am trying to follow users however I cant't seem to be able to or find any resources to help me, any help would be great thanks.

**Comment by Syzuna** [comment]
Hey,

V3 and V5 have endpoints for that. Sadly Helix doesnt support it yet.

For following users via API you can have a look at 

`FollowChannelAsync`

[https://github.com/swiftyspiffy/TwitchLib/blob/master/TwitchLib/Api/Sections/Users.cs#L184](https://github.com/swiftyspiffy/TwitchLib/blob/master/TwitchLib/Api/Sections/Users.cs#L184)

scroll down to the V5 section. there you can find it.

on the API object you would call it like `api.Users.v5.FollowChannelAsync(some args here)`

I hope that helps you a bit

**Comment by swiftyspiffy** [comment]
Also, you need to be using a Twitch Oauth token with the `user_follows_edit` scope to successfully do this.

**Comment by TehKingPenguin** [comment]
@Syzuna I'll give that a shot, thanks

**Comment by TehKingPenguin** [comment]
@swiftyspiffy How would I go about doing that?

**Comment by swiftyspiffy** [comment]
You can use a service I made: https://twitchtokengenerator.com . If it's a one off thing, that'll work. If you're making a service for other people to use, for production you're going to want to make a similar service.

**Comment by TehKingPenguin** [comment]
Okay, thanks!

**Comment by swiftyspiffy** [comment]
Going to go ahead and close this. Feel free to reopen as needed.

**Comment by LochiQF** [comment]
Hello there, it may be that I'm confused and messing up something really easy but, the method `FollowChannelAsync` doesn't seem to work.
 I currently have an access token with the scope `user_follows_edit` and defined the parameters `userId`, `channelId` with respectively the bot id and the broadcaster id.
Hope you will be able to provide light on the problem.
