### ISSUE TITLE
General Cleanup Part 1

### ISSUE THREAD

**Issue by Syzuna** [TwitchLib/TwitchLib#361]
I opened PR #360 with quite a lot of changes..

Sorry for that :D

This changes are just cleanups no breaking changes should be included!

More parts will follow once Part 1 is reviewed^^

Regards

**Comment by swiftyspiffy** [comment]
Will review this weekend since it's going to take several minutes :D

Thanks

**Comment by swiftyspiffy** [comment]
This has been merged,thanks again!
