### ISSUE TITLE
ArgumentOfOutRangeException randomly

### ISSUE THREAD

**Issue by DerpyDoom** [TwitchLib/TwitchLib#373]
Hello!

I randomly get this error, and then my bot crashes. Even tho I am not using any events like OnMessageReceived.

This is a screenshot of the exception:
http://prntscr.com/inaxek

**Comment by Syzuna** [comment]
Hi,

is there any information you can provide to narrow the issue down?
what version of twitch lib are you using? nuget version? if not whats the latest github commit included in you local TwitchLib copy or when in your process this error occures like at the start up, if someone writes something in chat or whatever?

Regards

**Comment by DerpyDoom** [comment]
Sorry! Totally forgot the additional information :P

NuGET Version: 1.6.1
Framework: .Net 4.6.1

It seems like it is triggered by something in the chat, since this is only happening randomly, it is connected to multiple streamers. Maybe an unsupported character or something?

**Comment by Syzuna** [comment]
ok based on the stacktrace there is a SubString method call failing. there are actually some of them in the ChatMessage class. so.. its either /me parsing or any emote that represents an edge case causing this.

any way you can monitor the IRC strings coming in?

**Comment by swiftyspiffy** [comment]
Hello!

Ya, the issue does look to be in the parsing department.
Additionally, it looks like the exception was thrown whilst performing a substring operation in ChatMessage model constructor.

The available locations for this are:
/me parsing:
https://github.com/TwitchLib/TwitchLib.Client/blob/1f9a21c143ec67433b982f3b79917ea742037882/TwitchLib.Client/Models/Client/ChatMessage.cs#L190

and EmoteSet parsing:
https://github.com/TwitchLib/TwitchLib.Client/blob/1f9a21c143ec67433b982f3b79917ea742037882/TwitchLib.Client/Models/Client/ChatMessage.cs#L209

The safety checks for /me parsing seem pretty good, so I think the problem probably exists in the EmoteSet parsing.

@DerpyDoom Is it possible that you could log data received in the `client.OnSendReceiveData` event to disk and then report back with the last message prior to a crash? This would help significantly I think.

**Comment by DerpyDoom** [comment]
I am now logging the output of client.OnSendReceiveData, it has not been crashed since.

I'll respond with updates as soon as it crashes again.

**Comment by DerpyDoom** [comment]
18 Hours later and it crashed again. It's the same exception. The cyan text is the output of `OnSendReceiveData` exactly where it crashed.

Screenshot: http://prntscr.com/io4b4v

**Comment by Mahsaap** [comment]
May I also suggest maybe joining the Discord Server where we can discuss this directly? https://discord.me/twitch-api

**Comment by swiftyspiffy** [comment]
@DerpyDoom any update on this?
