### ISSUE TITLE
Suggestion/Idea - Add a way to pull version of the library from code

### ISSUE THREAD

**Issue by Mahsaap** [TwitchLib/TwitchLib#378]
So say I want to add a label to my bot info command, that will pull this information instead of having to be updated manually every time I update.

I hate to keep bringing up examples from discord.net but this what I mean
https://cdn.discordapp.com/attachments/388427938086780949/425108379741061121/unknown.png

**Comment by swiftyspiffy** [comment]
This can be implemented. Probably a good idea to put this in each component of TwitchLib.

**Comment by LuckyNoS7evin** [comment]
I was thinking just a simple TwitchLib.Version.Current and use reflection to get the current version. Then at least it's one less file to update

**Comment by Mahsaap** [comment]
Something in the lines of 

public static string Version { get; } =

            typeof(twitchlib).GetTypeInfo().Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion ??

            typeof(twitchlib).GetTypeInfo().Assembly.GetName().Version.ToString(3) ?? 

            "Unknown";

This was copied ;)

**Comment by swiftyspiffy** [comment]
@Mahsaap @LuckyNoS7evin check that PR to see if you agree.

**Comment by Mahsaap** [comment]
Seems fine to me.

**Comment by Mahsaap** [comment]
This has been added. Closing.
