### ISSUE TITLE
MessageThrottler not working? 

### ISSUE THREAD

**Issue by MisaelUrq** [TwitchLib/TwitchLib#380]
Hi! c:

This probably isn't a issue, just a lack of knowledge on my part.

So I'm having a little trouble making the TwitchClient ChatThrottler and WhisperThrottler work on my bot, the problem is that my bot stops working when I insert this lines of code to make a Throttler: 

```csharp
client.ChatThrottler = new MessageThrottler(client, 20, TimeSpan.FromSeconds(30));
client.WhisperThrottler = new MessageThrottler(client, 20, TimeSpan.FromSeconds(30));
```

when I comment them or delete them, the Bot begins to respond normally to the chat, but when I insert them on the code the bot just stops responding sending messages, on the Log information the message is received, so I don't really know how I'm supposed to initialize the Throttlers, I'm guessing that I miss a step or something, 

I call this after Initializing the client with the credentials and before Connecting, don't know if that's important.

So if you can help me that would be great :D 
Thanks and have a nice day n.n

**Comment by Syzuna** [comment]
Hey there.

Yes this actually is missing in the docs but you need to call:

`
await client.ChatThrottler.StartQueue();
await client.WhisperThrottler.StartQueue();
`
