### ISSUE TITLE
ChannelState SlowMode returns always false

### ISSUE THREAD

**Issue by Itsmadhatter** [TwitchLib/TwitchLib#385]
Twitch´s "ROOMSTATE" does not returns a 0/1 value instead it is the slow mode time.

`slow=3 :tmi.twitch.tv ROOMSTATE`

`private static bool? ConvertToBool(string data)
        {
            if (string.IsNullOrEmpty(data))
                return null;
            return data == "1";
        }`

Thats why this Method always returns false

**Comment by swiftyspiffy** [comment]
Looks like Twitch changed their stuff again. Any idea how recent this change is?

**Comment by Itsmadhatter** [comment]
I have no idea. I´m random stumbled over it :D

**Comment by Syzuna** [comment]
Hey!
This should be fixed with the newest client commits made today. would appreciate if you check it out and tell us if it works properly now

**Comment by Itsmadhatter** [comment]
idk but now the OnChannelStateChanged Event doesn´t get triggered

**Comment by Syzuna** [comment]
looking into this.. bcs if sth broke thats my fault bcs I did the parsing rewrite NotLikeThis

**Comment by swiftyspiffy** [comment]
@Itsmadhatter Should be fixed with https://github.com/TwitchLib/TwitchLib.Client/pull/24

**Comment by Syzuna** [comment]
sorry my bad. forgot to change a return there after moving some code

**Comment by Itsmadhatter** [comment]
Ok everything works now. Thanks guys :D

**Comment by swiftyspiffy** [comment]
Awesome, will go ahead and close this. Feel free to reopen as necessary.
