### ISSUE TITLE
Please consider adding a CancellationToken as parameter for async methods

### ISSUE THREAD

**Issue by niklr** [TwitchLib/TwitchLib#389]
Is it currently possible to cancel a pending async method? What happens if Twitch is down: will the sync/async methods run forever or cancel/timeout after a specific time?

Please consider adding a CancellationToken as parameter for async methods. Additionally, consider the possibility to specify a number of milliseconds to wait before requests time out.

**Comment by LuckyNoS7evin** [comment]
@niklr Thanks for this, we are still working on the system and after some big changes we have made recently we are looking to implement things like this.

At the moment you are correct in asking but the async task will "timeout" if twitch is down, you'll almost instantly get an exception

**Comment by Syzuna** [comment]
@niklr Thanks for your suggestion again.

Yes CancellationToken Support is sth we should/want to implement in the near future for sure.

For your other concern: The calls to the TwitchApi are based on Http calls so if a server is down that http call will come back with a http error Code and will be handled accordingly that in the end leads to an excepion being raised.

Regards

Syzuna

**Comment by swiftyspiffy** [comment]
This issue was moved to TwitchLib/TwitchLib.Api#36
