### ISSUE TITLE
Client.OnMessageReceivedArgs not holding any emote data + other problem

### ISSUE THREAD

**Issue by Kesiek** [TwitchLib/TwitchLib#392]
Hello. As the title says, in 2.1 API version the Client.OnMessageReceivedArgs.EmotesSet is not holding any data, no matter what and how many emotes there is in message, it always returns 0.

And the second problem is that I'm always getting error when I'm trying to update channel title or game with TwitchAPI.Channels.v5.UpdateChannelAsync() method
Crash message:
`   Something went wrong during the request! Please try again later `

Here is link to stack trace to not overspam this post: [https://pastebin.com/fh5gBeCw](url)
And the code for method is:
       
        public async Task<string> ChangeStreamTitleAsync(string message)
        {
            try
            {
                var a = await twitchAPI.Streams.v5.GetStreamByUserAsync(userId);
                if (a.Stream == null)
                    return "offline";

                await twitchAPI.Channels.v5.UpdateChannelAsync(userId, message);
                return "updated";
            }
            catch (Exception ex)
            {
                DebugConsole.DisplayInDebugConsole(ex.StackTrace, error: true);
                DebugConsole.DisplayInDebugConsole(ex.Message, error: true);
                return "error";
            }
        }

**Comment by Syzuna** [comment]
do you have the Api logging enabled to see the actual status code you got back? bcs if you got this exception message your status code didnt hit anything in the switch statemend we have.. so apparently no 400,401,404,422,500,502,503 or 504

**Comment by Syzuna** [comment]
maybe a 503 from the api? bcs I just saw that we dont check for this

**Comment by Kesiek** [comment]
No, I don't have the logging enabled. I will try to enable it and I will report back if I will get any result

**Comment by Mahsaap** [comment]
UpdateChannelAsync require channelid != username so your "userid" is not going to work for both getby username and updatechannel calls.
example:
username == mahsaap
userid == 12345A == channelid

**Comment by Mahsaap** [comment]
however you can use the object you retreived with getbyusername
a.stream.channel

**Comment by Mahsaap** [comment]
removed comments for some reason i saw get by username

**Comment by Kesiek** [comment]
@Mahsaap This is how I'm getting the channelId (for me its called userId)     
So it should work if I'm understanding this correctly

        public async Task GetUserId()
        {
            var uL = await twitchAPI.Users.v5.GetUserByNameAsync(Program.ChannelName);
            var userList = uL.Matches;

            if (userList == null || userList.Length == 0)
                userId = string.Empty;
            else
                userId = userList[0].Id.Trim();
        }

**Comment by Mahsaap** [comment]
your fine, i just misread the call. i tend to do it alot sadly

**Comment by Kesiek** [comment]
Alright, it took me way too long to figure out the loggin but here I have the result, 
info: TwitchLib.Api.TwitchAPI[0]
      Timestamp: 04/16/2018 18:51:21 Type: Request Method: PUT Resource: https://api.twitch.tv/kraken/channels/56159327 Content: { "channel": {"status": "Test title"} }
fail: TwitchLib.Api.TwitchAPI[0]
      Timestamp: 04/16/2018 18:51:22 Type: Response Resource: https://api.twitch.tv/kraken/channels/56159327 Statuscode: 403 Elapsed: 635 ms Content:       D?K

**Comment by Kesiek** [comment]
And yes, I have the bot token for channel_editor

**Comment by Syzuna** [comment]
Ok your bot has the channel_editor scope. I dont know if this is actually required but is the bot also registered as Editor of your stream in your Dashboard?

**Comment by Syzuna** [comment]
The emote thing is a little bit more intresting.. the emote parsing Code is most likely the oldest untouched Code in this libary. 
It was only a matter of time until other changes break it.
We still dont have found a good way to rewrite it yet but will look into it again

**Comment by Kesiek** [comment]
Oh well.. I will just have to wait.
Thanks for help and good luck fixing stuff!

**Comment by swiftyspiffy** [comment]
This issue was moved to TwitchLib/TwitchLib.Client#42
