### ISSUE TITLE
Good way to handle disconnect?

### ISSUE THREAD

**Issue by jonas-weinhardt** [TwitchLib/TwitchLib#393]
It there a good way to handle the client disconnect. I want to achieve, that the client tries to reconnect a couple times on a disconnect and i tried something like this:

```
private static void ClientMain_OnDisconnected(object sender, OnDisconnectedArgs e)
{
       while (!clientMain.IsConnected)
       {
          Console.WriteLine("Reconnecting...");
          clientMain.Connect();
          Thread.Sleep(1000);
        }
}
```

But i always end up with this exception:

> System.Exception: "The socket is connecting, cannot connect again!"

This happens on the TwitchClient.Connect() Method.

Maybe you know a better way to do this?

Thank you in advance.

**Comment by LuckyNoS7evin** [comment]
@jonas-weinhardt try Reconnect() rather than Connect()

**Comment by jonas-weinhardt** [comment]
Ok I will it.
Thank you for the fast reply.
