### ISSUE TITLE
Not Compatible with Visual Basic

### ISSUE THREAD

**Issue by mbfan** [TwitchLib/TwitchLib#394]
Hello,
please consider rewriting the Code to remove all duplication of Members. Visual Basic ignores upper and lower case, and i can't use any method cause there is (for example) a "v5" and a "V5", which are the same to VB.
With kind regards,
Nico

**Comment by LuckyNoS7evin** [comment]
@mbfan thanks, we do know about this, I believe there was a discussion early to mid 2017 with regards to this and it was a decision to just support c# only. (Forgive me if I'm wrong it was just as I started using TwitchLib and wasn't a large contributor like now)

As we are always working on the library and with the removal of both v3 and v5 at the end of 2018 this may be a time we become compatible with VB again

**Comment by LuckyNoS7evin** [comment]
Ah, missed a bit, thanks

**Comment by mbfan** [comment]
It would help too moving the Classes into another Namespace, if possible.

**Comment by Syzuna** [comment]
As most of us here are only on the C# side of things, how would moving classes to different namespaces help?

**Comment by mbfan** [comment]
The Problem is the Duplication of "v5"/"V5" for Visual Basic, cause it doesnt work Casesensitive. But if the Classes would be in a different Namespace, say "TwitchLib.API.Sections.Classes", there wouldn't be such a duplication inside the same Class.

**Comment by Mahsaap** [comment]
As a note, a comment was added to the readme that states not supporting API in VB currently.

**Comment by swiftyspiffy** [comment]
This issue was moved to TwitchLib/TwitchLib.Api#37
