### ISSUE TITLE
Throttler Throttling all traffic

### ISSUE THREAD

**Issue by Azeranth** [TwitchLib/TwitchLib#397]
I am attempting to use the ChatThrottler but when I do my bot will not send any messages. None.
```csharp
client.ChatThrottler = new TwitchLib.Client.Services.MessageThrottler(client, 10, TimeSpan.FromSeconds(30));
client.WhisperThrottler = new TwitchLib.Client.Services.MessageThrottler(client, 10, TimeSpan.FromSeconds(30));
client.ChatThrottler.OnClientThrottled += ChatThrottler_OnClientThrottled;
client.WhisperThrottler.OnClientThrottled += WhisperThrottler_OnClientThrottled;
```

Is what I have for my throttlers and 

`        private void WhisperThrottler_OnClientThrottled(object sender, TwitchLib.Client.Events.Services.MessageThrottler.OnClientThrottledArgs e)
        {
            Console.WriteLine("Message Throttled");
        }

        private void ChatThrottler_OnClientThrottled(object sender, TwitchLib.Client.Events.Services.MessageThrottler.OnClientThrottledArgs e)
        {
            Console.WriteLine("Message Throttled");
        }'

for my OnClientThrottled events. When I comment these out, the bot works flawlessly, but when they're in totally nonfunctional. The OnClientThrottled events don't even trigger, the bot just does nothing

**Comment by swiftyspiffy** [comment]
Try adding `StartQueue();` after `client.ChatThrottler = new ...`
Something like:
```csharp
client.ChatThrottler = new TwitchLib.Client.Services.MessageThrottler(client, 10, TimeSpan.FromSeconds(30));
client.WhisperThrottler = new TwitchLib.Client.Services.MessageThrottler(client, 10, TimeSpan.FromSeconds(30));
client.ChatThrottler.StartQueue();
client.WhisperThrottler.StartQueue();
client.ChatThrottler.OnClientThrottled += ChatThrottler_OnClientThrottled;
client.WhisperThrottler.OnClientThrottled += WhisperThrottler_OnClientThrottled;
```

**Comment by swiftyspiffy** [comment]
Haven't heard an update on here. Going to go ahead and close it. Feel free to reopen as needed.
