### ISSUE TITLE
Host events not working

### ISSUE THREAD

**Issue by PenguinPero** [TwitchLib/TwitchLib#402]
So I'm having trouble with receiving host events
Example code below does not work:

```csharp
...
// subscribed to events
_client.OnBeingHosted += OnBeingHosted;
_client.OnHostingStarted += OnHostingStarted;

...
// handlers
private static void OnBeingHosted(object sender, OnBeingHostedArgs e)
{
    var host = e.BeingHostedNotification.HostedByChannel;
    var viewers = e.BeingHostedNotification.Viewers;

    SendChatMessage($"Hey @{_channel}, we just got hosted by {host} with {viewers} viewers Kappa");
    AppLogger.LogMessage(MessageLevel.Warning, "Host received with OnBeingHosted");
}

private static void OnHostingStarted(object sender, OnHostingStartedArgs e)
{
     var host = e.HostingStarted.HostingChannel;
     var viewers = e.HostingStarted.Viewers;

     SendChatMessage($"Hey @{_channel}, we just got hosted by {host} with {viewers} viewers Kappa");
     AppLogger.LogMessage(MessageLevel.Warning, "Host received with OnHostingStarted");
}
```

So am I doing something wrong or is it a bug?

**Comment by LuckyNoS7evin** [comment]
@PenguinPero which user are you connecting as and to what channel?

**Comment by PenguinPero** [comment]
@LuckyNoS7evin I'm connecting as "imkappabot" to my own channel "penguinpero"

@Mahsaap is it fixed there or?

**Comment by LuckyNoS7evin** [comment]
@PenguinPero to get hosts you do need to connect as yourself to your channel as hosts are not available to anyone except the broadcaster.

However on that note there is also an issue which hasn't been released in nuget yet.

In other words it's partially an issue at our end and partially an issue at yours .

**Comment by Mahsaap** [comment]
We are going to ask @swiftyspiffy to push a new version to nuget (It has been 21 days since the last one). But for now you could clone the repo if you needed it to work for now.

**Comment by PenguinPero** [comment]
@LuckyNoS7evin yeah, I just took a look at the @Mahsaap 's comment
Thank you for that, I thought that might be a problem. I will just connect as myself in the future.
Thanks! :)

**Comment by Mahsaap** [comment]
That's why something like streamlabs has a streamer/bot connect. Let us know if it fixes the issue. And close  the issue if you get it working :) Hope you get it working.

**Comment by PenguinPero** [comment]
@Mahsaap yes, I will test it asap when I get back home :)

**Comment by PenguinPero** [comment]
@Mahsaap @LuckyNoS7evin yep, I just connected with my own user and it works, thanks!
