### ISSUE TITLE
EmoteSet.Emotes is always empty

### ISSUE THREAD

**Issue by LeXtruX** [TwitchLib/TwitchLib#405]
As stated before, whenever I want to use the EmoteSet.Emotes, it always returns as an empty list of Emotes...
Even when following your code in another issue on here, it still returns nothing
`Console.WriteLine(e.ChatMessage.EmoteSet.Emotes.Count); `will return 0

**Comment by RRickkert** [comment]
Can confirm this issue. Found a fix, there was a different implementation for the ChatMessage vs the Whisper Message. Making it the same implementation fixed this. However, there might've been a reason for implementing it a different way. We'll see!

**Comment by swiftyspiffy** [comment]
This has been fixed by @RRickkert PR.

**Comment by LeXtruX** [comment]
Well, he fixed it, but he did not quite share how to make it the same implemantation...
