### ISSUE TITLE
exist any way to get current title and game

### ISSUE THREAD

**Issue by Zhet1** [TwitchLib/TwitchLib#409]
im reading old issues and cant find any solution, this is my actual code: 

![image](https://user-images.githubusercontent.com/13082170/42243192-7a38056a-7ede-11e8-87bc-18db7d5358c0.png)

any solution?

**Comment by swiftyspiffy** [comment]
Hi!
Try something like this:
![855qas422](https://user-images.githubusercontent.com/9569194/42250780-9c4e2186-7ef0-11e8-9b4d-089f4e03dabe.png)

**Comment by Zhet1** [comment]
works perfectly, thanks
