### ISSUE TITLE
follower service

### ISSUE THREAD

**Issue by devJav1** [TwitchLib/TwitchLib#410]
how can implement the following service? because i can't find any example of that.

**Comment by devJav1** [comment]
work great but the variable e.NewFollowers returns this : `TwitchLib.Api.Models.v5.Channels.ChannelFollow` and i just need the name of the new follower


`

**Comment by Mahsaap** [comment]
Channelfollower.user.name

**Comment by Zhet1** [comment]
@Mahsaap ??? i dont understant your answer

**Comment by Mahsaap** [comment]
Show what your using that returns that string

**Comment by Zhet1** [comment]
![image](https://user-images.githubusercontent.com/13082170/42402034-775e8ae8-8146-11e8-9f79-73c5614b5079.png)

im using this @Mahsaap

**Comment by Mahsaap** [comment]
ahhh ok i see, im a bit busy right now. I asked someone to help if they can :)

**Comment by swiftyspiffy** [comment]
@Zhet1 e.NewFollowers is a list, so you'd want to do something like:

![https://swfty.xyz/682kzy269](https://swfty.xyz/682kzy269)

**Comment by LuckyNoS7evin** [comment]
```string.Join(',',e.NewFollowers.Select(X => X.DisplayName))```

**Comment by swiftyspiffy** [comment]
@LuckyNoS7evin I knew there was a magical lambda to do it

**Comment by Zhet1** [comment]
@LuckyNoS7evin  @LuckyNoS7evin @Mahsaap thanks for the help, works perfect

**Comment by swiftyspiffy** [comment]
Feel free to reopen as needed.

**Comment by grobekelle** [comment]
Unfortunately, the links to the code example are no longer available. Could someone post a corresponding example here again? Many thanks in advance!
