### ISSUE TITLE
System.TypeLoadException

### ISSUE THREAD

**Issue by WoweePaw** [TwitchLib/TwitchLib#418]
```The type "TwitchLib.Communication.TcpClient" in the assembly "TwitchLib.Communication, Version = 1.0.0.0, Culture = neutral, PublicKeyToken = null" could not be loaded.```

And

```The type "TwitchLib.Communication.WebSocketClient" in the assembly "TwitchLib.Communication, Version = 1.0.0.0, Culture = neutral, PublicKeyToken = null" could not be loaded.```

Using TwitchLib 3.0.0 from NuGet (all subs also updated to "latest") on .NET Framework 4.6.2
Is something missing on my end or is it no longer .NET Framework 4.6.2 Supported? I'm a bit lost ^^'

**Comment by Mahsaap** [comment]
Swift actually removed v3 shortly after because of this and pretty sure he knows why but hasnt fixed yet.

**Comment by D3thw0lf** [comment]
Actually I don't really know anymore which version everything is... ^^' all those subthings have different versions ... the new ones starts on 1.0.0 the oldest are on 3.0x or higher ... very confusing but the "main" thing called "TwitchLib" is on 3.x so I guess this counts as the "used version"? :D
