### ISSUE TITLE
Can't get top clips

### ISSUE THREAD

**Issue by diogomartino** [TwitchLib/TwitchLib#421]
`TopClipsResponse response = await api.V5.Clips.GetTopClipsAsync(streamer, null, null, 5, Period.Day);`

Is triggering:

> Newtonsoft.Json.JsonSerializationException: 'Could not create an instance of type TwitchLib.Api.Core.Interfaces.Clips.IVOD. Type is an interface or abstract class and cannot be instantiated. Path 'clips[0].vod.id', line 1, position 1030.'

Is this the right way to do it or am I doing something wrong?

**Comment by swiftyspiffy** [comment]
This is known. A temp fix is to replace IVOD with just VOD, but obviously that doesn't fix the package.

**Comment by TehKingPenguin** [comment]
What do you mean replace IVOD with VOD? @swiftyspiffy

**Comment by swiftyspiffy** [comment]
Confirmed that this is working. Though consider moving to Helix (also sorry for late response).
