### ISSUE TITLE
onNewFollowerDetectedArgs doesnt store name anymore.

### ISSUE THREAD

**Issue by Bappsack** [TwitchLib/TwitchLib#422]

**Comment by Mahsaap** [comment]
Services now use Helix endpoints, and in turn only can supply what is supplied in the Helix api. Name is not and you will have to get that information through other means.

**Comment by Mitsukiii** [comment]
any good point why this change had to be made? most stuff need now to be rewritten :/

**Comment by Mahsaap** [comment]
V5 is deprecated so all things will be using Helix eventually, it is known that it is not fully implemented yet. However as library it was decided to use the latest API on this release but myself I can't say for sure what the exact reasoning was. In truth it does work the same as the service intended, but you are correct that the calls (twitch's end) do not return everything most people are using. its a win/loose imo.

I'm hoping that swift or one of the other guys will chime in and shed a better light then I have. Best of luck.

**Comment by Mitsukiii** [comment]
a new example workaround for the Follower Detection is something like this:

```
 private async void onFollowersDetected(object sender, OnNewFollowersDetectedArgs e)
        {
            try
            {
                string latestFollower = String.Empty;
                foreach (var item in e.NewFollowers)
                {
                    Follower = await api.V5.Users.GetUserByIDAsync(item.FromUserId.ToString());

                    if (latestFollower != Follower.Name)
                    {
                       // Do Something here.
                    }
                }
            }
        }
```

**Comment by swiftyspiffy** [comment]
As Mahsaap stated, this is not possible strictly with what that Helix endpoint returns (though you can use GetUsers).
