### ISSUE TITLE
ChattersFormatted broken?

### ISSUE THREAD

**Issue by Bappsack** [TwitchLib/TwitchLib#423]
Chattersformated is now stored at:

 "TwitchLib.Api.Models.Undocumented.Chatters.ChatterFormatted"

but should be;

"TwitchLib.Api.Core.Models.Undocumented.Chatters.ChatterFormatted"

**Comment by Mitsukiii** [comment]
^ same with Subscriptions:

"TwitchLib.Api.Models.v5.Subscriptions.Subscription" 

should be:

"TwitchLib.Api.V5.Models.Subscriptions.Subscription"

**Comment by Mahsaap** [comment]
Things were moved in V3, major change, breaking changes.

**Comment by swiftyspiffy** [comment]
This has sense been updated, and it's working.
