### ISSUE TITLE
Missing Docs

### ISSUE THREAD

**Issue by xzessmedia** [TwitchLib/TwitchLib#424]
This Library seems good but there is no example for it..
And a Doxygen generated file doc useless when not up to date...

people will use other libraries cause of that

**Comment by Mahsaap** [comment]
There are starting examples in the main repo and some specific ones in specific repos. Reading github from there should be enough, until someone has time to update some. This is all volunteered and I think most of us are currently taking courses that have halted this progress.

This is known and really don't think it requires a issue. Sure it's a nice thing to have but at current point not required. The examples will get someone started if they understand the language.

We are happy to help, Please just ask what you need help with specifically and if someone can help normally within 24hr we will. Knowledge if the language is implied.

**Comment by swiftyspiffy** [comment]
I have updated the doxygen docs: https://swiftyspiffy.com/TwitchLib/

**Comment by swiftyspiffy** [comment]
As sated, updated.
