### ISSUE TITLE
FollowChannelAsync

### ISSUE THREAD

**Issue by LochiQF** [TwitchLib/TwitchLib#426]
Hello there, it may be that I'm confused and messing up something really easy but, the method `FollowChannelAsync` doesn't seem to work.
I currently have an access token with the scope user_follows_edit and defined the parameters `userId`, `channelId` with respectively the bot id and the broadcaster id.
Hope you will be able to provide light on the problem.

**Comment by Mahsaap** [comment]
You will need the scope User_Follows_Edit

I think 
userID is bot's account ID (not sure why this is required, should be able to grab internally)
and channelId is the channel you want to follow with the bot account.

**Comment by LochiQF** [comment]
> I currently have an access token with the scope user_follows_edit

**Comment by Mahsaap** [comment]
I'm not sure, someone that worked with this will have to step in. I'm just going to be guessing at this point.

**Comment by swiftyspiffy** [comment]
Checking now

**Comment by swiftyspiffy** [comment]
Using the latest NuGet package, and running the code below, it worked as expected:
```csharp
var api = new TwitchAPI();
api.Settings.ClientId = "56m7k3nnkpa6....";
api.Settings.AccessToken = "jqf3z64vw873....";

var resp = api.V5.Users.FollowChannelAsync("40876073", "57690918").GetAwaiter().GetResult();
```
Client id is from an old project, and token generated on https://twitchtokengenerator.com using `user_follows_edit` scope.

Where `40876073` is userid of `swiftyspiffy` and `57690918` is userid of `KappaKares`.

If that doesn't work for you, the only thing I can think of is maybe Twitch flagged your account for suspicious activity and is blocking the functionality.

Can you post your code and error (if there is one)?

**Comment by LochiQF** [comment]
Hey spiffy, I contacted twitch support and the account was indeed flagged as suspicious for an error on their end, thanks for your support and your prompting debugging!

**Comment by LochiQF** [comment]
Also, would it be possible to have a resolution for issue #421 while retrieving top clips? At the moment it's impossible to get weekly monthly or daily clips without getting said error. Tried out the Helix call aswell but we can't define the timespan in which we want the channel clips.

**Comment by swiftyspiffy** [comment]
Both the original issue, and the referenced #421 issue have been resolved.
