### ISSUE TITLE
Twitch chat on android not running

### ISSUE THREAD

**Issue by zaneDraper** [TwitchLib/TwitchLib#427]
Hey guys,

I'm running into a bit of an issue with TwitchLib on an Android build. I have a chat feed running from a chosen channel, with the OnMessageReceived event, and it seems to be running with no issue in editor. As soon as I build the project to Android I will either receive 0 message events, or just a few before it stops responding. After that no events are received.

Any help or input on this would be really appreciated.

Thanks

**Comment by Syzuna** [comment]
Hello there,

thats definetly an odd one. I think we did not have someone who built an android app with Twitchlib but in theory there shouldnt be any problems as we soley use .net standard 2.0 which should be fully supported through xamarin.

Is there any error logs or debug logs you can provide for more insights?

**Comment by swiftyspiffy** [comment]
Please reopen if this is still happening on android.
