### ISSUE TITLE
Events randomly stop working

### ISSUE THREAD

**Issue by Insensitivity** [TwitchLib/TwitchLib#428]
So after looking through closed issues I found someone else describing a similar issue

https://github.com/TwitchLib/TwitchLib/issues/275

also somewhat this https://github.com/TwitchLib/TwitchLib/issues/427
"or just a few before it stops responding. After that no events are received."

Basically, just make a client, listen to the OnMessageReceived event, log messages to console. After around ~10 minutes (varies could be 3 minutes could be 30 minutes, usually around 10 minutes), the event stops firing.

At first I thought it was some kind of disposing or garbage collecting issues, so I tried to call SendMessage when the client stopped receiving messages, and the message does send, it just doesn't receive any events back (not even OnMessageSent although the message does fire).

No errors are thrown, the client is clearly not disconnected, the events just don't fire.

I'm using .NET Core 2.1, Running TwitchLib v3.0.1, I've tried using both ASP.NET Core and just a simple Console Application.

I've tried rolling back to .NET Core 2.0 which should be supported, the problem consisted, so I don't think that's it. Also tried compiling against .NET Framework 4.7.2 which didn't yield any better results.

I have a previously built (1~ year ago) project using .NET Framework 4.5.2, using TwitchLib v1.6.1 which doesn't seem to experience this problem.

Any help is appreciated.

**Comment by Mahsaap** [comment]
What OS are you running this on? also, can you supply your code/test code. So we can determine or try to replicate the issue.

**Comment by Insensitivity** [comment]
Running Windows 10 Pro 1803

```
private static void Main()
{
	_client = new TwitchClient();

	var credentials = new ConnectionCredentials("username", "auth");

	_client.Initialize(credentials, "channel");

	_client.OnConnected       += OnConnected;
	_client.OnDisconnected    += OnDisconnected;
	_client.OnReconnected     += OnReconnected;

	_client.OnMessageSent     += OnMessageSent;
	_client.OnMessageReceived += OnMessageReceived;

	_client.OnJoinedChannel   += OnJoinedChannel;
	_client.OnLeftChannel     += OnLeftChannel;

	_client.Connect();
	
	Console.ReadLine();
}

public void OnMessageReceived(object sender, OnMessageReceivedArgs args)
{
	Console.WriteLine($"{args.ChatMessage.Username}: {args.ChatMessage.Message}");
}
```

The rest of the events are all in similar fashion to the one I provided, simply logging some form of text to the console.

To test if the client is still able to send messages after the events stop firing I added a method when a certain key is pressed, which executes `_client.SendMessage("channel", "test message");` which in fact worked.

**Comment by Insensitivity** [comment]
I changed the project to target .NET Framework 4.5.2 and TwitchLib 2.1.4 and the problem seems to be gone. Has there been any major change between 2.1.4 to 3.0.3 ?

**Comment by prom3theu5** [comment]
Sounds like an exception is throwing inside a task somewhere killing the client and it’s being caught / wrapped as an aggregate exception

**Comment by Vasilyi** [comment]
Events dying when subscriber occur (10/10 reproduction rate).  When trying to client.disconnect() after that got this error
![image](https://user-images.githubusercontent.com/1212325/50774749-4d761980-12a5-11e9-9dc0-2c07287dc2d6.png) 
Worked fine on 2.1.2 which i used before

**Comment by Jaminima** [comment]
I found using TwitchLib v2.1.5 and TwitchLib.Api v2.1.3 fixes the problem. Can confirm is still an issue.

**Comment by SeeingBlue** [comment]
Same as reported here: [#437](https://github.com/TwitchLib/TwitchLib/issues/437)

**Comment by Locxion** [comment]
Still an Issue
https://sentry.io/locxservde/nanotwitchleafs/issues/882061342/?query=is%3Aunresolved

**Comment by Mahsaap** [comment]
Another reason and already in works. So actually it's another issues technically. I've mentioned this to you already Seeing

**Comment by bwoogie** [comment]
Same problem. It seems to stop receiving messages when chat gets going fast?

**Comment by XanderStoffels** [comment]
Still happening for me using  TwitchLib 3.0.1.
The problem occurs randomly, after receiving messages for 10 seconds to 30 minutes.

**Comment by Mahsaap** [comment]
Pre release on individual packages.

**Comment by Mahsaap** [comment]
Known issue now thats fixed on dev branch

**Comment by XanderStoffels** [comment]
> Known issue now thats fixed on dev branch

Any idea when it will be released?

**Comment by Mahsaap** [comment]
I've asked to a few times, hasn't happened. Really just pre release atm. Its more stable to use it then master atm.

**Comment by swiftyspiffy** [comment]
This is definitely in the main release now.
