### ISSUE TITLE
NuGet Install, Operation Failed

### ISSUE THREAD

**Issue by Komak57** [TwitchLib/TwitchLib#429]
Attempting to install TwitchLib in a C# project under visual Studio 2013. Install under .NET 4.5.2 failed. Confirmed Framework of source at 2.0, adjusted project to match. Install still gets error Operation failed.

`Attempting to resolve dependency 'TwitchLib.Client (≥ 3.0.3)'.`
`Attempting to resolve dependency 'TwitchLib.Api (≥ 3.0.0)'.`
`Attempting to resolve dependency 'TwitchLib.PubSub (≥ 3.0.2)'.`
`Installing 'TwitchLib.Client 3.0.3'.`
`Successfully installed 'TwitchLib.Client 3.0.3'.`
`Installing 'TwitchLib.Api 3.0.0'.`
`Successfully installed 'TwitchLib.Api 3.0.0'.`
`Installing 'TwitchLib.PubSub 3.0.2'.`
`Successfully installed 'TwitchLib.PubSub 3.0.2'.`
`Installing 'TwitchLib 3.0.1'.`
`Successfully installed 'TwitchLib 3.0.1'.`
`Adding 'TwitchLib.Client 3.0.3' to plgTwitch.`
`Uninstalling 'TwitchLib.Client 3.0.3'.`
`Successfully uninstalled 'TwitchLib.Client 3.0.3'.`
`Install failed. Rolling back...`
`Could not install package 'TwitchLib.Client 3.0.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v2.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by prom3theu5** [comment]
With version 3.0 of TwitchLib, minimum full framework version is now 4.6.1

You can try adding the netstandard nuget package to your solution however I do not think you can install this in a 4.5.2 project.

**Comment by Komak57** [comment]
Updated to .NET 4.6.1, attempted nuget.org repository, still getting 

`Could not install package 'TwitchLib.Client 3.0.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by prom3theu5** [comment]
Add the nuget package "NetStandard" to your solution, then try adding TwitchLib

**Comment by Komak57** [comment]
Visual Studio updated, NuGet installer updated, NetStandard.Library installed, OS rebooted, still getting the same error.

**Comment by Mahsaap** [comment]
4.6.2 8s minimum actually 
![screenshot_20181109-190036_samsung internet](https://user-images.githubusercontent.com/13688718/48292734-f644fb80-e451-11e8-8654-70bca494dc5d.jpg)

**Comment by prom3theu5** [comment]
![Example](https://i.imgur.com/eF2VwI4.gif)

I don't know what to suggest.
It definitely works with .net 4.6.1 upwards for Full Framework, and netcoreapp2.1 for .net core frameworks in Visual Studio 2017, as well as with the NuGet Cli tool, and DotNet executable for .net core.

Sounds like your solution may be a little broken.
You could try removing the bin and obj folders for each of your solutions projects, as well as the solutions packages folder, and then restoring NuGet packages for the solution.
I'd start with removing TwitchLib entirely.
Failing that - something is wrong with your VS setup / installation.

You DO NOT want to be trying anything with a framework version lower than .net 4.6.1 as it definitely won't work.

**Comment by Komak57** [comment]
Success.

Open project in VS2017 (might not be required)
Reset each Project's Compile back to `bin\Debug\` (might not be required)
Right Click Solution
Manage NuGet Packages for Solution
Select Installed
Removed _EVERY_ Package currently installed for all Projects in Solution
Browse for TwitchLib
Install for target Project

I look forward to incorporating your library into my bot! Thank you for looking into this with me.
