### ISSUE TITLE
How update channel language?

### ISSUE THREAD

**Issue by Shadowmafia** [TwitchLib/TwitchLib#430]
I apologize for the stupid question but I really did not find how to do it =(

**Comment by Mahsaap** [comment]
I cant find anything, only getting. But I think its account bound not channel so this may not be possible and only through settings same. At least for what I can find.

**Comment by Mahsaap** [comment]
but i could be wrong.

**Comment by swiftyspiffy** [comment]
I've forwarded this to a twitch staff and will be closing the issue for the time being.
