### ISSUE TITLE
DisplayNames for chatter entpoint

### ISSUE THREAD

**Issue by andreasblueher** [TwitchLib/TwitchLib#431]
Hey, 

I was wondering if it's possible to get the DisplayName of users for the Chatters endpoint. Else I would need to use the username and do a 2nd request to GetUsersByNameAsync right?

Thanks in advance

**Comment by Mahsaap** [comment]
Getchatters is undocumented , but I would guess twitch doesn't supply that, otherwise it would be part of the object. 
This is the object returned in the lib

```
        public ChatterFormatted(string username, Enums.UserType userType)
        {
            Username = username;
            UserType = userType;
        }
```

If username is not good enough, then yes you would need to do another call.
