### ISSUE TITLE
NullRefrenceException

### ISSUE THREAD

**Issue by XZcutable** [TwitchLib/TwitchLib#432]
I keep randomly getting this message "NullReferenceException: Object reference not set to an instance of an object
TwitchLib.Unity.ThreadDispatcher.Update () (at <3bb271f39a1b40ebb4b7264da4c75710>:0)" I'm not sure what is causing it or how to debug for it or even how to replicate it. Sometimes in one run, it's gone and in another, it will happen. Sometimes it breaks my program, other times it works (sends messages) and keeps calling that error. I'll keep trying to figure out what exactly is causing. It's weird because even in the source code I don't understand what could be null. I even tried changing the script execution order.

**Comment by swiftyspiffy** [comment]
I'm going to close this in favor of the issue @Mahsaap made.
