### ISSUE TITLE
api.V5.Users.GetUserBlockListAsync Not Correct working

### ISSUE THREAD

**Issue by Feindfluglp** [TwitchLib/TwitchLib#433]
Hello.
I become back a user list from: api.V5.Users.GetUserBlockListAsync
the problem its, not all the user.

Example:
i have ban a new user, i can´t see the new user in the list.
What its wrong?
Twitch have change this and the TwitchLib musst update?

**Comment by Mahsaap** [comment]
Ensure you have the user_blocks_read scope

**Comment by Feindfluglp** [comment]
don´t understand what you means, hm

**Comment by Mahsaap** [comment]
https://dev.twitch.tv/docs/authentication/#scopes

**Comment by Feindfluglp** [comment]
My Acess token its whit all scopes.
hm

**Comment by Feindfluglp** [comment]
Thx for your help, this its for my personal blocklist and not the stream banlist. closed here ;)
