### ISSUE TITLE
api.Undocumented.GetChattersAsync Not VIP showing

### ISSUE THREAD

**Issue by Feindfluglp** [TwitchLib/TwitchLib#434]
hello.
from twitch the new rank vip its not all working in the api.
from: api.Undocumented.GetChattersAsync can´t see its a vip.
pls update the twitchlib

**Comment by Mahsaap** [comment]
Its updated in dev branch waiting nuget update maybe this week

**Comment by sweethuman** [comment]
https://github.com/TwitchLib/TwitchLib.Api/pull/97

**Comment by Mahsaap** [comment]
Yes however the model reference is wrong in the latest nuget and probably not there. Automation is in the works. So that this doesnt happen and auto uploads to nuget from master.

**Comment by swiftyspiffy** [comment]
This should be resolved now.
