### ISSUE TITLE
TwitchLib crashing on TwitchClient.Connect on Windows 7 machines

### ISSUE THREAD

**Issue by emosaru** [TwitchLib/TwitchLib#435]
Since upgrading to 3.0, I have had reports of Windows 7 users crashing when trying to connect to Twitch, with an PlatformNotSupported exception. My gut suspicion is something to do with the underlying web socket implementation being used.

**Comment by Mahsaap** [comment]
from old post in discord
windows 7 only supports websockets on projects that target .NET Core 2.1+

**Comment by Feindfluglp** [comment]
i have too windows 7 maschine.
user this: client = new TwitchClient(protocol: ClientProtocol.TCP);
and all run perfekt ;)

**Comment by swiftyspiffy** [comment]
@emosaru can you give @Feindfluglp 's suggestion a try?

**Comment by emosaru** [comment]
Yep already in progress - was just waiting on test results from a user before I responded. Will report back here with the outcome.

**Comment by emosaru** [comment]
This has been resolved with the suggested changes.
