### ISSUE TITLE
OnExistingUsersDetected not triggering

### ISSUE THREAD

**Issue by Seeker1437** [TwitchLib/TwitchLib#436]
It looks like when the message is being parsed, the parser is not handling the format properly so the names are completely dropped and as a result the event cannot be triggered because there are no usernames to parse.

**Comment by Seeker1437** [comment]
I ported a message parser into my fork of this library and was able to correct the parsing of RPL_353  command to the point where it works. Should I bring it in?

**Comment by swiftyspiffy** [comment]
This is fixed now. Apologies for the 3 year delay lol
