### ISSUE TITLE
Chat related events break when there's a new sub

### ISSUE THREAD

**Issue by NotAkitake** [TwitchLib/TwitchLib#437]
Title says it all, my "OnChatCommandReceived" (also tried OnMessageReceived) won't run when a new subscriber arrives, and forces me to restart the bot, this is a critical issue and will force me to change libraries unless a fix is applied.

**Comment by RickRosendaal** [comment]
Could you provide us with a simple example reproducing this issue?
From my understanding, you're listening to the OnChatCommandReceived event and it works fine, until someone subscribes?

A few questions:
1: How do you test this? Is it an actual subscriber on Twitch, or are you simulating a subscription somehow?
2: Does it also happen with Resubs / Gifted subs / Anonymous gift subs?
3: Have you tried switching from the default WebSocket to the TCP method? Does this change anything?

Like I said a simple example could help a lot. Just a client being created, the binding of the events, etc. So we can reproduce the issue and solve it.

**Comment by Mahsaap** [comment]
I'd also make sure something in your sub method isn't causing a halt of some sort.

**Comment by swiftyspiffy** [comment]
Hey. This is an interesting problem. If the connection is dying or the bot instance state is corrupting, that’s a major problem.

As the others have stated, posting the code would help immensely. Even better, if you could create a really simple example that demonstrates if, that’d be even better.

Also are you able to tell what version of the packages you’re using?

**Comment by AkitakeKun** [comment]
> 
> 
> Hey. This is an interesting problem. If the connection is dying or the bot instance state is corrupting, that’s a major problem.
> 
> As the others have stated, posting the code would help immensely. Even better, if you could create a really simple example that demonstrates if, that’d be even better.
> 
> Also are you able to tell what version of the packages you’re using?

Yes, the application itself does not crash, and no errors are logged through any of the Error logging events, nor the OnLog event. It also does not output anything through OnDisconnected, it just (seemingly) stops.

I am currently using the latest stable version of TwitchLib (3.0.1) along with its sub-modules (installed through NuGet), on .NET Framework 4.6.1

**Comment by Mahsaap** [comment]
I could be wrong on this. However the tags In the reader do state 4.6.2. Could give thats try. I use core myself.

**Comment by AkitakeKun** [comment]
> 
> 
> I could be wrong on this. However the tags In the readme do state 4.6.2. Could give thats try. I use core myself.

Well noted, I have just changed the .NET Framework version my project targets.
I also have finished re-writing a big part of my project and will be uploading it on GitHub shortly. Will update this message when done so.

**Comment by RRickkert** [comment]
I used your project and simulated a subscription and most likely figured out the issue.

I'm pretty sure that the latest TwitchLib.Client nugget package does not have the required version of the TwitchLib.Client.Models project. Which is resulting in an exception being thrown when accessing models which haven't been added to the assembly (such as TwitchLib.Client.Models.AnonGiftedSubscription). This results in a runtime TypeLoadException for the AnonGiftedSubscription when someone subscribes to a channel (doesn't matter if it's a gifted subscription or not).

Looking at the references you use in your project, the version of Client.Models you're using does not contain that AnonGiftedSubscription class, resulting in the error.

**Comment by RRickkert** [comment]
Using a prerelease package does fix the issue in my test case!
If you'd like to test it out yourself, I used the OnReadLineTest method in the Twitch Client. You can pass along an IRC response string and it'll act as if it came from Twitch. In your case I used an example from the documentation: https://dev.twitch.tv/docs/irc/tags#usernotice-twitch-tags

```
client.OnReadLineTest(@"@badges=staff/1,broadcaster/1,turbo/1;color=#008000;display-name=ronni;emotes=;id=db25007f-7a18-43eb-9379-80131e44d633;login=ronni;mod=0;msg-id=resub;msg-param-months=6;msg-param-sub-plan=Prime;msg-param-sub-plan-name=Prime;room-id=1337;subscriber=1;system-msg=ronni\shas\ssubscribed\sfor\s6\smonths!;tmi-sent-ts=1507246572675;turbo=1;user-id=1337;user-type=staff :tmi.twitch.tv USERNOTICE #rrickkert :Great stream -- keep it up!");
```
The examples on the website have a "> " in front of it, but you should remove that. And since it contains backslashes, you should put an @ sign in front of it.
Maybe that helps you out as well testing other scenarios!

**Comment by AkitakeKun** [comment]
> 
> 
> Using a prerelease package does fix the issue in my test case!
> If you'd like to test it out yourself, I used the OnReadLineTest method in the Twitch Client. You can pass along an IRC response string and it'll act as if it came from Twitch. In your case I used an example from the documentation: https://dev.twitch.tv/docs/irc/tags#usernotice-twitch-tags
> 
> ```
> client.OnReadLineTest(@"@badges=staff/1,broadcaster/1,turbo/1;color=#008000;display-name=ronni;emotes=;id=db25007f-7a18-43eb-9379-80131e44d633;login=ronni;mod=0;msg-id=resub;msg-param-months=6;msg-param-sub-plan=Prime;msg-param-sub-plan-name=Prime;room-id=1337;subscriber=1;system-msg=ronni\shas\ssubscribed\sfor\s6\smonths!;tmi-sent-ts=1507246572675;turbo=1;user-id=1337;user-type=staff :tmi.twitch.tv USERNOTICE #rrickkert :Great stream -- keep it up!");
> ```
> 
> The examples on the website have a "> " in front of it, but you should remove that. And since it contains backslashes, you should put an @ sign in front of it.
> Maybe that helps you out as well testing other scenarios!

Nice insight, had no idea that existed but yeah. Waiting on a solution/fix as this is a major issue that makes the library unusable in my case.

**Comment by AkitakeKun** [comment]
> 
> 
> Using a prerelease package does fix the issue in my test case!
> If you'd like to test it out yourself, I used the OnReadLineTest method in the Twitch Client. You can pass along an IRC response string and it'll act as if it came from Twitch. In your case I used an example from the documentation: https://dev.twitch.tv/docs/irc/tags#usernotice-twitch-tags
> 
> ```
> client.OnReadLineTest(@"@badges=staff/1,broadcaster/1,turbo/1;color=#008000;display-name=ronni;emotes=;id=db25007f-7a18-43eb-9379-80131e44d633;login=ronni;mod=0;msg-id=resub;msg-param-months=6;msg-param-sub-plan=Prime;msg-param-sub-plan-name=Prime;room-id=1337;subscriber=1;system-msg=ronni\shas\ssubscribed\sfor\s6\smonths!;tmi-sent-ts=1507246572675;turbo=1;user-id=1337;user-type=staff :tmi.twitch.tv USERNOTICE #rrickkert :Great stream -- keep it up!");
> ```
> 
> The examples on the website have a "> " in front of it, but you should remove that. And since it contains backslashes, you should put an @ sign in front of it.
> Maybe that helps you out as well testing other scenarios!

Nice! Thanks for the insight on that event, had no idea, but yeah, I already gathered subscriptions were the issue from OnLog as it was the latest line printed in my console before a crash.

Welp, gonna use the prerelease until the release branch gets a new update.

**Comment by JonnyOThan** [comment]
This issue took down my bot yesterday.  @RRickkert  can you clarify what versions of each library you are using?

**Comment by Mahsaap** [comment]
There are recent changes on twitch that will probably break it even with using pre release. Pr has been started but people seem busier then normal lately.

**Comment by JonnyOThan** [comment]
Adding for completeness: my chat events also stopped working when someone raided me.
