### ISSUE TITLE
Twitch updated the subscribe message in Chatroom

### ISSUE THREAD

**Issue by j835111** [TwitchLib/TwitchLib#439]
Twitch changes the subscribe message in Chatroom.
ReSubscriber.Months can't get correct value,only get zero.

**Comment by Mahsaap** [comment]
Has been PR'd to dev branch.

**Comment by j835111** [comment]
I found that still have issue on ReSubscriber.Months.
I used new version on NuGet(3.0.4).
Its will break IRCs connection.

**Comment by swiftyspiffy** [comment]
This should be resolved now. Please reopen if it is not.
