### ISSUE TITLE
Send collision

### ISSUE THREAD

**Issue by Seeker1437** [TwitchLib/TwitchLib#444]
You you try to send a message and a whisper at the same time the method used to send messages does not ensure the last message was sent before the first one was complete resulting in an exception.

I modified my code to fix this issue, however since it it also has SEVERAL other changes I do know how long it would take for me to make a PR, but basically use Semaphore Slim in your send async to ensure the send method does not return until the message is actually sent. It will prevent the exception.

**Comment by swiftyspiffy** [comment]
Just tested sending a message and whisper at the same time, and got no exceptions or any issues. Feel free to reopen if this is still an issue.
