### ISSUE TITLE
Connection hangs when raid or new subscriber events

### ISSUE THREAD

**Issue by StriBog45** [TwitchLib/TwitchLib#448]
When a new subscriber appears on the channel or a raid occurs, the bot firstly fails to trigger these events, secondly all the others events stop working (OnChatCommandReceived)
I do not even know how to catch this hang, there is no error, it just stops responding

`public TwitchBot()
        {
            connectionCredentials = new ConnectionCredentials(TwitchInfo.BotName, TwitchInfo.AccessToken);

            client = new TwitchClient();
            client.Initialize(connectionCredentials, TwitchInfo.Channel);

            client.OnChatCommandReceived += OnChatCommandReceived;
            client.OnJoinedChannel += OnJoinedChannel;
            client.OnNewSubscriber += OnNewSubscriber;
            client.OnRaidNotification += OnRaidNotification;
            client.Connect();

            var channelInfo = new TwitchLib.Api.Models.v5.Channels.Channel();
            twitchAPI = new TwitchAPI();
            twitchAPI.Settings.ClientId = TwitchInfo.ClientId;
            twitchAPI.Settings.AccessToken = TwitchInfo.AccessToken;
        }`

I use the latest versions of libraries
TwitchLib v3.0.1
TwitchLib.Api v3.0.0
TwitchLib.Client v3.0.4
TwitchLib.Communication v1.0.3

I found a similar question earlier, but I didn't understand the exact answer what to do, roll back the version? https://github.com/TwitchLib/TwitchLib/issues/437

**Comment by Mahsaap** [comment]
This is probably related to the sub model mission reference I  the release version. Remove what your using and install individually the pre release version should fix it.

**Comment by StriBog45** [comment]
By "sub model" did you mean TwitchLib.PubSub? Сhange version of TwitchLib.PubSub from 3.0.2 to 3.0.1?
![image](https://user-images.githubusercontent.com/32923304/56058575-f5f7b600-5d8b-11e9-8dee-e78aac8d0c18.png)


> This is probably related to the sub model miss reference In the release version. Remove what your using and install individually the pre release version should fix it.

**Comment by Mahsaap** [comment]
Nope. Check the box to the right of the search bar
