### ISSUE TITLE
Chat: Unaccounted for [UserState]: badge-info

### ISSUE THREAD

**Issue by JesNoFear** [TwitchLib/TwitchLib#450]
Is anyone else getting these messages upon connection?
Unaccounted for [UserState]: badge-info

using vb.net

**Comment by Mahsaap** [comment]
that is fixed in dev branch. to use this in nuget you will need to use each individually with pre-release checked. it does not work with the whole suite option.

**Comment by swiftyspiffy** [comment]
Dev has been published as stable. Feel free to reopen if needed.

**Comment by LeCanadienAlexo** [comment]
I'm also getting that error on a new project I started, I've been trying to find the issue but since my project has like 10 lines of code I'm unsure it would be on my side

**Comment by swiftyspiffy** [comment]
It’s more of a warning than anything. Basically it means Twitch is sending a field the library isn’t expecting, and isn’t parsing into the model.

It doesn’t break anything, it’s just a notice to add it to the library.

**Comment by LeCanadienAlexo** [comment]
Thanks! I thought it was causing an issue since the rest of the program didn't output anything, but I'll go back to bug hunting

**Comment by Mahsaap** [comment]
@swiftyspiffy @LeCanadienAlexo this was also updated (swift you removed this in dev a while back) so unless master is still not updated (suite install im guessing) this will still appear.
