### ISSUE TITLE
Git clone produces empty folders for projects

### ISSUE THREAD

**Issue by Danatobob** [TwitchLib/TwitchLib#451]
If I try to git clone https://github.com/TwitchLib/TwitchLib, then only the root folder contains files (.sln and some txt). TwitchLib.Api, TwitchLib.Client, TwitchLib.PubSub, TwitchLib.WebSocket folders are empty.

**Comment by Mahsaap** [comment]
The suite only references the individual packages and will need to clone each I believe.

**Comment by Danatobob** [comment]
I think the main reason is that, according to whats written on this page: https://github.com/TwitchLib/TwitchLib
those projects are on some weird trees instead of master branch:
TwitchLib.Api @ **dea442d**
TwitchLib.Client @ **1dc4514**
TwitchLib.PubSub @ **ee1e0d9**
TwitchLib.WebSocket @ **2ecf518** 

Also in git log for Twitch.Api folder there was a commit that erased files

> SHA-1: 6005427d8dd5242fa687da4638349f776be82c2e
> 
> * Remove files - they will be back
> 

So i think its bad configuration of branches in the parent branch or something like that

**Comment by Mahsaap** [comment]
It has to do with auto update on nuget. If it doesnr have the extra it wont kiow the difference and bit update. At least I think. I don't have the know how on that, but I do know it causes a headache trying to clone the repos as a whole. Your not the first

**Comment by Danatobob** [comment]
You are wrong, it's not related to what you mentioned. It's just how git works. 
I've figured it out - I had to check "recursive" checkbox in TortoiseGit (or use "--recursive" parameter in git command prompt) to clone with submodules.

**Comment by Mahsaap** [comment]
@RRickkert  since you were having this issue.

Also I'm not surprised I'm wrong I'm only repeating old convos. This is out of my reach anyway.

**Comment by Mahsaap** [comment]
Please close if this is no longer relevant.  Thanks for the info though. I may add it to the readme for others.

**Comment by Danatobob** [comment]
Ah, yeah. Closing

**Comment by Mahsaap** [comment]
Also as a heads up use prerelease "dev" branch. Still things broke on master as far as I know.

**Comment by Danatobob** [comment]
huh? I would assume master is a stable branch and dev is not. Thanks.

**Comment by Mahsaap** [comment]
It is however twitch changes things and the main people who push the master/nuget have been extremely busy with RL work. So no time to work on this sadly. I've requested a few times to updated.
