### ISSUE TITLE
Add pagination for Clips

### ISSUE THREAD

**Issue by laurathackray21** [TwitchLib/TwitchLib#452]
Similarly to this issue https://github.com/TwitchLib/TwitchLib/issues/347, the `TwitchLib.Api.Helix.Models.Clips.GetClip.GetClipResponse` model doesn't include the pagination field.

**Comment by Ebrithil95** [comment]
Any Update on this?

**Comment by SPDevDE** [comment]
+1
I would love to see a fix for this.

**Comment by Syzuna** [comment]
I fixed this in a PR I made a few minutes ago. ( https://github.com/TwitchLib/TwitchLib.Api/pull/143 )
once this PR is merged this should be up in the latest prerelease version on nuget shortly after

**Comment by Syzuna** [comment]
https://github.com/TwitchLib/TwitchLib.Api/pull/143 was merged. the latest TwitchLib.Api Nuget prerelease will incluce this change in just a few minutes after the CICD pipeline is done.

Feel free to reopen if sth was missed.
