### ISSUE TITLE
Video playback PubSub callbacks don't fire

### ISSUE THREAD

**Issue by vaindil** [TwitchLib/TwitchLib#453]
I'm on the latest nightlies as of this post, and the video playback PubSub callbacks don't fire. They are being received, an example payload is below (from `OnLog`), but the callbacks don't fire.

```
{"type":"MESSAGE","data":{"topic":"video-playback.vaindil","message":"{\"type\":\"viewcount\",\"server_time\":1564183737.307632,\"viewers\":1}"}}
```

**Comment by swiftyspiffy** [comment]
Fixed per the PR vaindil sent.
