### ISSUE TITLE
How to get .dll out of this?

### ISSUE THREAD

**Issue by ghost** [TwitchLib/TwitchLib#455]
Hello. I need to update a .dll file in one of programs that used this library. How can I just compile this or whatever to get .dll which I can replace with one I have? I need TwitchLib.dll

**Comment by xHeaven** [comment]
Just update the NuGet package. you don't have to compile/replace anything.

**Comment by Toemsel** [comment]
Just download the nuget to your desktop, right click, extract.

**Comment by Mahsaap** [comment]
You need recursive node I believe

**Comment by swiftyspiffy** [comment]
Either of the methods above should work. Closing, feel free to reopen if needed.
