### ISSUE TITLE
OnUserJoined - how does this work?

### ISSUE THREAD

**Issue by mgroves** [TwitchLib/TwitchLib#456]
I'd like to write some code that will perform an action when certain users start watching my stream. Should I be using the OnUserJoined event? I tried it out, and I'm not exactly sure how it's working or how it's supposed to work. Does this trigger when anyone starts viewing? Is it supposed to trigger on every page refresh, for instance? When/how does a user "leave"?

**Comment by Mahsaap** [comment]
It will trigger when someone enters in that chat channel for that stream
And onuser leaves is when they arnt anymore given they arnt invisible

**Comment by mgroves** [comment]
That is not the behavior I'm seeing, though. I run my application and after a while, the event will be fired for a handful of users, even though no one has arrived (I'm testing it in my channel while not streaming). Even if there are users who are lurking, they aren't *joining*. Is there anymore information on these events, perhaps to illuminate what I'm doing wrong?

**Comment by Mahsaap** [comment]
You will need to use pre release on nuget on individual twitchlib.client and whatever else your using. There is a known issue in master for a while that I thought had been pushed the other day but hasn't. Basically makes events hang.

**Comment by swiftyspiffy** [comment]
`OnUserJoined` and `OnUserLeft`, as with other library events, fire as soon as the library receives data from Twitch.

Twitch sends these updates in bulk, especially for larger channels. I think Twitch used to send this data in real time, but has since moved to sending them in bulk on intervals, so you should not use these events if you're trying to track in real time.

**Comment by mgroves** [comment]
@Mahsaap I am using the latest prerelaase

@swiftyspiffy is there a different/better way to track? I'd like to trigger something to happen right as a user joins the channel (or within a few seconds of that would be fine)

**Comment by Mahsaap** [comment]
Pretty sure that's a twitch/irc limitation

**Comment by swiftyspiffy** [comment]
Going to close this. Feel free to reopen if needed.
