### ISSUE TITLE
Twitch API - Missing user_name field

### ISSUE THREAD

**Issue by FunkyFr3sh** [TwitchLib/TwitchLib#457]
`.Helix.Streams.GetStreamsAsync()`

Only contains user_id but not user_name which is forcing me to do another unnecessary request to turn the user_id into a user_name

**Comment by swiftyspiffy** [comment]
What version are you using? Because I think it exists: https://github.com/TwitchLib/TwitchLib.Api/blob/master/TwitchLib.Api.Helix.Models/Streams/Stream.cs#L13

**Comment by FunkyFr3sh** [comment]
Using nuget `<PackageReference Include="TwitchLib" Version="3.0.1" />`  which seems to be the highest available from what I can see.

I just noticed there is a TwitchLib.Api package too, but it errors out with "A stable package for TwitchLib.Api.V5 (>= 3.02) could not be found"

**Comment by FunkyFr3sh** [comment]
Well, I'll just go with the unstable version for now. Glad to see the problem was already fixed, thanks!
