### ISSUE TITLE
OnNewFollower Event

### ISSUE THREAD

**Issue by jason-rietzke** [TwitchLib/TwitchLib#458]
Does somewon know how to get somthing like a onNewFollower event? There is a onNewSubscriber event in TwitchLib.Client. I saw there was this question in past but the answers are 2 years old and I couldn't find a way to addapt those comments for the todays version.

Please Help :(

**Comment by rootdarkarchon** [comment]
You can use TwitchLib.PubSub for that.

**Comment by jason-rietzke** [comment]
Oh I see, thank you

**Comment by neoconker61** [comment]
Pp0

**Comment by swiftyspiffy** [comment]
Closing, feel free to reopen if needed.
