### ISSUE TITLE
The Username of the ChatMessage returned by OnMessageReceivedArgs is in lower case

### ISSUE THREAD

**Issue by JonasKlose** [TwitchLib/TwitchLib#459]
The Username of the ChatMessage returned by OnMessageReceivedArgs is in lower case.

Is this a bug or is this intentional functionality?

I'd like to send a message back to the user with @{e.ChatMessage.Username}. That obviously won't work with a lower case user name when the user concerned has an upper case char in his account name.

**Comment by Mahsaap** [comment]
yes it does actually 
![image](https://user-images.githubusercontent.com/13688718/65471089-3f245980-de44-11e9-94af-dc8fbd8b609f.png)
![image](https://user-images.githubusercontent.com/13688718/65471101-4ba8b200-de44-11e9-8f77-eea44765b4c7.png)

**Comment by JonasKlose** [comment]
Ah, thanks for confirming that it's not only in my bot.

**Comment by Mahsaap** [comment]
No problem. There is a reason for lowercase but I dont remember off hand.

**Comment by swiftyspiffy** [comment]
So username is always lowercase, as that is what twitch has decided. There should be a DisplayName property that has the correct casing. Keep in mind though, the displayname field isn’t always 100% of the time set.  I think for really old accounts, it isn’t set.

**Comment by JonasKlose** [comment]
Ah, thank you. So DisplayName is null in that case?

Also, my bot appears with lower case letters when logged in in chat. Is that connected to this behavior?

**Comment by JonasKlose** [comment]
I think that this can be closed as by design. 
Maybe a little helpful info on the Username property could be added for other developers?

**Comment by swiftyspiffy** [comment]
Closing as requested.
