### ISSUE TITLE
Stream model missing UserName field

### ISSUE THREAD

**Issue by ShawnCholeva** [TwitchLib/TwitchLib#463]
I pulled down the TwitchLib nuget package and noticed there was a UserName (user_name) field missing from the GetStreamsResponse model in TwitchLib/TwitchLib.Api/TwitchLib.Api.Helix.Models/Streams/Stream.cs. 

 So I looked around the repositories and noticed that there was a PR to add this field in the TwitchLib.API repo (Link to PR: https://github.com/TwitchLib/TwitchLib.Api/pull/112), is it just the TwitchLib nuget package and TwitchLib.API nuget packages are out of sync with changes?  Would be cool to be able to get this fix in the main TwitchLib package.

**Comment by Mahsaap** [comment]
use pre release

**Comment by ShawnCholeva** [comment]
Ahhh gotcha, by pre-release you mean to just use the TwitchLib.Api nuget package directly?

**Comment by Mahsaap** [comment]
yes but install client,api,pubsub individually with pre release. the suite will not work.

**Comment by ShawnCholeva** [comment]
Worked well, thank you!
