### ISSUE TITLE
client.JoinRoom breaks normal chat functionality since Rooms deprecation

### ISSUE THREAD

**Issue by thquinn** [TwitchLib/TwitchLib#464]
[Twitch is deprecating chat room functionality.](https://pasteboard.co/IB4R61IB.png) This worked yesterday, but calling

`client.JoinRoom("197750788", "906788dd-d198-4e68-bd74-5562a52c1546");`

seems to now break normal chat events and behavior. Apparently they decided to flip some switches early. More an FYI for other people having a similar problem than an actual request to fix.

**Comment by swiftyspiffy** [comment]
Was not aware of this. Thanks for the heads up. Will review tomorrow after work and get a change out that removes it. Thanks.

**Comment by swiftyspiffy** [comment]
PR: https://github.com/TwitchLib/TwitchLib.Client/pull/125

**Comment by swiftyspiffy** [comment]
PR merged. Closing this. Feel free to reopen if needed.
