### ISSUE TITLE
How about Channel Point API?

### ISSUE THREAD

**Issue by Rumaruka** [TwitchLib/TwitchLib#469]
Twitch add Point System
Will you make API for this System?
![image](https://user-images.githubusercontent.com/8148679/70966541-68582d00-20b5-11ea-980d-b2ca615cb772.png)

**Comment by Mahsaap** [comment]
https://github.com/TwitchLib/TwitchLib.PubSub/pull/41 thus far

**Comment by Rumaruka** [comment]
Thanks
