### ISSUE TITLE
Conflicting Extensions.Logging.Abstractions nuget dependencies

### ISSUE THREAD

**Issue by thoralmighty** [TwitchLib/TwitchLib#471]
Hello, I'm using TwitchLib in a separate class library project in my solution which is then used by the main project. When I try to dynamically load the assemblies in the main project I get the following error:

> Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Both the class library project and the main project have Microsoft.Extensions.Logging.Abstractions version **3.1.2** installed and if I try to downgrade either of them back to 2.1.1.0, the following changes apply to TwitchLib:

> Microsoft.Extensions.Logging.Abstractions.3.1.2 -> Microsoft.Extensions.Logging.Abstractions.2.1.1
> TwitchLib.3.1.0 -> TwitchLib.3.0.1
> TwitchLib.PubSub.3.1.3 -> TwitchLib.PubSub.3.0.2

I still get the same error message, however this time it's trying to load a newer version:
> Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies.

This seems to be something in TwitchLib rather than my solution, any suggestions?

**Comment by swiftyspiffy** [comment]
This should be resolved now, I think. Feel free to reopen if needed.
