### ISSUE TITLE
Reduce CPU Usage

### ISSUE THREAD

**Issue by kimimaru4000** [TwitchLib/TwitchLib#475]
TwitchLib uses up a lot of my CPU, and I'm looking to reduce it since I'm running a simple bot that doesn't need many resources. The high CPU usage causes problems such as higher computer temperature and increased noise since the fans kick in.

[Here's](https://github.com/teamradish/TRTwitchPlaysBot/blob/master/TRBot/TRBotCore/Classes/BotProgram.cs#L263) how I'm throttling the main thread in my application. Everything else is handled through messages from TwitchLib. In addition, [the process is set to run at a lower priority](https://github.com/teamradish/TRTwitchPlaysBot/blob/master/TRBot/TRBotCore/Classes/BotProgram.cs#L82). However, I haven't had any success getting these to affect what TwitchLib is doing in the background. Is there a setting somewhere I can use to reduce the frequency TwitchLib operates to reduce CPU usage?

**Comment by LuckyNoS7evin** [comment]
The CPU use is down to bad code. I have several systems including a few t2.micro and nanos in AWS running TwitchLib. I can say that TwitchLib is not the cause of this.

**Comment by tdeeb** [comment]
You're correct, sorry for the inconvenience. I don't remember where I found that code snippet from a while ago, but it is not working as intended and I've resolved the issue.
