### ISSUE TITLE
TwitchApi.V5.Chat.GetAllChatEmoticonsAsync()

### ISSUE THREAD

**Issue by Zoidbert** [TwitchLib/TwitchLib#481]
Hi,

I have an Issue where i get the following exception:
>  TwitchLib.Api.Core.Exceptions.BadRequestException: "Your request failed because either: 
>  1. Your ClientID was invalid/not set. 
>  2. Your refresh token was invalid. 
>  3. You requested a username when the server was expecting a user ID."

My code is:
```
TwitchAPI = new TwitchLib.Api.TwitchAPI();
            TwitchAPI.Settings.ClientId = twitch_clientId;
            TwitchAPI.Settings.AccessToken = twitch_OAuth;
            TwitchAPI.Settings.Secret = twitch_secret;
            BadgeCollection = (await TwitchAPI.V5.Badges.GetGlobalBadgesAsync()).Sets; //Works
            EmoticonCollection = (await TwitchAPI.V5.Chat.GetAllChatEmoticonsAsync()).Emoticons; //Doesn't work
```

The first command (GetGlobalBadgesAsync) works fine, but in the second command I get the exception. I have checked my clientId and OAuth key and am not requesting a username or user ID as the exception mentioned. I could only imagine that the refresh token is the problem, but I don't see where to put one. I couldn't find any in the TwitchAPI.Settings.

**Comment by LuckyNoS7evin** [comment]
There is a current issue in that emoteset Zero (0) is causing a 500 on twitches side of things. This may be the issue for this error on the emotes call
