### ISSUE TITLE
OnRewardRedeemedArgs - RewardId is actually RedemptionId

### ISSUE THREAD

**Issue by kcoderhere** [TwitchLib/TwitchLib#482]
I'm trying to pull the RewardId (the unique ID of the reward being redeemed so I don't have to rely on the exact title name) from TwitchLib.PubSub.Events.OnRewardRedeemedArgs, but it turns out from examining the JSON response, the data being assigned to OnRewardRedeemedArgs.RewardId is actually the RedemptionId (the unique ID of the specific redemption event, not the ID of the reward).

**Comment by Mahsaap** [comment]
Rewardid is being used for the specific event. But I do agree the name is misleading and missing the other ID. Maybe RewardEventId would be better for this. And pull the reward ID for RewarďId. First time I've looked at this code. XD

Redemption 
`RewardId = Guid.Parse(json.SelectToken("data.redemption.id").ToString());`
Updated
`RewardId = Guid.Parse(json.SelectToken("data.updated_reward.id").ToString());`
Created
`RewardId = Guid.Parse(json.SelectToken("data.new_reward.id").ToString());`
Deleted
`RewardId = Guid.Parse(json.SelectToken("data.deleted_reward.id").ToString());`

**Comment by kcoderhere** [comment]
I suggested "RedemptionId" since it's the id under the "Redemption" node:

```
{
   "type":"redemption-status-update",
   "data":{
      "timestamp":"2020-05-11T04:59:03.674036526Z",
      "redemption":{
         "id":"46724533-94a0-45bd-815f-77bc2343c4de",
         "user":{
            "id":"1234567",
            "login":"mytwitchuser",
            "display_name":"MyTwitchUser"
         },
         "channel_id":"1234567",
         "redeemed_at":"2020-05-11T04:59:45.5325238Z",
         "reward":{
            "id":"2395bc3b-46d0-4731-817a-a53163b45467",
            "channel_id":"1234567",
            "title":"Test",
            "prompt":"Test",
            "cost":1,
            "is_user_input_required":false,
            "is_sub_only":false,
            "image":null,
            "default_image":null,
            "background_color":"#9147FF",
            "is_enabled":false,
            "is_paused":false,
            "is_in_stock":false,
            "max_per_stream":{
               "is_enabled":false,
               "max_per_stream":0
            },
            "should_redemptions_skip_request_queue":false,
            "template_id":null,
            "updated_for_indicator_at":null
         },
         "status":"ACTION_TAKEN",
         "cursor":"MmY4NzlX18yMDIwLTA1LTExVDA0OjQ5OjQ1LjMyOTI1Mjg4OFo="
      }
   }
}
```

**Comment by Mahsaap** [comment]
sure but its the same object used for redemption create new and delete. the other option would be adding the respective models for 4 different events

**Comment by kcoderhere** [comment]
Oh, maybe I misunderstood what you meant then.

It felt like it should be:

`RewardId = Guid.Parse(json.SelectToken("data.redemption.reward.id").ToString());`
So `RewardId` will match RewardId with all the other Create/Update/Delete events.

Then just add RedemptionId just for the Redemption event.
`RedemptionId = Guid.Parse(json.SelectToken("data.redemption.id").ToString());`

**Comment by Syzuna** [comment]
This was changed/fixed in the latest Pubsub prerelease nuget

CC: https://github.com/TwitchLib/TwitchLib.PubSub/pull/56
