### ISSUE TITLE
TwitchLib.Api.Core.Exceptions.BadScopeException When using LiveStreamMonitorService

### ISSUE THREAD

**Issue by jackie0100** [TwitchLib/TwitchLib#483]
Hey there I'm getting the following error each time I'm trying to use "LiveStreamMonitorService": TwitchLib.Api.Core.Exceptions.BadScopeException: 'Your request was blocked due to bad credentials (Do you have the right scope for your access token?).'

The problem has recently started and I could suspect the new changes in the twitch helix api may be to blame as it seem to be the only thing which is currently giving me problems I can fine use other calls fine so far.

My code/class looks as follow and is a single module in a group of multiple for a discord bot (using discord.net):

`
public class StreamAnnouncement : ModuleBase, IBotModule
    {
        DiscordShardedClient _client;

        LiveStreamMonitorService _monitor;
        TwitchAPI API;
        IConfigurationRoot _config;

        public StreamAnnouncement(IConfigurationRoot config, IServiceProvider services)
        {
            Console.WriteLine("Initializing Stream Announcement Module");
            _client = services.GetRequiredService<DiscordShardedClient>();
            _config = config;
        }

        public async Task SetupAsync()
        {
            _client.ShardReady += OnClientReady;
            await Task.Delay(-1);
        }

        public async Task StartAsync()
        {
            await Task.Delay(-1);
        }

        private async Task OnClientReady(DiscordSocketClient arg)
        {
            var streamerlist =_client.Guilds.First(x => x.Name == _config["TargetServer"]).Users.Where(x => x.Roles.Any(r => r.Name == "Streamer"));
            _client.UserUpdated += OnUserUpdated;

            API = new TwitchAPI();
            
            API.Settings.ClientId = _config["TwitchClientId"];
            API.Settings.AccessToken = _config["TwitchSecret"];
            var test = await API.V5.Users.GetUserByNameAsync("jacksendary"); //This works fine
            //API.Settings.Scopes = new List<AuthScopes>() { AuthScopes.Any, AuthScopes.Channel_Check_Subscription, AuthScopes.Channel_Commercial, AuthScopes.Channel_Editor, AuthScopes.Channel_Feed_Edit, AuthScopes.Channel_Feed_Read, AuthScopes.Channel_Read, AuthScopes.Channel_Stream, AuthScopes.Channel_Subscriptions, AuthScopes.Chat_Login, AuthScopes.Collections_Edit, AuthScopes.Communities_Edit, AuthScopes.Communities_Moderate, AuthScopes.Helix_Analytics_Read_Extensions, AuthScopes.Helix_Analytics_Read_Games, AuthScopes.Helix_Bits_Read, AuthScopes.Helix_Channel_Read_Subscriptions, AuthScopes.Helix_Clips_Edit, AuthScopes.Helix_Moderation_Read, AuthScopes.Helix_User_Edit, AuthScopes.Helix_User_Edit_Broadcast, AuthScopes.Helix_User_Read_Broadcast, AuthScopes.Helix_User_Read_Email, AuthScopes.OpenId, AuthScopes.User_Blocks_Edit, AuthScopes.User_Blocks_Read, AuthScopes.User_Follows_Edit, AuthScopes.User_Read, AuthScopes.User_Subscriptions, AuthScopes.Viewing_Activity_Read, }; //Even if I comment this line in it still doesn't work :(
            _monitor = new LiveStreamMonitorService(API, 60);
            _monitor.SetChannelsById(new List<string>() { test.Matches.Single().Id });

            _monitor.OnStreamOnline += Monitor_OnStreamOnline;
            _monitor.OnStreamOffline += Monitor_OnStreamOffline;
            _monitor.OnStreamUpdate += Monitor_OnStreamUpdate;

            _monitor.OnServiceStarted += Monitor_OnServiceStarted;
            _monitor.OnChannelsSet += Monitor_OnChannelsSet;
            _monitor.Start();

            Console.WriteLine("Stream Announcement Module Started");
            await Task.Delay(-1);
        }

        private async Task OnUserUpdated(SocketUser arg1, SocketUser arg2)
        {
            await Task.Delay(-1);
        }

        private void Monitor_OnStreamOnline(object sender, OnStreamOnlineArgs e)
        {
        }

        private void Monitor_OnStreamUpdate(object sender, OnStreamUpdateArgs e)
        {
        }

        private void Monitor_OnStreamOffline(object sender, OnStreamOfflineArgs e)
        {
        }

        private void Monitor_OnChannelsSet(object sender, OnChannelsSetArgs e)
        {
        }

        private void Monitor_OnServiceStarted(object sender, OnServiceStartedArgs e)
        {
            Console.WriteLine("Monitor service successfully connected to Twitch!");
        }

        [Command("set twitch", RunMode = RunMode.Async)]
        public async Task SetTwitchName([Remainder]string arg)
        {
            Console.WriteLine(arg);
        }
    }
`

**Comment by Mahsaap** [comment]
Secret is not token. There is a secret entry though in settings However a proper flow is better. Just requires the code to be made to pull this info.

**Comment by jackie0100** [comment]
Not sure how I missed that and why Access token worked for me up until recently but it actually seems it works now with using the secret property, would maybe suggest to to change the examples when possible but thank you @Mahsaap for the help, and sorry for my misunderstanding 👍

**Comment by Mahsaap** [comment]
Well its it's technically not wrong. It says token in access token spot. But yes I had started a pr but it didn't happen.

Also it's a change on twitch side that enforces this change and was ok before because it wasn't required to match with client Id.
