### ISSUE TITLE
Stream Marker

### ISSUE THREAD

**Issue by LightStriker** [TwitchLib/TwitchLib#485]
I'm probably blind... but I can't find how to create stream marker using the API.

Stream Markers; https://dev.twitch.tv/docs/api/reference#create-stream-marker

Am I missing something?

**Comment by royalkitsune** [comment]
There is an example on the page showing how to format the request to the right of the main body for me is this not showing up for you?
![image](https://user-images.githubusercontent.com/24488293/85647244-041db380-b66c-11ea-8633-bb07d03aa171.png)

**Comment by swiftyspiffy** [comment]
It looks like both Helix Markers functions are supported: https://github.com/TwitchLib/TwitchLib.Api/blob/master/TwitchLib.Api.Helix/Streams.cs#L147

Also apologies for the year+ delay lol
