### ISSUE TITLE
Unaccounted for: :tmi.twitch.tv NOTICE * :Login unsuccessful

### ISSUE THREAD

**Issue by k-kalashnikov** [TwitchLib/TwitchLib#487]
Hello there. I have a problem with connect TwitchClient.
![image](https://user-images.githubusercontent.com/2326820/83548760-5bb97b00-a515-11ea-8f2d-011ab553f67b.png)
![image](https://user-images.githubusercontent.com/2326820/83548781-65db7980-a515-11ea-8392-3742a61ef923.png)

**Comment by Mahsaap** [comment]
usessl option auto sets the uri btw.
Does the oauth have chat:read and chat:edit scopes? Does the oauth match the username in connectioncredentials?
u dont need oauth: attached to the oauth token in this lib.
have you tried with ssl? if its a problem without it?

This is all I can think of atm.

**Comment by jsedlak** [comment]
You need to go to https://twitchapps.com/tmi/ and get a token.

**Comment by swiftyspiffy** [comment]
This is a credentials issue, and Login unsuccessful is evented on in the library now. Feel free to reopen if needed.
