### ISSUE TITLE
Get channelId

### ISSUE THREAD

**Issue by zerocarbthirty** [TwitchLib/TwitchLib#488]
Hi there, I am working through some older code trying to update it a bit.

Everything I am finding in this library returns the name of the channel but twitch wants me to send channel ids.'

For example in this code:
``
public async Task<int> getChannel(string userName)
        {
            var theChannel = await api.V5.Channels.GetChannelAsync(userName);
            return theChannel.id;
        }
````
GetChannelAsync takes an authToken not a username, what is this authToken?

I've also tried this:

`public async Task<string> GetChan()
        {
            ChannelAuthed x = await api.V5.Channels.GetChannelAsync();
            return x.Id;
        }`

I really just need the channel id of JoinedChannels[0] thanks so much

**Comment by Mahsaap** [comment]
v5 has get user by username and you can get id from that.
helix has logins list that you can supply a list with a user in it and the return collection has that user with the id.

**Comment by Mahsaap** [comment]
V5= GetUserByUsername(username);
Helix= GetUsersAsync(logins: new List<string>(){"username"})[0].Id;

channelid = userid so still gets what you want.

**Comment by zerocarbthirty** [comment]
So if my bot is a different user than the owner of the channel but its a
mod on the channel it can get that info for the other user/channel?

thanks.

**Comment by Mahsaap** [comment]
yes that is not sesnsitive information.

**Comment by Mahsaap** [comment]
If you are good, can you close this issue please :)

**Comment by Syzuna** [comment]
This seems resolved. 
Closing this issue for now.

Feel free to reopen if further assistance is needed in this particular case
