### ISSUE TITLE
support multi-month sub gifting

### ISSUE THREAD

**Issue by Felk** [TwitchLib/TwitchLib#489]
twitch announced today that they changed sub notification data to account for the new multi-month sub gifting feature, in effect immediately. Read more here: https://discuss.dev.twitch.tv/t/updates-to-pubsub-messages-and-irc-for-multi-month-subscription-gifting

**Comment by Syzuna** [comment]
this was added to the dev branch already. its available in the latest prerelease nuget.

CC: https://github.com/TwitchLib/TwitchLib.Client/pull/146
