### ISSUE TITLE
Improve Release Transparency

### ISSUE THREAD

**Issue by kimimaru4000** [TwitchLib/TwitchLib#490]
First off, thank you very much for writing such a great and easy to use Twitch library. It's very powerful and has helped tremendously with many projects, including my own.

However, I'd like to see more transparency regarding the releases. The current version on [NuGet](https://www.nuget.org/packages/TwitchLib/) as of now is **3.1.1**. There is no associated tag or release for this on GitHub. In fact, the [latest release](https://github.com/TwitchLib/TwitchLib/releases/latest) on GitHub is **3.0.0, released almost two years ago**.

I can't find release notes or which commit each release on NuGet was built off of. Some of my projects using TwitchLib are in use by popular streamers, and I'd like to keep everything as stable as possible. I would like to see what's in each release (just the commit hash would suffice) so I can decide if I want to upgrade when one comes around. Otherwise, it's very hard for me to debug any issues that arise from TwitchLib itself, and I can't have full confidence in upgrading the version in my projects.

I hope you can provide some insight into this issue. Thanks!

**Comment by Mahsaap** [comment]
If your only looking at the suite page, that won't show you the latest commits in each respective repo. To see the updates in each version, go to each repo and there will be a version update commit so you can go from previous to that.

So on Nuget 

Release Notes
TwitchLib. Update aligns with:
TwitchLib.Api 3.1.3
TwitchLib.Client 3.1.5
TwitchLib.PubSub 3.1.4

so client for example https://github.com/TwitchLib/TwitchLib.Client/commits/master

**Comment by Mahsaap** [comment]
The suite is just an easy way to download them all instead of indiviually.

**Comment by tdeeb** [comment]
Thank you! I didn't know that the versions are mentioned in the commit messages :+1:.
