### ISSUE TITLE
TypeLoadException when loaded at runtime

### ISSUE THREAD

**Issue by jessfdm-codes** [TwitchLib/TwitchLib#494]
Hi,

I'm fairly certain this isn't an actual issue with the library itself more that I'd appreciate some pointers on where to look for the solution.

I'm trying to load in the TwitchLib Client from some framework 4.6.1 code (running inside a Unity game loaded at runtime - it's a mod), but when calling the constructor I get the following error and I'm really floored about how to approach this issue?

```
TypeLoadException: Invalid type TwitchLib.Client.Models.JoinedChannel[] for instance field System.Collections.Generic.Queue`1[TwitchLib.Client.Models.JoinedChannel]:_array
  at TwitchChatMod.TwitchChatClient.Init () [0x00046] in <2b5272e381784f419bedce259360c274>:0 
  at TwitchChatMod.TwitchChatClient.Start () [0x00001] in <2b5272e381784f419bedce259360c274>:0 
```

This is TwitchChatClient.Init():
```
private void Init()
        {
            Debug.Log("Client connection init...");

            if (client != null)
            {
                client.Disconnect();
            }

            ConnectionCredentials creds = new ConnectionCredentials(_username, _password);
            Debug.Log("Creating Client");
            client = new TwitchClient(); // It fails here
            Debug.Log("Client will be on channel: " + _channel);
            client.Initialize(creds, _channel);

            client.OnConnected += Client_OnConnected;
            client.OnJoinedChannel += Client_OnJoinedChannel;
            client.OnMessageReceived += Client_OnMessageReceived;
            client.OnDisconnected += Client_OnDisconnected;
            client.OnConnectionError += Client_OnConnectionError;
    

            //client.Connect();
        }
```

Any pointers would really be appreciated. I've made sure I'm using the netstandard nuget package to make it .NET Standard 2.0 compatible but maybe a reference is getting crossed over somewhere but I'm struggling to work it out.

**Comment by Mahsaap** [comment]
Unity requires a wrapper for the lib to work. We do have a repo for unity but I'm not sure how new it is. Only a couple people work on it.

**Comment by thomasfdm** [comment]
It's definetly working in Unity because it worked in a test project, but it's just when I try and load it in with reflection i get this error.

**Comment by MopsiMauser** [comment]
I guess you maybe need to load the TwitchLib.Client.Models (and maybe TwitchLib.Client.Enums) assembly as well, when you load TwitchLib.Client via reflection at runtime.

**Comment by swiftyspiffy** [comment]
Going to go ahead and close this. Feel free to reopen if there are still issues you think we can help with.
