### ISSUE TITLE
C# simple send message 

### ISSUE THREAD

**Issue by caiouechi** [TwitchLib/TwitchLib#495]
My OAuth (from the **OIDC implicit code flow**) is valid:
![image](https://user-images.githubusercontent.com/4606180/93291020-08132a80-f7b0-11ea-9210-3657e41dd248.png)

I used the access token returned, but it is still not logging. Can you help me?
![image](https://user-images.githubusercontent.com/4606180/93291062-2711bc80-f7b0-11ea-880f-019d520f4dca.png)

![image](https://user-images.githubusercontent.com/4606180/93291083-2f69f780-f7b0-11ea-9c6a-6ba4ccadae8e.png)

**Comment by Mahsaap** [comment]
https://github.com/TwitchLib/TwitchLib.Client/blob/1dc45145654ac467a7568c88770c0df258a2bedb/TwitchLib.Client.Models/ConnectionCredentials.cs#L19

It uses OAuth in ConnectionCredentials.

**Comment by swiftyspiffy** [comment]
Looks like a credentials error. Please reopen if you still need help.
