### ISSUE TITLE
PubSub Service Randomly Disconnects, not able to reconnect

### ISSUE THREAD

**Issue by artibex** [TwitchLib/TwitchLib#496]
I'm looking into this problem a while now. There is no particular reason why or when it's happening. Sometimes the bot is 5 minutes online and stopped working and sometimes it works an hour or longer.

Also, `OnPubSubServiceClosed` and `OnPubSubServiceError` never fired ever. The bot just stops listening. I use it to trigger code via Channel Point redemption and it's just not reliable at all. I'v installed TwitchLib via NuGet in version 3.1.1 and TwitchLib.PubSub is in version 3.1.4. Somebody know what I'm doing wrong perhaps?

Code:

```
public static void Init() 
{
    pubsub = new TwitchPubSub(); //init PubSub

    //Connect PubSub events with custom Methods
    pubsub.OnPubSubServiceConnected += Pubsub_OnPubSubServiceConnected;
    pubsub.OnPubSubServiceClosed += Pubsub_OnPubSubServiceDisconnect; //Reconnect if connection is lost
    pubsub.OnPubSubServiceError += Pubsub_OnPubSubServiceError; //Reconnect if error
    pubsub.OnListenResponse += Pubsub_OnListenResponse;
    pubsub.OnRewardRedeemed += Pubsub_OnRewardRedeemed;

    pubsub.Connect(); //Connect
}

private static void Pubsub_OnPubSubServiceConnected(object sender, System.EventArgs e)
{
    pubsub.ListenToRewards(FileManager.GetChannelID()); //Set Channel ID
    pubsub.SendTopics(FileManager.GetOAuth()); //Give OAuth Key and connect
}

private static void Pubsub_OnPubSubServiceError(object sender, System.EventArgs e)
{
    Console.WriteLine("Some Pubsub Error Occured, try to reconnect");
    Console.WriteLine(e);
    pubsub.Connect();
}

private static void Pubsub_OnPubSubServiceDisconnect(object sender, System.EventArgs e)
{
    Console.WriteLine("PubSub got Disconnected, try to reconnect");
    Console.WriteLine(e);
    pubsub.Connect();
}

private static void Pubsub_OnListenResponse(object sender, OnListenResponseArgs e)
{
    if (!e.Successful)
        throw new Exception($"Failed to listen! Response: {e.Topic}");
    else Console.WriteLine("Connected to PubSub");
}

private static void Pubsub_OnRewardRedeemed(object sender, OnRewardRedeemedArgs e)
{
    CommandIdentifier.CheckCommand(e); //Process given Channel Point redemption
    //RewardRedeemedDebug(e); //Log everything of a channel point redemption
}
```

**Comment by Bregann** [comment]
I've been having this too recently and I think it might be around the complete all / reject all buttons of the reward requests queue. Haven't had a chance to dig into it further though if its something wrong in my code of its a genuine bug with library

**Comment by Shaggy84675** [comment]
It behaves for me really weird as well. When PubSub disconnects (it can happen after few hours or even few days), it calls twice OnPubSubServiceError event and then OnPubSubServiceClosed. When I'm trying to reconnect it, it sometimes works, sometimes not. Sometimes something happens with TwitchClient service because after calling pubSub.Connect method the TwitchClient service is not listening for chat commands and chat globally. Maybe I need to put some delay after it crashes and after I'm trying reconnect? But I have already 100ms there. Maybe it's something wrong in my code, but I don't think so. I'm not using anything special. I'd be glad if there exist Reconnect method for PubSub as well as it exists in TwitchClient. Would be possible to implement it? And yeah I think something wrong is with the events.

**Comment by Omsad** [comment]
Subscribing to the rewards events will cause the PubSub service to disconnect if a user accepts or rejects all redemptions. See [Issue 65](https://github.com/TwitchLib/TwitchLib.PubSub/issues/65) I've reported today.

**Comment by Korpsian** [comment]
I'v never accepted or rejected ANY redemption and it still disconnects for me.

**Comment by MedicGuy** [comment]
I am having the same issue, whether i accept any redemptions or not. No disconnect, closed or error events fire and OnLog still shows pings going on.

**Comment by Omsad** [comment]
I've created a pull request to fix the above. 

I don't know if it will fix you're random disconnects but from what I understand sending a PING message by it's self isn't enough. If you don't get a PONG message back within 10 seconds you're effectivity disconnected, see https://dev.twitch.tv/docs/pubsub#connection-management .  

In the same documentation it mentions that Twitch can, at anytime, send a RECONNECT message signalling that the server you're connected to is restarting. Currently this is also unhandled, which the pull-request attempts to fix.

**Comment by MedicGuy** [comment]
I did mean to write PONG.

I found a temporary solution for anyone having the issue. I am using a timer that triggers every 10 minutes and resends the topics and restarts listening to the redemptions. 

Has been working for ~5 Hours now

**Comment by Korpsian** [comment]
@MedicGuy I try to renew pubsub ever 10 minutes but I run into the weird problem that suddenly `OnPubSubServiceError` is triggering, which should disconnect it, and reconnect it but it's now stuck in a loop of `OnPubSubServiceError` trigger. I mean, I COMPLETLY yeet that thing away and create a new one and it triggers non stop.

**Comment by MedicGuy** [comment]
i dont even disconnect, i just reuse listentorewards and sendtopics :)

**Comment by MedicGuy** [comment]
> 
> 
> @MedicGuy I try to renew pubsub ever 10 minutes but I run into the weird problem that suddenly `OnPubSubServiceError` is triggering, which should disconnect it, and reconnect it but it's now stuck in a loop of `OnPubSubServiceError` trigger. I mean, I COMPLETLY yeet that thing away and create a new one and it triggers non stop.

 i dont even disconnect, i just reuse listentorewards and sendtopics :)

**Comment by Korpsian** [comment]
Ok after a long testing and eveen with the renewing of pubsub I STILL get random disconnects ranging from 2 minutes to 40 minutes and.... it makes no sense to me...

**Comment by swiftyspiffy** [comment]
Following up on this, I haven't seen any new instances of these disconnects. Fee free to reopen if you're still encountering them.
