### ISSUE TITLE
Own Messages doesn't trigger the OnMessageReceived listener.

### ISSUE THREAD

**Issue by Strencher** [TwitchLib/TwitchLib#497]
i've added a listener for messages to the `OnMessageReceived` method of the client and it doesn't seem to catch my own messages.

**Comment by Mahsaap** [comment]
Are you trying to receive messages from the same account your connected to with the client?

**Comment by Strencher** [comment]
yes, i wanna get the messages i send too.

**Comment by Strencher** [comment]
aah, okay, thanks
