### ISSUE TITLE
OnLog Unaccounted For

### ISSUE THREAD

**Issue by StreamTalker** [TwitchLib/TwitchLib#498]
Noticed this in my Logs.
It says to create an issue here on GitHub, so here is what I received:

Date :17-Oct-20 17:23:29 Data: Received: :tmi.twitch.tv CAP * ACK :twitch.tv/membership<br/>

Date :17-Oct-20 17:23:29 Data: Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/membership (please create a TwitchLib GitHub issue :P)

Date :17-Oct-20 17:23:29 Data: Received: :tmi.twitch.tv CAP * ACK :twitch.tv/commands<br/>

Date :17-Oct-20 17:23:29 Data: Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/commands (please create a TwitchLib GitHub issue :P)

Date :17-Oct-20 17:23:29 Data: Received: :tmi.twitch.tv CAP * ACK :twitch.tv/tags<br/>

Date :17-Oct-20 17:23:29 Data: Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/tags (please create a TwitchLib GitHub issue :P)

Have not seen any noticeable effects but thought this info might be helpful.

**Comment by swiftyspiffy** [comment]
The "Unaccounted for" messages are intended to alert devs to potentially new data Twitch is sending that the library is not expecting.

In this (rare) case, these CAP (capacity) messages are a result of the library requesting them, and Twitch confirming. In this case, this is expected, and the library just isn't handling the confirmations from Twitch (largely unnecessary). Fear not!
