### ISSUE TITLE
ThirdParty.AuthorizationFlow.OnUserAuthorizationDetected 

### ISSUE THREAD

**Issue by Thefrenchdev** [TwitchLib/TwitchLib#499]
HI, 
I'm trying to use the ThirdParty AuthorizationFlow to then get my channel subscribers.
How do I get the client_id when the user is connected.

Here is what I tried from now.

```
var scopes = new List<AuthScopes>() { AuthScopes.Helix_Channel_Read_Subscriptions };
api.ThirdParty.AuthorizationFlow.OnUserAuthorizationDetected += (s, e) =>
            {
              var pingstatus=  api.ThirdParty.AuthorizationFlow.PingStatus(id);
            };
            var createdFlow = api.ThirdParty.AuthorizationFlow.CreateFlow("Mon Appli", scopes);
            api.ThirdParty.AuthorizationFlow.BeginPingingStatus(createdFlow.Id);

            await OpenBrowser(new Uri(createdFlow.Url));
```
The user can connect but from the "Authorisationdetectedargs" i can't get the client id

Thanks

**Comment by swiftyspiffy** [comment]
Hi.

If you are using the dev branch/prerelease nuget package, you'll find `ClientId` in the `PingResponse` object:
https://github.com/TwitchLib/TwitchLib.Api/blob/dev/TwitchLib.Api/ThirdParty/AuthorizationFlow/PingResponse.cs#L20

**Comment by Thefrenchdev** [comment]
It's Exactly what i tried but how and when to call the PingResponse.

When i call it when the Auth is detected i get a message : Already activated

**Comment by swiftyspiffy** [comment]
Ahh, I see the issue. APologies for the delay. See PR: https://github.com/TwitchLib/TwitchLib.Api/pull/156

**Comment by Thefrenchdev** [comment]
@swiftyspiffy Don't Apologies 
That was exactly what I needed Thank you so much.

Just One last things : 
On the Authorizationdetectedargs the `e.id` seems to be always null Maybe there's an issue with the response class
