### ISSUE TITLE
OnModeratorJoined event not working

### ISSUE THREAD

**Issue by SebastianSieb** [TwitchLib/TwitchLib#500]
Hi,
I got an issue subscribing to the `OnModeratorJoined` event.
While events like `OnMessageReceived` or `OnJoinedChannel` work properly the `OnModeratorJoined` event is not fired at all (verified by a breakpoint in the `Client_OnModeratorJoined` method).

I tried to trigger the event by subscribing the Bot to a channel I´m a moderator of. When I joined the channel and wrote something in the chat the event was not fired, however the twitch mod view listed me as "user in chat".

Is there a known issue with this event, or am I missing something?

My Setup looks like this:

```c#
ConnectionCredentials credentials =
    new ConnectionCredentials("<userName>", "<OAuthToken>");
var clientOptions = new ClientOptions
{
    MessagesAllowedInPeriod = 750,
    ThrottlingPeriod = TimeSpan.FromSeconds(1)
};
WebSocketClient customClient = new WebSocketClient(clientOptions);
_client = new TwitchClient(customClient);
_client.Initialize(credentials, "einhornkatze");

_client.OnJoinedChannel += Client_OnJoinedChannel;
_client.OnMessageReceived += Client_OnMessageReceived;
_client.OnModeratorJoined += Client_OnModeratorJoined;
_client.OnUserBanned += Client_OnUserBanned;

_client.Connect();
```
And this my `Client_OnModeratorJoined` implementation:

```c#
private void Client_OnModeratorJoined(object sender, OnModeratorJoinedArgs e)
{
    // TODO this event is not fired somehow
    _client.SendMessage(e.Channel, $"test {e.Username}");
}
```

Great Lib though! ;)

**Comment by 3ventic** [comment]
Twitch removed support for the underlying event earlier this year. I don't think TwitchLib will continue supporting the event going forward due to moderator list requiring an additional auth scope.

Listen to joins, maintain a list of moderators, and filter the event based on that list.

**Comment by SebastianSieb** [comment]
Thank you for your fast answer! Using the OnUserJoin-Event worked for me.
