### ISSUE TITLE
How do the "sendwhisper" command Whisper works?

### ISSUE THREAD

**Issue by Thefrenchdev** [TwitchLib/TwitchLib#501]
I've tried so many ways but never successed it.

Questions : 
- Is it possible to send a whisper to someone with my account?
-How? What are the prerequisites?

I dont wanna pass trough chat but only whisper someone.

What i Have from now

`private static TwitchClient client = new TwitchClient();
        static void Main(string[] args)
        {
            client.Initialize(new ConnectionCredentials("myusername", "*************"));
            client.OnConnected += Client_OnConnected;
            client.OnConnectionError += Client_OnConnectionError;
            
          client.Connect();  
 }
        private static void Client_OnConnectionError(object sender, TwitchLib.Client.Events.OnConnectionErrorArgs e)
        {
            Console.WriteLine(e.Error);
        }

        private static void Client_OnConnected(object sender, TwitchLib.Client.Events.OnConnectedArgs e)
        {            
            Console.WriteLine("Client Connected");
            client.SendWhisper("whisperreceiver", "heeyyyyyyy");
        }
    }
`

I never get either onconnected or onconnectionerror events

**Comment by Mahsaap** [comment]
Whispers require a known bot with newer tokens. This has to be requested through a twitch form. I don't know the link off hand atm.

**Comment by Mahsaap** [comment]
https://dev.twitch.tv/limit-increase

**Comment by Thefrenchdev** [comment]
Thanks.
